// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/id_extract_service/v1/regions_enum.proto
// Protobuf Java Version: 4.28.2

package proto.id_extract_service.v1;

public final class RegionsEnum {
  private RegionsEnum() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      RegionsEnum.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * Region - enumeration of supported regions.
   * </pre>
   *
   * Protobuf enum {@code proto.id_extract_service.v1.Region}
   */
  public enum Region
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * Undefined
     * </pre>
     *
     * <code>REGION_UNDEFINED = 0;</code>
     */
    REGION_UNDEFINED(0),
    /**
     * <pre>
     * New South Wales in Australia
     * </pre>
     *
     * <code>REGION_AUSTRALIA_NEW_SOUTH_WALES = 1;</code>
     */
    REGION_AUSTRALIA_NEW_SOUTH_WALES(1),
    /**
     * <pre>
     * Northern Territory in Australia
     * </pre>
     *
     * <code>REGION_AUSTRALIA_NORTHERN_TERRITORY = 2;</code>
     */
    REGION_AUSTRALIA_NORTHERN_TERRITORY(2),
    /**
     * <pre>
     * Queensland in Australia
     * </pre>
     *
     * <code>REGION_AUSTRALIA_QUEENSLAND = 3;</code>
     */
    REGION_AUSTRALIA_QUEENSLAND(3),
    /**
     * <pre>
     * South Australia in Australia
     * </pre>
     *
     * <code>REGION_AUSTRALIA_SOUTH_AUSTRALIA = 4;</code>
     */
    REGION_AUSTRALIA_SOUTH_AUSTRALIA(4),
    /**
     * <pre>
     * Tasmania in Australia
     * </pre>
     *
     * <code>REGION_AUSTRALIA_TASMANIA = 5;</code>
     */
    REGION_AUSTRALIA_TASMANIA(5),
    /**
     * <pre>
     * Victoria in Australia
     * </pre>
     *
     * <code>REGION_AUSTRALIA_VICTORIA = 6;</code>
     */
    REGION_AUSTRALIA_VICTORIA(6),
    /**
     * <pre>
     * Western Australia in Australia
     * </pre>
     *
     * <code>REGION_AUSTRALIA_WESTERN_AUSTRALIA = 7;</code>
     */
    REGION_AUSTRALIA_WESTERN_AUSTRALIA(7),
    /**
     * <pre>
     * Australian Capital Territory in Australia
     * </pre>
     *
     * <code>REGION_AUSTRALIA_AUSTRALIAN_CAPITAL_TERRITORY = 8;</code>
     */
    REGION_AUSTRALIA_AUSTRALIAN_CAPITAL_TERRITORY(8),
    /**
     * <pre>
     * Sao Paolo in Brazil
     * </pre>
     *
     * <code>REGION_BRAZIL_SAO_PAOLO = 9;</code>
     */
    REGION_BRAZIL_SAO_PAOLO(9),
    /**
     * <pre>
     * Distrito Federal in Brazil
     * </pre>
     *
     * <code>REGION_BRAZIL_DISTRITO_FEDERAL = 10;</code>
     */
    REGION_BRAZIL_DISTRITO_FEDERAL(10),
    /**
     * <pre>
     * Maranhao in Brazil
     * </pre>
     *
     * <code>REGION_BRAZIL_MARANHAO = 11;</code>
     */
    REGION_BRAZIL_MARANHAO(11),
    /**
     * <pre>
     * Santa Catarina in Brazil
     * </pre>
     *
     * <code>REGION_BRAZIL_SANTA_CATARINA = 12;</code>
     */
    REGION_BRAZIL_SANTA_CATARINA(12),
    /**
     * <pre>
     * Ceara in Brazil
     * </pre>
     *
     * <code>REGION_BRAZIL_CEARA = 13;</code>
     */
    REGION_BRAZIL_CEARA(13),
    /**
     * <pre>
     * Goias in Brazil
     * </pre>
     *
     * <code>REGION_BRAZIL_GOIAS = 14;</code>
     */
    REGION_BRAZIL_GOIAS(14),
    /**
     * <pre>
     * Rio Grande Do Sul in Brazil
     * </pre>
     *
     * <code>REGION_BRAZIL_RIO_GRANDE_DO_SUL = 15;</code>
     */
    REGION_BRAZIL_RIO_GRANDE_DO_SUL(15),
    /**
     * <pre>
     * Pernambuco in Brazil
     * </pre>
     *
     * <code>REGION_BRAZIL_PERNAMBUCO = 16;</code>
     */
    REGION_BRAZIL_PERNAMBUCO(16),
    /**
     * <pre>
     * Rio De Janeiro in Brazil
     * </pre>
     *
     * <code>REGION_BRAZIL_RIO_DE_JANEIRO = 17;</code>
     */
    REGION_BRAZIL_RIO_DE_JANEIRO(17),
    /**
     * <pre>
     * Parana in Brazil
     * </pre>
     *
     * <code>REGION_BRAZIL_PARANA = 18;</code>
     */
    REGION_BRAZIL_PARANA(18),
    /**
     * <pre>
     * Sergipe in Brazil
     * </pre>
     *
     * <code>REGION_BRAZIL_SERGIPE = 19;</code>
     */
    REGION_BRAZIL_SERGIPE(19),
    /**
     * <pre>
     * Mato Grosso in Brazil
     * </pre>
     *
     * <code>REGION_BRAZIL_MATO_GROSSO = 20;</code>
     */
    REGION_BRAZIL_MATO_GROSSO(20),
    /**
     * <pre>
     * Minas Gerais in Brazil
     * </pre>
     *
     * <code>REGION_BRAZIL_MINAS_GERAIS = 21;</code>
     */
    REGION_BRAZIL_MINAS_GERAIS(21),
    /**
     * <pre>
     * Para in Brazil
     * </pre>
     *
     * <code>REGION_BRAZIL_PARA = 22;</code>
     */
    REGION_BRAZIL_PARA(22),
    /**
     * <pre>
     * Prince Edward Island in Canada
     * </pre>
     *
     * <code>REGION_CANADA_PRINCE_EDWARD_ISLAND = 23;</code>
     */
    REGION_CANADA_PRINCE_EDWARD_ISLAND(23),
    /**
     * <pre>
     * Quebec in Canada
     * </pre>
     *
     * <code>REGION_CANADA_QUEBEC = 24;</code>
     */
    REGION_CANADA_QUEBEC(24),
    /**
     * <pre>
     * Manitoba in Canada
     * </pre>
     *
     * <code>REGION_CANADA_MANITOBA = 25;</code>
     */
    REGION_CANADA_MANITOBA(25),
    /**
     * <pre>
     * New Brunswick in Canada
     * </pre>
     *
     * <code>REGION_CANADA_NEW_BRUNSWICK = 26;</code>
     */
    REGION_CANADA_NEW_BRUNSWICK(26),
    /**
     * <pre>
     * Newfoundland And Labrador in Canada
     * </pre>
     *
     * <code>REGION_CANADA_NEWFOUNDLAND_AND_LABRADOR = 27;</code>
     */
    REGION_CANADA_NEWFOUNDLAND_AND_LABRADOR(27),
    /**
     * <pre>
     * Northwest Territories in Canada
     * </pre>
     *
     * <code>REGION_CANADA_NORTHWEST_TERRITORIES = 28;</code>
     */
    REGION_CANADA_NORTHWEST_TERRITORIES(28),
    /**
     * <pre>
     * Nunavut in Canada
     * </pre>
     *
     * <code>REGION_CANADA_NUNAVUT = 29;</code>
     */
    REGION_CANADA_NUNAVUT(29),
    /**
     * <pre>
     * Yukon in Canada
     * </pre>
     *
     * <code>REGION_CANADA_YUKON = 30;</code>
     */
    REGION_CANADA_YUKON(30),
    /**
     * <pre>
     * Alberta in Canada
     * </pre>
     *
     * <code>REGION_CANADA_ALBERTA = 31;</code>
     */
    REGION_CANADA_ALBERTA(31),
    /**
     * <pre>
     * British Columbia in Canada
     * </pre>
     *
     * <code>REGION_CANADA_BRITISH_COLUMBIA = 32;</code>
     */
    REGION_CANADA_BRITISH_COLUMBIA(32),
    /**
     * <pre>
     * Nova Scotia in Canada
     * </pre>
     *
     * <code>REGION_CANADA_NOVA_SCOTIA = 33;</code>
     */
    REGION_CANADA_NOVA_SCOTIA(33),
    /**
     * <pre>
     * Ontario in Canada
     * </pre>
     *
     * <code>REGION_CANADA_ONTARIO = 34;</code>
     */
    REGION_CANADA_ONTARIO(34),
    /**
     * <pre>
     * Saskatchewan in Canada
     * </pre>
     *
     * <code>REGION_CANADA_SASKATCHEWAN = 35;</code>
     */
    REGION_CANADA_SASKATCHEWAN(35),
    /**
     * <pre>
     * Andhra Pradesh in India
     * </pre>
     *
     * <code>REGION_INDIA_ANDHRA_PRADESH = 36;</code>
     */
    REGION_INDIA_ANDHRA_PRADESH(36),
    /**
     * <pre>
     * Tamil Nadu in India
     * </pre>
     *
     * <code>REGION_INDIA_TAMIL_NADU = 37;</code>
     */
    REGION_INDIA_TAMIL_NADU(37),
    /**
     * <pre>
     * Gujarat in India
     * </pre>
     *
     * <code>REGION_INDIA_GUJARAT = 38;</code>
     */
    REGION_INDIA_GUJARAT(38),
    /**
     * <pre>
     * Haryana in India
     * </pre>
     *
     * <code>REGION_INDIA_HARYANA = 39;</code>
     */
    REGION_INDIA_HARYANA(39),
    /**
     * <pre>
     * Karnataka in India
     * </pre>
     *
     * <code>REGION_INDIA_KARNATAKA = 40;</code>
     */
    REGION_INDIA_KARNATAKA(40),
    /**
     * <pre>
     * Kerala in India
     * </pre>
     *
     * <code>REGION_INDIA_KERALA = 41;</code>
     */
    REGION_INDIA_KERALA(41),
    /**
     * <pre>
     * Madhya Pradesh in India
     * </pre>
     *
     * <code>REGION_INDIA_MADHYA_PRADESH = 42;</code>
     */
    REGION_INDIA_MADHYA_PRADESH(42),
    /**
     * <pre>
     * Maharashtra in India
     * </pre>
     *
     * <code>REGION_INDIA_MAHARASHTRA = 43;</code>
     */
    REGION_INDIA_MAHARASHTRA(43),
    /**
     * <pre>
     * Punjab in India
     * </pre>
     *
     * <code>REGION_INDIA_PUNJAB = 44;</code>
     */
    REGION_INDIA_PUNJAB(44),
    /**
     * <pre>
     * Chiapas in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_CHIAPAS = 45;</code>
     */
    REGION_MEXICO_CHIAPAS(45),
    /**
     * <pre>
     * Chihuahua in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_CHIHUAHUA = 46;</code>
     */
    REGION_MEXICO_CHIHUAHUA(46),
    /**
     * <pre>
     * Durango in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_DURANGO = 47;</code>
     */
    REGION_MEXICO_DURANGO(47),
    /**
     * <pre>
     * Guerrero-Juchitan in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_GUERRERO_JUCHITAN = 48;</code>
     */
    REGION_MEXICO_GUERRERO_JUCHITAN(48),
    /**
     * <pre>
     * Baja California Sur in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_BAJA_CALIFORNIA_SUR = 49;</code>
     */
    REGION_MEXICO_BAJA_CALIFORNIA_SUR(49),
    /**
     * <pre>
     * Ciudad De Mexico in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_CIUDAD_DE_MEXICO = 50;</code>
     */
    REGION_MEXICO_CIUDAD_DE_MEXICO(50),
    /**
     * <pre>
     * Jalisco in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_JALISCO = 51;</code>
     */
    REGION_MEXICO_JALISCO(51),
    /**
     * <pre>
     * Mexico in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_MEXICO = 52;</code>
     */
    REGION_MEXICO_MEXICO(52),
    /**
     * <pre>
     * Nuevo Leon in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_NUEVO_LEON = 53;</code>
     */
    REGION_MEXICO_NUEVO_LEON(53),
    /**
     * <pre>
     * Veracruz in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_VERACRUZ = 54;</code>
     */
    REGION_MEXICO_VERACRUZ(54),
    /**
     * <pre>
     * Aguascalientes in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_AGUASCALIENTES = 55;</code>
     */
    REGION_MEXICO_AGUASCALIENTES(55),
    /**
     * <pre>
     * Queretaro in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_QUERETARO = 56;</code>
     */
    REGION_MEXICO_QUERETARO(56),
    /**
     * <pre>
     * Quintana Roo-Cozumel in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_QUINTANA_ROO_COZUMEL = 57;</code>
     */
    REGION_MEXICO_QUINTANA_ROO_COZUMEL(57),
    /**
     * <pre>
     * San Luis Potosi in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_SAN_LUIS_POTOSI = 58;</code>
     */
    REGION_MEXICO_SAN_LUIS_POTOSI(58),
    /**
     * <pre>
     * Morelos in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_MORELOS = 59;</code>
     */
    REGION_MEXICO_MORELOS(59),
    /**
     * <pre>
     * Oaxaca in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_OAXACA = 60;</code>
     */
    REGION_MEXICO_OAXACA(60),
    /**
     * <pre>
     * Puebla in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_PUEBLA = 61;</code>
     */
    REGION_MEXICO_PUEBLA(61),
    /**
     * <pre>
     * Sinaloa in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_SINALOA = 62;</code>
     */
    REGION_MEXICO_SINALOA(62),
    /**
     * <pre>
     * Sonora in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_SONORA = 63;</code>
     */
    REGION_MEXICO_SONORA(63),
    /**
     * <pre>
     * Coahuila in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_COAHUILA = 64;</code>
     */
    REGION_MEXICO_COAHUILA(64),
    /**
     * <pre>
     * Hidalgo in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_HIDALGO = 65;</code>
     */
    REGION_MEXICO_HIDALGO(65),
    /**
     * <pre>
     * Zacatecas in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_ZACATECAS = 66;</code>
     */
    REGION_MEXICO_ZACATECAS(66),
    /**
     * <pre>
     * Campeche in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_CAMPECHE = 67;</code>
     */
    REGION_MEXICO_CAMPECHE(67),
    /**
     * <pre>
     * Quintana Roo-Benito Juarez in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_QUINTANA_ROO_BENITO_JUAREZ = 68;</code>
     */
    REGION_MEXICO_QUINTANA_ROO_BENITO_JUAREZ(68),
    /**
     * <pre>
     * Quintana Roo in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_QUINTANA_ROO = 69;</code>
     */
    REGION_MEXICO_QUINTANA_ROO(69),
    /**
     * <pre>
     * Tabasco in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_TABASCO = 70;</code>
     */
    REGION_MEXICO_TABASCO(70),
    /**
     * <pre>
     * Tamaulipas in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_TAMAULIPAS = 71;</code>
     */
    REGION_MEXICO_TAMAULIPAS(71),
    /**
     * <pre>
     * Guerrero-Acapulco De Juarez in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_GUERRERO_ACAPULCO_DE_JUAREZ = 72;</code>
     */
    REGION_MEXICO_GUERRERO_ACAPULCO_DE_JUAREZ(72),
    /**
     * <pre>
     * Tlaxcala in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_TLAXCALA = 73;</code>
     */
    REGION_MEXICO_TLAXCALA(73),
    /**
     * <pre>
     * Nayarit in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_NAYARIT = 74;</code>
     */
    REGION_MEXICO_NAYARIT(74),
    /**
     * <pre>
     * Colima in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_COLIMA = 75;</code>
     */
    REGION_MEXICO_COLIMA(75),
    /**
     * <pre>
     * Guanajuato in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_GUANAJUATO = 76;</code>
     */
    REGION_MEXICO_GUANAJUATO(76),
    /**
     * <pre>
     * Michoacan in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_MICHOACAN = 77;</code>
     */
    REGION_MEXICO_MICHOACAN(77),
    /**
     * <pre>
     * Quintana Roo-Solidaridad in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_QUINTANA_ROO_SOLIDARIDAD = 78;</code>
     */
    REGION_MEXICO_QUINTANA_ROO_SOLIDARIDAD(78),
    /**
     * <pre>
     * Yucatan in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_YUCATAN = 79;</code>
     */
    REGION_MEXICO_YUCATAN(79),
    /**
     * <pre>
     * Baja California in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_BAJA_CALIFORNIA = 80;</code>
     */
    REGION_MEXICO_BAJA_CALIFORNIA(80),
    /**
     * <pre>
     * Khyber Pakhtunkhwa in Pakistan
     * </pre>
     *
     * <code>REGION_PAKISTAN_KHYBER_PAKHTUNKHWA = 81;</code>
     */
    REGION_PAKISTAN_KHYBER_PAKHTUNKHWA(81),
    /**
     * <pre>
     * Punjab in Pakistan
     * </pre>
     *
     * <code>REGION_PAKISTAN_PUNJAB = 82;</code>
     */
    REGION_PAKISTAN_PUNJAB(82),
    /**
     * <pre>
     * Arizona in USA
     * </pre>
     *
     * <code>REGION_USA_ARIZONA = 83;</code>
     */
    REGION_USA_ARIZONA(83),
    /**
     * <pre>
     * Minnesota in USA
     * </pre>
     *
     * <code>REGION_USA_MINNESOTA = 84;</code>
     */
    REGION_USA_MINNESOTA(84),
    /**
     * <pre>
     * Oklahoma in USA
     * </pre>
     *
     * <code>REGION_USA_OKLAHOMA = 85;</code>
     */
    REGION_USA_OKLAHOMA(85),
    /**
     * <pre>
     * South Dakota in USA
     * </pre>
     *
     * <code>REGION_USA_SOUTH_DAKOTA = 86;</code>
     */
    REGION_USA_SOUTH_DAKOTA(86),
    /**
     * <pre>
     * Utah in USA
     * </pre>
     *
     * <code>REGION_USA_UTAH = 87;</code>
     */
    REGION_USA_UTAH(87),
    /**
     * <pre>
     * Nevada in USA
     * </pre>
     *
     * <code>REGION_USA_NEVADA = 88;</code>
     */
    REGION_USA_NEVADA(88),
    /**
     * <pre>
     * Texas in USA
     * </pre>
     *
     * <code>REGION_USA_TEXAS = 89;</code>
     */
    REGION_USA_TEXAS(89),
    /**
     * <pre>
     * Iowa in USA
     * </pre>
     *
     * <code>REGION_USA_IOWA = 90;</code>
     */
    REGION_USA_IOWA(90),
    /**
     * <pre>
     * Montana in USA
     * </pre>
     *
     * <code>REGION_USA_MONTANA = 91;</code>
     */
    REGION_USA_MONTANA(91),
    /**
     * <pre>
     * Wyoming in USA
     * </pre>
     *
     * <code>REGION_USA_WYOMING = 92;</code>
     */
    REGION_USA_WYOMING(92),
    /**
     * <pre>
     * California in USA
     * </pre>
     *
     * <code>REGION_USA_CALIFORNIA = 93;</code>
     */
    REGION_USA_CALIFORNIA(93),
    /**
     * <pre>
     * Colorado in USA
     * </pre>
     *
     * <code>REGION_USA_COLORADO = 94;</code>
     */
    REGION_USA_COLORADO(94),
    /**
     * <pre>
     * Hawaii in USA
     * </pre>
     *
     * <code>REGION_USA_HAWAII = 95;</code>
     */
    REGION_USA_HAWAII(95),
    /**
     * <pre>
     * Mississippi in USA
     * </pre>
     *
     * <code>REGION_USA_MISSISSIPPI = 96;</code>
     */
    REGION_USA_MISSISSIPPI(96),
    /**
     * <pre>
     * New Hampshire in USA
     * </pre>
     *
     * <code>REGION_USA_NEW_HAMPSHIRE = 97;</code>
     */
    REGION_USA_NEW_HAMPSHIRE(97),
    /**
     * <pre>
     * New York in USA
     * </pre>
     *
     * <code>REGION_USA_NEW_YORK = 98;</code>
     */
    REGION_USA_NEW_YORK(98),
    /**
     * <pre>
     * South Carolina in USA
     * </pre>
     *
     * <code>REGION_USA_SOUTH_CAROLINA = 99;</code>
     */
    REGION_USA_SOUTH_CAROLINA(99),
    /**
     * <pre>
     * Missouri in USA
     * </pre>
     *
     * <code>REGION_USA_MISSOURI = 100;</code>
     */
    REGION_USA_MISSOURI(100),
    /**
     * <pre>
     * Alaska in USA
     * </pre>
     *
     * <code>REGION_USA_ALASKA = 101;</code>
     */
    REGION_USA_ALASKA(101),
    /**
     * <pre>
     * Arkansas in USA
     * </pre>
     *
     * <code>REGION_USA_ARKANSAS = 102;</code>
     */
    REGION_USA_ARKANSAS(102),
    /**
     * <pre>
     * Kansas in USA
     * </pre>
     *
     * <code>REGION_USA_KANSAS = 103;</code>
     */
    REGION_USA_KANSAS(103),
    /**
     * <pre>
     * Kentucky in USA
     * </pre>
     *
     * <code>REGION_USA_KENTUCKY = 104;</code>
     */
    REGION_USA_KENTUCKY(104),
    /**
     * <pre>
     * Louisiana in USA
     * </pre>
     *
     * <code>REGION_USA_LOUISIANA = 105;</code>
     */
    REGION_USA_LOUISIANA(105),
    /**
     * <pre>
     * Maine in USA
     * </pre>
     *
     * <code>REGION_USA_MAINE = 106;</code>
     */
    REGION_USA_MAINE(106),
    /**
     * <pre>
     * Massachusetts in USA
     * </pre>
     *
     * <code>REGION_USA_MASSACHUSETTS = 107;</code>
     */
    REGION_USA_MASSACHUSETTS(107),
    /**
     * <pre>
     * Tennessee in USA
     * </pre>
     *
     * <code>REGION_USA_TENNESSEE = 108;</code>
     */
    REGION_USA_TENNESSEE(108),
    /**
     * <pre>
     * Wisconsin in USA
     * </pre>
     *
     * <code>REGION_USA_WISCONSIN = 109;</code>
     */
    REGION_USA_WISCONSIN(109),
    /**
     * <pre>
     * North Dakota in USA
     * </pre>
     *
     * <code>REGION_USA_NORTH_DAKOTA = 110;</code>
     */
    REGION_USA_NORTH_DAKOTA(110),
    /**
     * <pre>
     * Delaware in USA
     * </pre>
     *
     * <code>REGION_USA_DELAWARE = 111;</code>
     */
    REGION_USA_DELAWARE(111),
    /**
     * <pre>
     * Florida in USA
     * </pre>
     *
     * <code>REGION_USA_FLORIDA = 112;</code>
     */
    REGION_USA_FLORIDA(112),
    /**
     * <pre>
     * Georgia in USA
     * </pre>
     *
     * <code>REGION_USA_GEORGIA = 113;</code>
     */
    REGION_USA_GEORGIA(113),
    /**
     * <pre>
     * Idaho in USA
     * </pre>
     *
     * <code>REGION_USA_IDAHO = 114;</code>
     */
    REGION_USA_IDAHO(114),
    /**
     * <pre>
     * Illinois in USA
     * </pre>
     *
     * <code>REGION_USA_ILLINOIS = 115;</code>
     */
    REGION_USA_ILLINOIS(115),
    /**
     * <pre>
     * Michigan in USA
     * </pre>
     *
     * <code>REGION_USA_MICHIGAN = 116;</code>
     */
    REGION_USA_MICHIGAN(116),
    /**
     * <pre>
     * New Jersey in USA
     * </pre>
     *
     * <code>REGION_USA_NEW_JERSEY = 117;</code>
     */
    REGION_USA_NEW_JERSEY(117),
    /**
     * <pre>
     * Ohio in USA
     * </pre>
     *
     * <code>REGION_USA_OHIO = 118;</code>
     */
    REGION_USA_OHIO(118),
    /**
     * <pre>
     * Virginia in USA
     * </pre>
     *
     * <code>REGION_USA_VIRGINIA = 119;</code>
     */
    REGION_USA_VIRGINIA(119),
    /**
     * <pre>
     * Washington in USA
     * </pre>
     *
     * <code>REGION_USA_WASHINGTON = 120;</code>
     */
    REGION_USA_WASHINGTON(120),
    /**
     * <pre>
     * West Virginia in USA
     * </pre>
     *
     * <code>REGION_USA_WEST_VIRGINIA = 121;</code>
     */
    REGION_USA_WEST_VIRGINIA(121),
    /**
     * <pre>
     * Pennsylvania in USA
     * </pre>
     *
     * <code>REGION_USA_PENNSYLVANIA = 122;</code>
     */
    REGION_USA_PENNSYLVANIA(122),
    /**
     * <pre>
     * Alabama in USA
     * </pre>
     *
     * <code>REGION_USA_ALABAMA = 123;</code>
     */
    REGION_USA_ALABAMA(123),
    /**
     * <pre>
     * District Of Columbia in USA
     * </pre>
     *
     * <code>REGION_USA_DISTRICT_OF_COLUMBIA = 124;</code>
     */
    REGION_USA_DISTRICT_OF_COLUMBIA(124),
    /**
     * <pre>
     * Indiana in USA
     * </pre>
     *
     * <code>REGION_USA_INDIANA = 125;</code>
     */
    REGION_USA_INDIANA(125),
    /**
     * <pre>
     * Maryland in USA
     * </pre>
     *
     * <code>REGION_USA_MARYLAND = 126;</code>
     */
    REGION_USA_MARYLAND(126),
    /**
     * <pre>
     * Nebraska in USA
     * </pre>
     *
     * <code>REGION_USA_NEBRASKA = 127;</code>
     */
    REGION_USA_NEBRASKA(127),
    /**
     * <pre>
     * New Mexico in USA
     * </pre>
     *
     * <code>REGION_USA_NEW_MEXICO = 128;</code>
     */
    REGION_USA_NEW_MEXICO(128),
    /**
     * <pre>
     * North Carolina in USA
     * </pre>
     *
     * <code>REGION_USA_NORTH_CAROLINA = 129;</code>
     */
    REGION_USA_NORTH_CAROLINA(129),
    /**
     * <pre>
     * Rhode Island in USA
     * </pre>
     *
     * <code>REGION_USA_RHODE_ISLAND = 130;</code>
     */
    REGION_USA_RHODE_ISLAND(130),
    /**
     * <pre>
     * Connecticut in USA
     * </pre>
     *
     * <code>REGION_USA_CONNECTICUT = 131;</code>
     */
    REGION_USA_CONNECTICUT(131),
    /**
     * <pre>
     * New York City in USA
     * </pre>
     *
     * <code>REGION_USA_NEW_YORK_CITY = 132;</code>
     */
    REGION_USA_NEW_YORK_CITY(132),
    /**
     * <pre>
     * Oregon in USA
     * </pre>
     *
     * <code>REGION_USA_OREGON = 133;</code>
     */
    REGION_USA_OREGON(133),
    /**
     * <pre>
     * Vermont in USA
     * </pre>
     *
     * <code>REGION_USA_VERMONT = 134;</code>
     */
    REGION_USA_VERMONT(134),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 2,
        /* suffix= */ "",
        Region.class.getName());
    }
    /**
     * <pre>
     * Undefined
     * </pre>
     *
     * <code>REGION_UNDEFINED = 0;</code>
     */
    public static final int REGION_UNDEFINED_VALUE = 0;
    /**
     * <pre>
     * New South Wales in Australia
     * </pre>
     *
     * <code>REGION_AUSTRALIA_NEW_SOUTH_WALES = 1;</code>
     */
    public static final int REGION_AUSTRALIA_NEW_SOUTH_WALES_VALUE = 1;
    /**
     * <pre>
     * Northern Territory in Australia
     * </pre>
     *
     * <code>REGION_AUSTRALIA_NORTHERN_TERRITORY = 2;</code>
     */
    public static final int REGION_AUSTRALIA_NORTHERN_TERRITORY_VALUE = 2;
    /**
     * <pre>
     * Queensland in Australia
     * </pre>
     *
     * <code>REGION_AUSTRALIA_QUEENSLAND = 3;</code>
     */
    public static final int REGION_AUSTRALIA_QUEENSLAND_VALUE = 3;
    /**
     * <pre>
     * South Australia in Australia
     * </pre>
     *
     * <code>REGION_AUSTRALIA_SOUTH_AUSTRALIA = 4;</code>
     */
    public static final int REGION_AUSTRALIA_SOUTH_AUSTRALIA_VALUE = 4;
    /**
     * <pre>
     * Tasmania in Australia
     * </pre>
     *
     * <code>REGION_AUSTRALIA_TASMANIA = 5;</code>
     */
    public static final int REGION_AUSTRALIA_TASMANIA_VALUE = 5;
    /**
     * <pre>
     * Victoria in Australia
     * </pre>
     *
     * <code>REGION_AUSTRALIA_VICTORIA = 6;</code>
     */
    public static final int REGION_AUSTRALIA_VICTORIA_VALUE = 6;
    /**
     * <pre>
     * Western Australia in Australia
     * </pre>
     *
     * <code>REGION_AUSTRALIA_WESTERN_AUSTRALIA = 7;</code>
     */
    public static final int REGION_AUSTRALIA_WESTERN_AUSTRALIA_VALUE = 7;
    /**
     * <pre>
     * Australian Capital Territory in Australia
     * </pre>
     *
     * <code>REGION_AUSTRALIA_AUSTRALIAN_CAPITAL_TERRITORY = 8;</code>
     */
    public static final int REGION_AUSTRALIA_AUSTRALIAN_CAPITAL_TERRITORY_VALUE = 8;
    /**
     * <pre>
     * Sao Paolo in Brazil
     * </pre>
     *
     * <code>REGION_BRAZIL_SAO_PAOLO = 9;</code>
     */
    public static final int REGION_BRAZIL_SAO_PAOLO_VALUE = 9;
    /**
     * <pre>
     * Distrito Federal in Brazil
     * </pre>
     *
     * <code>REGION_BRAZIL_DISTRITO_FEDERAL = 10;</code>
     */
    public static final int REGION_BRAZIL_DISTRITO_FEDERAL_VALUE = 10;
    /**
     * <pre>
     * Maranhao in Brazil
     * </pre>
     *
     * <code>REGION_BRAZIL_MARANHAO = 11;</code>
     */
    public static final int REGION_BRAZIL_MARANHAO_VALUE = 11;
    /**
     * <pre>
     * Santa Catarina in Brazil
     * </pre>
     *
     * <code>REGION_BRAZIL_SANTA_CATARINA = 12;</code>
     */
    public static final int REGION_BRAZIL_SANTA_CATARINA_VALUE = 12;
    /**
     * <pre>
     * Ceara in Brazil
     * </pre>
     *
     * <code>REGION_BRAZIL_CEARA = 13;</code>
     */
    public static final int REGION_BRAZIL_CEARA_VALUE = 13;
    /**
     * <pre>
     * Goias in Brazil
     * </pre>
     *
     * <code>REGION_BRAZIL_GOIAS = 14;</code>
     */
    public static final int REGION_BRAZIL_GOIAS_VALUE = 14;
    /**
     * <pre>
     * Rio Grande Do Sul in Brazil
     * </pre>
     *
     * <code>REGION_BRAZIL_RIO_GRANDE_DO_SUL = 15;</code>
     */
    public static final int REGION_BRAZIL_RIO_GRANDE_DO_SUL_VALUE = 15;
    /**
     * <pre>
     * Pernambuco in Brazil
     * </pre>
     *
     * <code>REGION_BRAZIL_PERNAMBUCO = 16;</code>
     */
    public static final int REGION_BRAZIL_PERNAMBUCO_VALUE = 16;
    /**
     * <pre>
     * Rio De Janeiro in Brazil
     * </pre>
     *
     * <code>REGION_BRAZIL_RIO_DE_JANEIRO = 17;</code>
     */
    public static final int REGION_BRAZIL_RIO_DE_JANEIRO_VALUE = 17;
    /**
     * <pre>
     * Parana in Brazil
     * </pre>
     *
     * <code>REGION_BRAZIL_PARANA = 18;</code>
     */
    public static final int REGION_BRAZIL_PARANA_VALUE = 18;
    /**
     * <pre>
     * Sergipe in Brazil
     * </pre>
     *
     * <code>REGION_BRAZIL_SERGIPE = 19;</code>
     */
    public static final int REGION_BRAZIL_SERGIPE_VALUE = 19;
    /**
     * <pre>
     * Mato Grosso in Brazil
     * </pre>
     *
     * <code>REGION_BRAZIL_MATO_GROSSO = 20;</code>
     */
    public static final int REGION_BRAZIL_MATO_GROSSO_VALUE = 20;
    /**
     * <pre>
     * Minas Gerais in Brazil
     * </pre>
     *
     * <code>REGION_BRAZIL_MINAS_GERAIS = 21;</code>
     */
    public static final int REGION_BRAZIL_MINAS_GERAIS_VALUE = 21;
    /**
     * <pre>
     * Para in Brazil
     * </pre>
     *
     * <code>REGION_BRAZIL_PARA = 22;</code>
     */
    public static final int REGION_BRAZIL_PARA_VALUE = 22;
    /**
     * <pre>
     * Prince Edward Island in Canada
     * </pre>
     *
     * <code>REGION_CANADA_PRINCE_EDWARD_ISLAND = 23;</code>
     */
    public static final int REGION_CANADA_PRINCE_EDWARD_ISLAND_VALUE = 23;
    /**
     * <pre>
     * Quebec in Canada
     * </pre>
     *
     * <code>REGION_CANADA_QUEBEC = 24;</code>
     */
    public static final int REGION_CANADA_QUEBEC_VALUE = 24;
    /**
     * <pre>
     * Manitoba in Canada
     * </pre>
     *
     * <code>REGION_CANADA_MANITOBA = 25;</code>
     */
    public static final int REGION_CANADA_MANITOBA_VALUE = 25;
    /**
     * <pre>
     * New Brunswick in Canada
     * </pre>
     *
     * <code>REGION_CANADA_NEW_BRUNSWICK = 26;</code>
     */
    public static final int REGION_CANADA_NEW_BRUNSWICK_VALUE = 26;
    /**
     * <pre>
     * Newfoundland And Labrador in Canada
     * </pre>
     *
     * <code>REGION_CANADA_NEWFOUNDLAND_AND_LABRADOR = 27;</code>
     */
    public static final int REGION_CANADA_NEWFOUNDLAND_AND_LABRADOR_VALUE = 27;
    /**
     * <pre>
     * Northwest Territories in Canada
     * </pre>
     *
     * <code>REGION_CANADA_NORTHWEST_TERRITORIES = 28;</code>
     */
    public static final int REGION_CANADA_NORTHWEST_TERRITORIES_VALUE = 28;
    /**
     * <pre>
     * Nunavut in Canada
     * </pre>
     *
     * <code>REGION_CANADA_NUNAVUT = 29;</code>
     */
    public static final int REGION_CANADA_NUNAVUT_VALUE = 29;
    /**
     * <pre>
     * Yukon in Canada
     * </pre>
     *
     * <code>REGION_CANADA_YUKON = 30;</code>
     */
    public static final int REGION_CANADA_YUKON_VALUE = 30;
    /**
     * <pre>
     * Alberta in Canada
     * </pre>
     *
     * <code>REGION_CANADA_ALBERTA = 31;</code>
     */
    public static final int REGION_CANADA_ALBERTA_VALUE = 31;
    /**
     * <pre>
     * British Columbia in Canada
     * </pre>
     *
     * <code>REGION_CANADA_BRITISH_COLUMBIA = 32;</code>
     */
    public static final int REGION_CANADA_BRITISH_COLUMBIA_VALUE = 32;
    /**
     * <pre>
     * Nova Scotia in Canada
     * </pre>
     *
     * <code>REGION_CANADA_NOVA_SCOTIA = 33;</code>
     */
    public static final int REGION_CANADA_NOVA_SCOTIA_VALUE = 33;
    /**
     * <pre>
     * Ontario in Canada
     * </pre>
     *
     * <code>REGION_CANADA_ONTARIO = 34;</code>
     */
    public static final int REGION_CANADA_ONTARIO_VALUE = 34;
    /**
     * <pre>
     * Saskatchewan in Canada
     * </pre>
     *
     * <code>REGION_CANADA_SASKATCHEWAN = 35;</code>
     */
    public static final int REGION_CANADA_SASKATCHEWAN_VALUE = 35;
    /**
     * <pre>
     * Andhra Pradesh in India
     * </pre>
     *
     * <code>REGION_INDIA_ANDHRA_PRADESH = 36;</code>
     */
    public static final int REGION_INDIA_ANDHRA_PRADESH_VALUE = 36;
    /**
     * <pre>
     * Tamil Nadu in India
     * </pre>
     *
     * <code>REGION_INDIA_TAMIL_NADU = 37;</code>
     */
    public static final int REGION_INDIA_TAMIL_NADU_VALUE = 37;
    /**
     * <pre>
     * Gujarat in India
     * </pre>
     *
     * <code>REGION_INDIA_GUJARAT = 38;</code>
     */
    public static final int REGION_INDIA_GUJARAT_VALUE = 38;
    /**
     * <pre>
     * Haryana in India
     * </pre>
     *
     * <code>REGION_INDIA_HARYANA = 39;</code>
     */
    public static final int REGION_INDIA_HARYANA_VALUE = 39;
    /**
     * <pre>
     * Karnataka in India
     * </pre>
     *
     * <code>REGION_INDIA_KARNATAKA = 40;</code>
     */
    public static final int REGION_INDIA_KARNATAKA_VALUE = 40;
    /**
     * <pre>
     * Kerala in India
     * </pre>
     *
     * <code>REGION_INDIA_KERALA = 41;</code>
     */
    public static final int REGION_INDIA_KERALA_VALUE = 41;
    /**
     * <pre>
     * Madhya Pradesh in India
     * </pre>
     *
     * <code>REGION_INDIA_MADHYA_PRADESH = 42;</code>
     */
    public static final int REGION_INDIA_MADHYA_PRADESH_VALUE = 42;
    /**
     * <pre>
     * Maharashtra in India
     * </pre>
     *
     * <code>REGION_INDIA_MAHARASHTRA = 43;</code>
     */
    public static final int REGION_INDIA_MAHARASHTRA_VALUE = 43;
    /**
     * <pre>
     * Punjab in India
     * </pre>
     *
     * <code>REGION_INDIA_PUNJAB = 44;</code>
     */
    public static final int REGION_INDIA_PUNJAB_VALUE = 44;
    /**
     * <pre>
     * Chiapas in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_CHIAPAS = 45;</code>
     */
    public static final int REGION_MEXICO_CHIAPAS_VALUE = 45;
    /**
     * <pre>
     * Chihuahua in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_CHIHUAHUA = 46;</code>
     */
    public static final int REGION_MEXICO_CHIHUAHUA_VALUE = 46;
    /**
     * <pre>
     * Durango in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_DURANGO = 47;</code>
     */
    public static final int REGION_MEXICO_DURANGO_VALUE = 47;
    /**
     * <pre>
     * Guerrero-Juchitan in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_GUERRERO_JUCHITAN = 48;</code>
     */
    public static final int REGION_MEXICO_GUERRERO_JUCHITAN_VALUE = 48;
    /**
     * <pre>
     * Baja California Sur in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_BAJA_CALIFORNIA_SUR = 49;</code>
     */
    public static final int REGION_MEXICO_BAJA_CALIFORNIA_SUR_VALUE = 49;
    /**
     * <pre>
     * Ciudad De Mexico in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_CIUDAD_DE_MEXICO = 50;</code>
     */
    public static final int REGION_MEXICO_CIUDAD_DE_MEXICO_VALUE = 50;
    /**
     * <pre>
     * Jalisco in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_JALISCO = 51;</code>
     */
    public static final int REGION_MEXICO_JALISCO_VALUE = 51;
    /**
     * <pre>
     * Mexico in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_MEXICO = 52;</code>
     */
    public static final int REGION_MEXICO_MEXICO_VALUE = 52;
    /**
     * <pre>
     * Nuevo Leon in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_NUEVO_LEON = 53;</code>
     */
    public static final int REGION_MEXICO_NUEVO_LEON_VALUE = 53;
    /**
     * <pre>
     * Veracruz in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_VERACRUZ = 54;</code>
     */
    public static final int REGION_MEXICO_VERACRUZ_VALUE = 54;
    /**
     * <pre>
     * Aguascalientes in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_AGUASCALIENTES = 55;</code>
     */
    public static final int REGION_MEXICO_AGUASCALIENTES_VALUE = 55;
    /**
     * <pre>
     * Queretaro in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_QUERETARO = 56;</code>
     */
    public static final int REGION_MEXICO_QUERETARO_VALUE = 56;
    /**
     * <pre>
     * Quintana Roo-Cozumel in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_QUINTANA_ROO_COZUMEL = 57;</code>
     */
    public static final int REGION_MEXICO_QUINTANA_ROO_COZUMEL_VALUE = 57;
    /**
     * <pre>
     * San Luis Potosi in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_SAN_LUIS_POTOSI = 58;</code>
     */
    public static final int REGION_MEXICO_SAN_LUIS_POTOSI_VALUE = 58;
    /**
     * <pre>
     * Morelos in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_MORELOS = 59;</code>
     */
    public static final int REGION_MEXICO_MORELOS_VALUE = 59;
    /**
     * <pre>
     * Oaxaca in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_OAXACA = 60;</code>
     */
    public static final int REGION_MEXICO_OAXACA_VALUE = 60;
    /**
     * <pre>
     * Puebla in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_PUEBLA = 61;</code>
     */
    public static final int REGION_MEXICO_PUEBLA_VALUE = 61;
    /**
     * <pre>
     * Sinaloa in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_SINALOA = 62;</code>
     */
    public static final int REGION_MEXICO_SINALOA_VALUE = 62;
    /**
     * <pre>
     * Sonora in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_SONORA = 63;</code>
     */
    public static final int REGION_MEXICO_SONORA_VALUE = 63;
    /**
     * <pre>
     * Coahuila in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_COAHUILA = 64;</code>
     */
    public static final int REGION_MEXICO_COAHUILA_VALUE = 64;
    /**
     * <pre>
     * Hidalgo in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_HIDALGO = 65;</code>
     */
    public static final int REGION_MEXICO_HIDALGO_VALUE = 65;
    /**
     * <pre>
     * Zacatecas in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_ZACATECAS = 66;</code>
     */
    public static final int REGION_MEXICO_ZACATECAS_VALUE = 66;
    /**
     * <pre>
     * Campeche in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_CAMPECHE = 67;</code>
     */
    public static final int REGION_MEXICO_CAMPECHE_VALUE = 67;
    /**
     * <pre>
     * Quintana Roo-Benito Juarez in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_QUINTANA_ROO_BENITO_JUAREZ = 68;</code>
     */
    public static final int REGION_MEXICO_QUINTANA_ROO_BENITO_JUAREZ_VALUE = 68;
    /**
     * <pre>
     * Quintana Roo in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_QUINTANA_ROO = 69;</code>
     */
    public static final int REGION_MEXICO_QUINTANA_ROO_VALUE = 69;
    /**
     * <pre>
     * Tabasco in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_TABASCO = 70;</code>
     */
    public static final int REGION_MEXICO_TABASCO_VALUE = 70;
    /**
     * <pre>
     * Tamaulipas in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_TAMAULIPAS = 71;</code>
     */
    public static final int REGION_MEXICO_TAMAULIPAS_VALUE = 71;
    /**
     * <pre>
     * Guerrero-Acapulco De Juarez in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_GUERRERO_ACAPULCO_DE_JUAREZ = 72;</code>
     */
    public static final int REGION_MEXICO_GUERRERO_ACAPULCO_DE_JUAREZ_VALUE = 72;
    /**
     * <pre>
     * Tlaxcala in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_TLAXCALA = 73;</code>
     */
    public static final int REGION_MEXICO_TLAXCALA_VALUE = 73;
    /**
     * <pre>
     * Nayarit in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_NAYARIT = 74;</code>
     */
    public static final int REGION_MEXICO_NAYARIT_VALUE = 74;
    /**
     * <pre>
     * Colima in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_COLIMA = 75;</code>
     */
    public static final int REGION_MEXICO_COLIMA_VALUE = 75;
    /**
     * <pre>
     * Guanajuato in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_GUANAJUATO = 76;</code>
     */
    public static final int REGION_MEXICO_GUANAJUATO_VALUE = 76;
    /**
     * <pre>
     * Michoacan in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_MICHOACAN = 77;</code>
     */
    public static final int REGION_MEXICO_MICHOACAN_VALUE = 77;
    /**
     * <pre>
     * Quintana Roo-Solidaridad in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_QUINTANA_ROO_SOLIDARIDAD = 78;</code>
     */
    public static final int REGION_MEXICO_QUINTANA_ROO_SOLIDARIDAD_VALUE = 78;
    /**
     * <pre>
     * Yucatan in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_YUCATAN = 79;</code>
     */
    public static final int REGION_MEXICO_YUCATAN_VALUE = 79;
    /**
     * <pre>
     * Baja California in Mexico
     * </pre>
     *
     * <code>REGION_MEXICO_BAJA_CALIFORNIA = 80;</code>
     */
    public static final int REGION_MEXICO_BAJA_CALIFORNIA_VALUE = 80;
    /**
     * <pre>
     * Khyber Pakhtunkhwa in Pakistan
     * </pre>
     *
     * <code>REGION_PAKISTAN_KHYBER_PAKHTUNKHWA = 81;</code>
     */
    public static final int REGION_PAKISTAN_KHYBER_PAKHTUNKHWA_VALUE = 81;
    /**
     * <pre>
     * Punjab in Pakistan
     * </pre>
     *
     * <code>REGION_PAKISTAN_PUNJAB = 82;</code>
     */
    public static final int REGION_PAKISTAN_PUNJAB_VALUE = 82;
    /**
     * <pre>
     * Arizona in USA
     * </pre>
     *
     * <code>REGION_USA_ARIZONA = 83;</code>
     */
    public static final int REGION_USA_ARIZONA_VALUE = 83;
    /**
     * <pre>
     * Minnesota in USA
     * </pre>
     *
     * <code>REGION_USA_MINNESOTA = 84;</code>
     */
    public static final int REGION_USA_MINNESOTA_VALUE = 84;
    /**
     * <pre>
     * Oklahoma in USA
     * </pre>
     *
     * <code>REGION_USA_OKLAHOMA = 85;</code>
     */
    public static final int REGION_USA_OKLAHOMA_VALUE = 85;
    /**
     * <pre>
     * South Dakota in USA
     * </pre>
     *
     * <code>REGION_USA_SOUTH_DAKOTA = 86;</code>
     */
    public static final int REGION_USA_SOUTH_DAKOTA_VALUE = 86;
    /**
     * <pre>
     * Utah in USA
     * </pre>
     *
     * <code>REGION_USA_UTAH = 87;</code>
     */
    public static final int REGION_USA_UTAH_VALUE = 87;
    /**
     * <pre>
     * Nevada in USA
     * </pre>
     *
     * <code>REGION_USA_NEVADA = 88;</code>
     */
    public static final int REGION_USA_NEVADA_VALUE = 88;
    /**
     * <pre>
     * Texas in USA
     * </pre>
     *
     * <code>REGION_USA_TEXAS = 89;</code>
     */
    public static final int REGION_USA_TEXAS_VALUE = 89;
    /**
     * <pre>
     * Iowa in USA
     * </pre>
     *
     * <code>REGION_USA_IOWA = 90;</code>
     */
    public static final int REGION_USA_IOWA_VALUE = 90;
    /**
     * <pre>
     * Montana in USA
     * </pre>
     *
     * <code>REGION_USA_MONTANA = 91;</code>
     */
    public static final int REGION_USA_MONTANA_VALUE = 91;
    /**
     * <pre>
     * Wyoming in USA
     * </pre>
     *
     * <code>REGION_USA_WYOMING = 92;</code>
     */
    public static final int REGION_USA_WYOMING_VALUE = 92;
    /**
     * <pre>
     * California in USA
     * </pre>
     *
     * <code>REGION_USA_CALIFORNIA = 93;</code>
     */
    public static final int REGION_USA_CALIFORNIA_VALUE = 93;
    /**
     * <pre>
     * Colorado in USA
     * </pre>
     *
     * <code>REGION_USA_COLORADO = 94;</code>
     */
    public static final int REGION_USA_COLORADO_VALUE = 94;
    /**
     * <pre>
     * Hawaii in USA
     * </pre>
     *
     * <code>REGION_USA_HAWAII = 95;</code>
     */
    public static final int REGION_USA_HAWAII_VALUE = 95;
    /**
     * <pre>
     * Mississippi in USA
     * </pre>
     *
     * <code>REGION_USA_MISSISSIPPI = 96;</code>
     */
    public static final int REGION_USA_MISSISSIPPI_VALUE = 96;
    /**
     * <pre>
     * New Hampshire in USA
     * </pre>
     *
     * <code>REGION_USA_NEW_HAMPSHIRE = 97;</code>
     */
    public static final int REGION_USA_NEW_HAMPSHIRE_VALUE = 97;
    /**
     * <pre>
     * New York in USA
     * </pre>
     *
     * <code>REGION_USA_NEW_YORK = 98;</code>
     */
    public static final int REGION_USA_NEW_YORK_VALUE = 98;
    /**
     * <pre>
     * South Carolina in USA
     * </pre>
     *
     * <code>REGION_USA_SOUTH_CAROLINA = 99;</code>
     */
    public static final int REGION_USA_SOUTH_CAROLINA_VALUE = 99;
    /**
     * <pre>
     * Missouri in USA
     * </pre>
     *
     * <code>REGION_USA_MISSOURI = 100;</code>
     */
    public static final int REGION_USA_MISSOURI_VALUE = 100;
    /**
     * <pre>
     * Alaska in USA
     * </pre>
     *
     * <code>REGION_USA_ALASKA = 101;</code>
     */
    public static final int REGION_USA_ALASKA_VALUE = 101;
    /**
     * <pre>
     * Arkansas in USA
     * </pre>
     *
     * <code>REGION_USA_ARKANSAS = 102;</code>
     */
    public static final int REGION_USA_ARKANSAS_VALUE = 102;
    /**
     * <pre>
     * Kansas in USA
     * </pre>
     *
     * <code>REGION_USA_KANSAS = 103;</code>
     */
    public static final int REGION_USA_KANSAS_VALUE = 103;
    /**
     * <pre>
     * Kentucky in USA
     * </pre>
     *
     * <code>REGION_USA_KENTUCKY = 104;</code>
     */
    public static final int REGION_USA_KENTUCKY_VALUE = 104;
    /**
     * <pre>
     * Louisiana in USA
     * </pre>
     *
     * <code>REGION_USA_LOUISIANA = 105;</code>
     */
    public static final int REGION_USA_LOUISIANA_VALUE = 105;
    /**
     * <pre>
     * Maine in USA
     * </pre>
     *
     * <code>REGION_USA_MAINE = 106;</code>
     */
    public static final int REGION_USA_MAINE_VALUE = 106;
    /**
     * <pre>
     * Massachusetts in USA
     * </pre>
     *
     * <code>REGION_USA_MASSACHUSETTS = 107;</code>
     */
    public static final int REGION_USA_MASSACHUSETTS_VALUE = 107;
    /**
     * <pre>
     * Tennessee in USA
     * </pre>
     *
     * <code>REGION_USA_TENNESSEE = 108;</code>
     */
    public static final int REGION_USA_TENNESSEE_VALUE = 108;
    /**
     * <pre>
     * Wisconsin in USA
     * </pre>
     *
     * <code>REGION_USA_WISCONSIN = 109;</code>
     */
    public static final int REGION_USA_WISCONSIN_VALUE = 109;
    /**
     * <pre>
     * North Dakota in USA
     * </pre>
     *
     * <code>REGION_USA_NORTH_DAKOTA = 110;</code>
     */
    public static final int REGION_USA_NORTH_DAKOTA_VALUE = 110;
    /**
     * <pre>
     * Delaware in USA
     * </pre>
     *
     * <code>REGION_USA_DELAWARE = 111;</code>
     */
    public static final int REGION_USA_DELAWARE_VALUE = 111;
    /**
     * <pre>
     * Florida in USA
     * </pre>
     *
     * <code>REGION_USA_FLORIDA = 112;</code>
     */
    public static final int REGION_USA_FLORIDA_VALUE = 112;
    /**
     * <pre>
     * Georgia in USA
     * </pre>
     *
     * <code>REGION_USA_GEORGIA = 113;</code>
     */
    public static final int REGION_USA_GEORGIA_VALUE = 113;
    /**
     * <pre>
     * Idaho in USA
     * </pre>
     *
     * <code>REGION_USA_IDAHO = 114;</code>
     */
    public static final int REGION_USA_IDAHO_VALUE = 114;
    /**
     * <pre>
     * Illinois in USA
     * </pre>
     *
     * <code>REGION_USA_ILLINOIS = 115;</code>
     */
    public static final int REGION_USA_ILLINOIS_VALUE = 115;
    /**
     * <pre>
     * Michigan in USA
     * </pre>
     *
     * <code>REGION_USA_MICHIGAN = 116;</code>
     */
    public static final int REGION_USA_MICHIGAN_VALUE = 116;
    /**
     * <pre>
     * New Jersey in USA
     * </pre>
     *
     * <code>REGION_USA_NEW_JERSEY = 117;</code>
     */
    public static final int REGION_USA_NEW_JERSEY_VALUE = 117;
    /**
     * <pre>
     * Ohio in USA
     * </pre>
     *
     * <code>REGION_USA_OHIO = 118;</code>
     */
    public static final int REGION_USA_OHIO_VALUE = 118;
    /**
     * <pre>
     * Virginia in USA
     * </pre>
     *
     * <code>REGION_USA_VIRGINIA = 119;</code>
     */
    public static final int REGION_USA_VIRGINIA_VALUE = 119;
    /**
     * <pre>
     * Washington in USA
     * </pre>
     *
     * <code>REGION_USA_WASHINGTON = 120;</code>
     */
    public static final int REGION_USA_WASHINGTON_VALUE = 120;
    /**
     * <pre>
     * West Virginia in USA
     * </pre>
     *
     * <code>REGION_USA_WEST_VIRGINIA = 121;</code>
     */
    public static final int REGION_USA_WEST_VIRGINIA_VALUE = 121;
    /**
     * <pre>
     * Pennsylvania in USA
     * </pre>
     *
     * <code>REGION_USA_PENNSYLVANIA = 122;</code>
     */
    public static final int REGION_USA_PENNSYLVANIA_VALUE = 122;
    /**
     * <pre>
     * Alabama in USA
     * </pre>
     *
     * <code>REGION_USA_ALABAMA = 123;</code>
     */
    public static final int REGION_USA_ALABAMA_VALUE = 123;
    /**
     * <pre>
     * District Of Columbia in USA
     * </pre>
     *
     * <code>REGION_USA_DISTRICT_OF_COLUMBIA = 124;</code>
     */
    public static final int REGION_USA_DISTRICT_OF_COLUMBIA_VALUE = 124;
    /**
     * <pre>
     * Indiana in USA
     * </pre>
     *
     * <code>REGION_USA_INDIANA = 125;</code>
     */
    public static final int REGION_USA_INDIANA_VALUE = 125;
    /**
     * <pre>
     * Maryland in USA
     * </pre>
     *
     * <code>REGION_USA_MARYLAND = 126;</code>
     */
    public static final int REGION_USA_MARYLAND_VALUE = 126;
    /**
     * <pre>
     * Nebraska in USA
     * </pre>
     *
     * <code>REGION_USA_NEBRASKA = 127;</code>
     */
    public static final int REGION_USA_NEBRASKA_VALUE = 127;
    /**
     * <pre>
     * New Mexico in USA
     * </pre>
     *
     * <code>REGION_USA_NEW_MEXICO = 128;</code>
     */
    public static final int REGION_USA_NEW_MEXICO_VALUE = 128;
    /**
     * <pre>
     * North Carolina in USA
     * </pre>
     *
     * <code>REGION_USA_NORTH_CAROLINA = 129;</code>
     */
    public static final int REGION_USA_NORTH_CAROLINA_VALUE = 129;
    /**
     * <pre>
     * Rhode Island in USA
     * </pre>
     *
     * <code>REGION_USA_RHODE_ISLAND = 130;</code>
     */
    public static final int REGION_USA_RHODE_ISLAND_VALUE = 130;
    /**
     * <pre>
     * Connecticut in USA
     * </pre>
     *
     * <code>REGION_USA_CONNECTICUT = 131;</code>
     */
    public static final int REGION_USA_CONNECTICUT_VALUE = 131;
    /**
     * <pre>
     * New York City in USA
     * </pre>
     *
     * <code>REGION_USA_NEW_YORK_CITY = 132;</code>
     */
    public static final int REGION_USA_NEW_YORK_CITY_VALUE = 132;
    /**
     * <pre>
     * Oregon in USA
     * </pre>
     *
     * <code>REGION_USA_OREGON = 133;</code>
     */
    public static final int REGION_USA_OREGON_VALUE = 133;
    /**
     * <pre>
     * Vermont in USA
     * </pre>
     *
     * <code>REGION_USA_VERMONT = 134;</code>
     */
    public static final int REGION_USA_VERMONT_VALUE = 134;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Region valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Region forNumber(int value) {
      switch (value) {
        case 0: return REGION_UNDEFINED;
        case 1: return REGION_AUSTRALIA_NEW_SOUTH_WALES;
        case 2: return REGION_AUSTRALIA_NORTHERN_TERRITORY;
        case 3: return REGION_AUSTRALIA_QUEENSLAND;
        case 4: return REGION_AUSTRALIA_SOUTH_AUSTRALIA;
        case 5: return REGION_AUSTRALIA_TASMANIA;
        case 6: return REGION_AUSTRALIA_VICTORIA;
        case 7: return REGION_AUSTRALIA_WESTERN_AUSTRALIA;
        case 8: return REGION_AUSTRALIA_AUSTRALIAN_CAPITAL_TERRITORY;
        case 9: return REGION_BRAZIL_SAO_PAOLO;
        case 10: return REGION_BRAZIL_DISTRITO_FEDERAL;
        case 11: return REGION_BRAZIL_MARANHAO;
        case 12: return REGION_BRAZIL_SANTA_CATARINA;
        case 13: return REGION_BRAZIL_CEARA;
        case 14: return REGION_BRAZIL_GOIAS;
        case 15: return REGION_BRAZIL_RIO_GRANDE_DO_SUL;
        case 16: return REGION_BRAZIL_PERNAMBUCO;
        case 17: return REGION_BRAZIL_RIO_DE_JANEIRO;
        case 18: return REGION_BRAZIL_PARANA;
        case 19: return REGION_BRAZIL_SERGIPE;
        case 20: return REGION_BRAZIL_MATO_GROSSO;
        case 21: return REGION_BRAZIL_MINAS_GERAIS;
        case 22: return REGION_BRAZIL_PARA;
        case 23: return REGION_CANADA_PRINCE_EDWARD_ISLAND;
        case 24: return REGION_CANADA_QUEBEC;
        case 25: return REGION_CANADA_MANITOBA;
        case 26: return REGION_CANADA_NEW_BRUNSWICK;
        case 27: return REGION_CANADA_NEWFOUNDLAND_AND_LABRADOR;
        case 28: return REGION_CANADA_NORTHWEST_TERRITORIES;
        case 29: return REGION_CANADA_NUNAVUT;
        case 30: return REGION_CANADA_YUKON;
        case 31: return REGION_CANADA_ALBERTA;
        case 32: return REGION_CANADA_BRITISH_COLUMBIA;
        case 33: return REGION_CANADA_NOVA_SCOTIA;
        case 34: return REGION_CANADA_ONTARIO;
        case 35: return REGION_CANADA_SASKATCHEWAN;
        case 36: return REGION_INDIA_ANDHRA_PRADESH;
        case 37: return REGION_INDIA_TAMIL_NADU;
        case 38: return REGION_INDIA_GUJARAT;
        case 39: return REGION_INDIA_HARYANA;
        case 40: return REGION_INDIA_KARNATAKA;
        case 41: return REGION_INDIA_KERALA;
        case 42: return REGION_INDIA_MADHYA_PRADESH;
        case 43: return REGION_INDIA_MAHARASHTRA;
        case 44: return REGION_INDIA_PUNJAB;
        case 45: return REGION_MEXICO_CHIAPAS;
        case 46: return REGION_MEXICO_CHIHUAHUA;
        case 47: return REGION_MEXICO_DURANGO;
        case 48: return REGION_MEXICO_GUERRERO_JUCHITAN;
        case 49: return REGION_MEXICO_BAJA_CALIFORNIA_SUR;
        case 50: return REGION_MEXICO_CIUDAD_DE_MEXICO;
        case 51: return REGION_MEXICO_JALISCO;
        case 52: return REGION_MEXICO_MEXICO;
        case 53: return REGION_MEXICO_NUEVO_LEON;
        case 54: return REGION_MEXICO_VERACRUZ;
        case 55: return REGION_MEXICO_AGUASCALIENTES;
        case 56: return REGION_MEXICO_QUERETARO;
        case 57: return REGION_MEXICO_QUINTANA_ROO_COZUMEL;
        case 58: return REGION_MEXICO_SAN_LUIS_POTOSI;
        case 59: return REGION_MEXICO_MORELOS;
        case 60: return REGION_MEXICO_OAXACA;
        case 61: return REGION_MEXICO_PUEBLA;
        case 62: return REGION_MEXICO_SINALOA;
        case 63: return REGION_MEXICO_SONORA;
        case 64: return REGION_MEXICO_COAHUILA;
        case 65: return REGION_MEXICO_HIDALGO;
        case 66: return REGION_MEXICO_ZACATECAS;
        case 67: return REGION_MEXICO_CAMPECHE;
        case 68: return REGION_MEXICO_QUINTANA_ROO_BENITO_JUAREZ;
        case 69: return REGION_MEXICO_QUINTANA_ROO;
        case 70: return REGION_MEXICO_TABASCO;
        case 71: return REGION_MEXICO_TAMAULIPAS;
        case 72: return REGION_MEXICO_GUERRERO_ACAPULCO_DE_JUAREZ;
        case 73: return REGION_MEXICO_TLAXCALA;
        case 74: return REGION_MEXICO_NAYARIT;
        case 75: return REGION_MEXICO_COLIMA;
        case 76: return REGION_MEXICO_GUANAJUATO;
        case 77: return REGION_MEXICO_MICHOACAN;
        case 78: return REGION_MEXICO_QUINTANA_ROO_SOLIDARIDAD;
        case 79: return REGION_MEXICO_YUCATAN;
        case 80: return REGION_MEXICO_BAJA_CALIFORNIA;
        case 81: return REGION_PAKISTAN_KHYBER_PAKHTUNKHWA;
        case 82: return REGION_PAKISTAN_PUNJAB;
        case 83: return REGION_USA_ARIZONA;
        case 84: return REGION_USA_MINNESOTA;
        case 85: return REGION_USA_OKLAHOMA;
        case 86: return REGION_USA_SOUTH_DAKOTA;
        case 87: return REGION_USA_UTAH;
        case 88: return REGION_USA_NEVADA;
        case 89: return REGION_USA_TEXAS;
        case 90: return REGION_USA_IOWA;
        case 91: return REGION_USA_MONTANA;
        case 92: return REGION_USA_WYOMING;
        case 93: return REGION_USA_CALIFORNIA;
        case 94: return REGION_USA_COLORADO;
        case 95: return REGION_USA_HAWAII;
        case 96: return REGION_USA_MISSISSIPPI;
        case 97: return REGION_USA_NEW_HAMPSHIRE;
        case 98: return REGION_USA_NEW_YORK;
        case 99: return REGION_USA_SOUTH_CAROLINA;
        case 100: return REGION_USA_MISSOURI;
        case 101: return REGION_USA_ALASKA;
        case 102: return REGION_USA_ARKANSAS;
        case 103: return REGION_USA_KANSAS;
        case 104: return REGION_USA_KENTUCKY;
        case 105: return REGION_USA_LOUISIANA;
        case 106: return REGION_USA_MAINE;
        case 107: return REGION_USA_MASSACHUSETTS;
        case 108: return REGION_USA_TENNESSEE;
        case 109: return REGION_USA_WISCONSIN;
        case 110: return REGION_USA_NORTH_DAKOTA;
        case 111: return REGION_USA_DELAWARE;
        case 112: return REGION_USA_FLORIDA;
        case 113: return REGION_USA_GEORGIA;
        case 114: return REGION_USA_IDAHO;
        case 115: return REGION_USA_ILLINOIS;
        case 116: return REGION_USA_MICHIGAN;
        case 117: return REGION_USA_NEW_JERSEY;
        case 118: return REGION_USA_OHIO;
        case 119: return REGION_USA_VIRGINIA;
        case 120: return REGION_USA_WASHINGTON;
        case 121: return REGION_USA_WEST_VIRGINIA;
        case 122: return REGION_USA_PENNSYLVANIA;
        case 123: return REGION_USA_ALABAMA;
        case 124: return REGION_USA_DISTRICT_OF_COLUMBIA;
        case 125: return REGION_USA_INDIANA;
        case 126: return REGION_USA_MARYLAND;
        case 127: return REGION_USA_NEBRASKA;
        case 128: return REGION_USA_NEW_MEXICO;
        case 129: return REGION_USA_NORTH_CAROLINA;
        case 130: return REGION_USA_RHODE_ISLAND;
        case 131: return REGION_USA_CONNECTICUT;
        case 132: return REGION_USA_NEW_YORK_CITY;
        case 133: return REGION_USA_OREGON;
        case 134: return REGION_USA_VERMONT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Region>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Region> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Region>() {
            public Region findValueByNumber(int number) {
              return Region.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return proto.id_extract_service.v1.RegionsEnum.getDescriptor().getEnumTypes().get(0);
    }

    private static final Region[] VALUES = values();

    public static Region valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Region(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:proto.id_extract_service.v1.Region)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n.proto/id_extract_service/v1/regions_en" +
      "um.proto\022\033proto.id_extract_service.v1*\362\036" +
      "\n\006Region\022\024\n\020REGION_UNDEFINED\020\000\022$\n REGION" +
      "_AUSTRALIA_NEW_SOUTH_WALES\020\001\022\'\n#REGION_A" +
      "USTRALIA_NORTHERN_TERRITORY\020\002\022\037\n\033REGION_" +
      "AUSTRALIA_QUEENSLAND\020\003\022$\n REGION_AUSTRAL" +
      "IA_SOUTH_AUSTRALIA\020\004\022\035\n\031REGION_AUSTRALIA" +
      "_TASMANIA\020\005\022\035\n\031REGION_AUSTRALIA_VICTORIA" +
      "\020\006\022&\n\"REGION_AUSTRALIA_WESTERN_AUSTRALIA" +
      "\020\007\0221\n-REGION_AUSTRALIA_AUSTRALIAN_CAPITA" +
      "L_TERRITORY\020\010\022\033\n\027REGION_BRAZIL_SAO_PAOLO" +
      "\020\t\022\"\n\036REGION_BRAZIL_DISTRITO_FEDERAL\020\n\022\032" +
      "\n\026REGION_BRAZIL_MARANHAO\020\013\022 \n\034REGION_BRA" +
      "ZIL_SANTA_CATARINA\020\014\022\027\n\023REGION_BRAZIL_CE" +
      "ARA\020\r\022\027\n\023REGION_BRAZIL_GOIAS\020\016\022#\n\037REGION" +
      "_BRAZIL_RIO_GRANDE_DO_SUL\020\017\022\034\n\030REGION_BR" +
      "AZIL_PERNAMBUCO\020\020\022 \n\034REGION_BRAZIL_RIO_D" +
      "E_JANEIRO\020\021\022\030\n\024REGION_BRAZIL_PARANA\020\022\022\031\n" +
      "\025REGION_BRAZIL_SERGIPE\020\023\022\035\n\031REGION_BRAZI" +
      "L_MATO_GROSSO\020\024\022\036\n\032REGION_BRAZIL_MINAS_G" +
      "ERAIS\020\025\022\026\n\022REGION_BRAZIL_PARA\020\026\022&\n\"REGIO" +
      "N_CANADA_PRINCE_EDWARD_ISLAND\020\027\022\030\n\024REGIO" +
      "N_CANADA_QUEBEC\020\030\022\032\n\026REGION_CANADA_MANIT" +
      "OBA\020\031\022\037\n\033REGION_CANADA_NEW_BRUNSWICK\020\032\022+" +
      "\n\'REGION_CANADA_NEWFOUNDLAND_AND_LABRADO" +
      "R\020\033\022\'\n#REGION_CANADA_NORTHWEST_TERRITORI" +
      "ES\020\034\022\031\n\025REGION_CANADA_NUNAVUT\020\035\022\027\n\023REGIO" +
      "N_CANADA_YUKON\020\036\022\031\n\025REGION_CANADA_ALBERT" +
      "A\020\037\022\"\n\036REGION_CANADA_BRITISH_COLUMBIA\020 \022" +
      "\035\n\031REGION_CANADA_NOVA_SCOTIA\020!\022\031\n\025REGION" +
      "_CANADA_ONTARIO\020\"\022\036\n\032REGION_CANADA_SASKA" +
      "TCHEWAN\020#\022\037\n\033REGION_INDIA_ANDHRA_PRADESH" +
      "\020$\022\033\n\027REGION_INDIA_TAMIL_NADU\020%\022\030\n\024REGIO" +
      "N_INDIA_GUJARAT\020&\022\030\n\024REGION_INDIA_HARYAN" +
      "A\020\'\022\032\n\026REGION_INDIA_KARNATAKA\020(\022\027\n\023REGIO" +
      "N_INDIA_KERALA\020)\022\037\n\033REGION_INDIA_MADHYA_" +
      "PRADESH\020*\022\034\n\030REGION_INDIA_MAHARASHTRA\020+\022" +
      "\027\n\023REGION_INDIA_PUNJAB\020,\022\031\n\025REGION_MEXIC" +
      "O_CHIAPAS\020-\022\033\n\027REGION_MEXICO_CHIHUAHUA\020." +
      "\022\031\n\025REGION_MEXICO_DURANGO\020/\022#\n\037REGION_ME" +
      "XICO_GUERRERO_JUCHITAN\0200\022%\n!REGION_MEXIC" +
      "O_BAJA_CALIFORNIA_SUR\0201\022\"\n\036REGION_MEXICO" +
      "_CIUDAD_DE_MEXICO\0202\022\031\n\025REGION_MEXICO_JAL" +
      "ISCO\0203\022\030\n\024REGION_MEXICO_MEXICO\0204\022\034\n\030REGI" +
      "ON_MEXICO_NUEVO_LEON\0205\022\032\n\026REGION_MEXICO_" +
      "VERACRUZ\0206\022 \n\034REGION_MEXICO_AGUASCALIENT" +
      "ES\0207\022\033\n\027REGION_MEXICO_QUERETARO\0208\022&\n\"REG" +
      "ION_MEXICO_QUINTANA_ROO_COZUMEL\0209\022!\n\035REG" +
      "ION_MEXICO_SAN_LUIS_POTOSI\020:\022\031\n\025REGION_M" +
      "EXICO_MORELOS\020;\022\030\n\024REGION_MEXICO_OAXACA\020" +
      "<\022\030\n\024REGION_MEXICO_PUEBLA\020=\022\031\n\025REGION_ME" +
      "XICO_SINALOA\020>\022\030\n\024REGION_MEXICO_SONORA\020?" +
      "\022\032\n\026REGION_MEXICO_COAHUILA\020@\022\031\n\025REGION_M" +
      "EXICO_HIDALGO\020A\022\033\n\027REGION_MEXICO_ZACATEC" +
      "AS\020B\022\032\n\026REGION_MEXICO_CAMPECHE\020C\022,\n(REGI" +
      "ON_MEXICO_QUINTANA_ROO_BENITO_JUAREZ\020D\022\036" +
      "\n\032REGION_MEXICO_QUINTANA_ROO\020E\022\031\n\025REGION" +
      "_MEXICO_TABASCO\020F\022\034\n\030REGION_MEXICO_TAMAU" +
      "LIPAS\020G\022-\n)REGION_MEXICO_GUERRERO_ACAPUL" +
      "CO_DE_JUAREZ\020H\022\032\n\026REGION_MEXICO_TLAXCALA" +
      "\020I\022\031\n\025REGION_MEXICO_NAYARIT\020J\022\030\n\024REGION_" +
      "MEXICO_COLIMA\020K\022\034\n\030REGION_MEXICO_GUANAJU" +
      "ATO\020L\022\033\n\027REGION_MEXICO_MICHOACAN\020M\022*\n&RE" +
      "GION_MEXICO_QUINTANA_ROO_SOLIDARIDAD\020N\022\031" +
      "\n\025REGION_MEXICO_YUCATAN\020O\022!\n\035REGION_MEXI" +
      "CO_BAJA_CALIFORNIA\020P\022&\n\"REGION_PAKISTAN_" +
      "KHYBER_PAKHTUNKHWA\020Q\022\032\n\026REGION_PAKISTAN_" +
      "PUNJAB\020R\022\026\n\022REGION_USA_ARIZONA\020S\022\030\n\024REGI" +
      "ON_USA_MINNESOTA\020T\022\027\n\023REGION_USA_OKLAHOM" +
      "A\020U\022\033\n\027REGION_USA_SOUTH_DAKOTA\020V\022\023\n\017REGI" +
      "ON_USA_UTAH\020W\022\025\n\021REGION_USA_NEVADA\020X\022\024\n\020" +
      "REGION_USA_TEXAS\020Y\022\023\n\017REGION_USA_IOWA\020Z\022" +
      "\026\n\022REGION_USA_MONTANA\020[\022\026\n\022REGION_USA_WY" +
      "OMING\020\\\022\031\n\025REGION_USA_CALIFORNIA\020]\022\027\n\023RE" +
      "GION_USA_COLORADO\020^\022\025\n\021REGION_USA_HAWAII" +
      "\020_\022\032\n\026REGION_USA_MISSISSIPPI\020`\022\034\n\030REGION" +
      "_USA_NEW_HAMPSHIRE\020a\022\027\n\023REGION_USA_NEW_Y" +
      "ORK\020b\022\035\n\031REGION_USA_SOUTH_CAROLINA\020c\022\027\n\023" +
      "REGION_USA_MISSOURI\020d\022\025\n\021REGION_USA_ALAS" +
      "KA\020e\022\027\n\023REGION_USA_ARKANSAS\020f\022\025\n\021REGION_" +
      "USA_KANSAS\020g\022\027\n\023REGION_USA_KENTUCKY\020h\022\030\n" +
      "\024REGION_USA_LOUISIANA\020i\022\024\n\020REGION_USA_MA" +
      "INE\020j\022\034\n\030REGION_USA_MASSACHUSETTS\020k\022\030\n\024R" +
      "EGION_USA_TENNESSEE\020l\022\030\n\024REGION_USA_WISC" +
      "ONSIN\020m\022\033\n\027REGION_USA_NORTH_DAKOTA\020n\022\027\n\023" +
      "REGION_USA_DELAWARE\020o\022\026\n\022REGION_USA_FLOR" +
      "IDA\020p\022\026\n\022REGION_USA_GEORGIA\020q\022\024\n\020REGION_" +
      "USA_IDAHO\020r\022\027\n\023REGION_USA_ILLINOIS\020s\022\027\n\023" +
      "REGION_USA_MICHIGAN\020t\022\031\n\025REGION_USA_NEW_" +
      "JERSEY\020u\022\023\n\017REGION_USA_OHIO\020v\022\027\n\023REGION_" +
      "USA_VIRGINIA\020w\022\031\n\025REGION_USA_WASHINGTON\020" +
      "x\022\034\n\030REGION_USA_WEST_VIRGINIA\020y\022\033\n\027REGIO" +
      "N_USA_PENNSYLVANIA\020z\022\026\n\022REGION_USA_ALABA" +
      "MA\020{\022#\n\037REGION_USA_DISTRICT_OF_COLUMBIA\020" +
      "|\022\026\n\022REGION_USA_INDIANA\020}\022\027\n\023REGION_USA_" +
      "MARYLAND\020~\022\027\n\023REGION_USA_NEBRASKA\020\177\022\032\n\025R" +
      "EGION_USA_NEW_MEXICO\020\200\001\022\036\n\031REGION_USA_NO" +
      "RTH_CAROLINA\020\201\001\022\034\n\027REGION_USA_RHODE_ISLA" +
      "ND\020\202\001\022\033\n\026REGION_USA_CONNECTICUT\020\203\001\022\035\n\030RE" +
      "GION_USA_NEW_YORK_CITY\020\204\001\022\026\n\021REGION_USA_" +
      "OREGON\020\205\001\022\027\n\022REGION_USA_VERMONT\020\206\001BCZAgi" +
      "thub.com/veridil/id-extract-service/prot" +
      "o/id_extract_service/v1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
