# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/ddx/v1/mrz.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'proto/ddx/v1/mrz.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16proto/ddx/v1/mrz.proto\x12\x0cproto.ddx.v1\"\xcf\x03\n\tMrzFields\x12#\n\rdocument_type\x18\x01 \x01(\tR\x0c\x64ocumentType\x12!\n\x0c\x63ountry_code\x18\x02 \x01(\tR\x0b\x63ountryCode\x12\'\n\x0f\x64ocument_number\x18\x03 \x01(\tR\x0e\x64ocumentNumber\x12\x1c\n\tbirthdate\x18\x04 \x01(\tR\tbirthdate\x12\x10\n\x03sex\x18\x05 \x01(\tR\x03sex\x12\x1f\n\x0b\x65xpiry_date\x18\x06 \x01(\tR\nexpiryDate\x12 \n\x0bnationality\x18\x07 \x01(\tR\x0bnationality\x12*\n\x11\x66inal_check_digit\x18\x08 \x01(\tR\x0f\x66inalCheckDigit\x12\x12\n\x04name\x18\t \x01(\tR\x04name\x12\x18\n\x07surname\x18\n \x01(\tR\x07surname\x12\x1d\n\ngiven_name\x18\x0b \x01(\tR\tgivenName\x12%\n\x0eoptional_data1\x18\x0c \x01(\tR\roptionalData1\x12%\n\x0eoptional_data2\x18\r \x01(\tR\roptionalData2\x12\x17\n\x07is_visa\x18\x0e \x01(\x08R\x06isVisaB4Z2github.com/veridil/id-extract-service/proto/ddx/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.ddx.v1.mrz_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z2github.com/veridil/id-extract-service/proto/ddx/v1'
  _globals['_MRZFIELDS']._serialized_start=41
  _globals['_MRZFIELDS']._serialized_end=504
# @@protoc_insertion_point(module_scope)
