// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/ddx/v1/countries_enum.proto
// Protobuf Java Version: 4.28.2

package proto.ddx.v1;

public final class CountriesEnum {
  private CountriesEnum() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      CountriesEnum.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * Country - enumeration of supported countries.
   * </pre>
   *
   * Protobuf enum {@code proto.ddx.v1.Country}
   */
  public enum Country
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * Not available
     * </pre>
     *
     * <code>COUNTRY_NOT_AVAILABLE = 0;</code>
     */
    COUNTRY_NOT_AVAILABLE(0),
    /**
     * <pre>
     * AFGHANISTAN
     * </pre>
     *
     * <code>COUNTRY_AFGHANISTAN = 1;</code>
     */
    COUNTRY_AFGHANISTAN(1),
    /**
     * <pre>
     * ALBANIA
     * </pre>
     *
     * <code>COUNTRY_ALBANIA = 2;</code>
     */
    COUNTRY_ALBANIA(2),
    /**
     * <pre>
     * ALGERIA
     * </pre>
     *
     * <code>COUNTRY_ALGERIA = 3;</code>
     */
    COUNTRY_ALGERIA(3),
    /**
     * <pre>
     * ANTIGUA AND BARBUDA
     * </pre>
     *
     * <code>COUNTRY_ANTIGUA_AND_BARBUDA = 4;</code>
     */
    COUNTRY_ANTIGUA_AND_BARBUDA(4),
    /**
     * <pre>
     * ARGENTINA
     * </pre>
     *
     * <code>COUNTRY_ARGENTINA = 5;</code>
     */
    COUNTRY_ARGENTINA(5),
    /**
     * <pre>
     * ARMENIA
     * </pre>
     *
     * <code>COUNTRY_ARMENIA = 6;</code>
     */
    COUNTRY_ARMENIA(6),
    /**
     * <pre>
     * AUSTRALIA
     * </pre>
     *
     * <code>COUNTRY_AUSTRALIA = 7;</code>
     */
    COUNTRY_AUSTRALIA(7),
    /**
     * <pre>
     * AUSTRIA
     * </pre>
     *
     * <code>COUNTRY_AUSTRIA = 8;</code>
     */
    COUNTRY_AUSTRIA(8),
    /**
     * <pre>
     * AZERBAIJAN
     * </pre>
     *
     * <code>COUNTRY_AZERBAIJAN = 9;</code>
     */
    COUNTRY_AZERBAIJAN(9),
    /**
     * <pre>
     * BAHAMAS
     * </pre>
     *
     * <code>COUNTRY_BAHAMAS = 10;</code>
     */
    COUNTRY_BAHAMAS(10),
    /**
     * <pre>
     * BAHRAIN
     * </pre>
     *
     * <code>COUNTRY_BAHRAIN = 11;</code>
     */
    COUNTRY_BAHRAIN(11),
    /**
     * <pre>
     * BANGLADESH
     * </pre>
     *
     * <code>COUNTRY_BANGLADESH = 12;</code>
     */
    COUNTRY_BANGLADESH(12),
    /**
     * <pre>
     * BARBADOS
     * </pre>
     *
     * <code>COUNTRY_BARBADOS = 13;</code>
     */
    COUNTRY_BARBADOS(13),
    /**
     * <pre>
     * BELARUS
     * </pre>
     *
     * <code>COUNTRY_BELARUS = 14;</code>
     */
    COUNTRY_BELARUS(14),
    /**
     * <pre>
     * BELGIUM
     * </pre>
     *
     * <code>COUNTRY_BELGIUM = 15;</code>
     */
    COUNTRY_BELGIUM(15),
    /**
     * <pre>
     * BERMUDA
     * </pre>
     *
     * <code>COUNTRY_BERMUDA = 16;</code>
     */
    COUNTRY_BERMUDA(16),
    /**
     * <pre>
     * BOLIVIA
     * </pre>
     *
     * <code>COUNTRY_BOLIVIA = 17;</code>
     */
    COUNTRY_BOLIVIA(17),
    /**
     * <pre>
     * BOSNIA AND HERZEGOVINA
     * </pre>
     *
     * <code>COUNTRY_BOSNIA_AND_HERZEGOVINA = 18;</code>
     */
    COUNTRY_BOSNIA_AND_HERZEGOVINA(18),
    /**
     * <pre>
     * BRAZIL
     * </pre>
     *
     * <code>COUNTRY_BRAZIL = 19;</code>
     */
    COUNTRY_BRAZIL(19),
    /**
     * <pre>
     * BRUNEI
     * </pre>
     *
     * <code>COUNTRY_BRUNEI = 20;</code>
     */
    COUNTRY_BRUNEI(20),
    /**
     * <pre>
     * BULGARIA
     * </pre>
     *
     * <code>COUNTRY_BULGARIA = 21;</code>
     */
    COUNTRY_BULGARIA(21),
    /**
     * <pre>
     * CAMBODIA
     * </pre>
     *
     * <code>COUNTRY_CAMBODIA = 22;</code>
     */
    COUNTRY_CAMBODIA(22),
    /**
     * <pre>
     * CAMEROON
     * </pre>
     *
     * <code>COUNTRY_CAMEROON = 23;</code>
     */
    COUNTRY_CAMEROON(23),
    /**
     * <pre>
     * CANADA
     * </pre>
     *
     * <code>COUNTRY_CANADA = 24;</code>
     */
    COUNTRY_CANADA(24),
    /**
     * <pre>
     * CAYMAN ISLANDS
     * </pre>
     *
     * <code>COUNTRY_CAYMAN_ISLANDS = 25;</code>
     */
    COUNTRY_CAYMAN_ISLANDS(25),
    /**
     * <pre>
     * CHILE
     * </pre>
     *
     * <code>COUNTRY_CHILE = 26;</code>
     */
    COUNTRY_CHILE(26),
    /**
     * <pre>
     * CHINA
     * </pre>
     *
     * <code>COUNTRY_CHINA = 27;</code>
     */
    COUNTRY_CHINA(27),
    /**
     * <pre>
     * COLOMBIA
     * </pre>
     *
     * <code>COUNTRY_COLOMBIA = 28;</code>
     */
    COUNTRY_COLOMBIA(28),
    /**
     * <pre>
     * COSTA RICA
     * </pre>
     *
     * <code>COUNTRY_COSTA_RICA = 29;</code>
     */
    COUNTRY_COSTA_RICA(29),
    /**
     * <pre>
     * CROATIA
     * </pre>
     *
     * <code>COUNTRY_CROATIA = 30;</code>
     */
    COUNTRY_CROATIA(30),
    /**
     * <pre>
     * CUBA
     * </pre>
     *
     * <code>COUNTRY_CUBA = 31;</code>
     */
    COUNTRY_CUBA(31),
    /**
     * <pre>
     * CYPRUS
     * </pre>
     *
     * <code>COUNTRY_CYPRUS = 32;</code>
     */
    COUNTRY_CYPRUS(32),
    /**
     * <pre>
     * CZECHIA
     * </pre>
     *
     * <code>COUNTRY_CZECHIA = 33;</code>
     */
    COUNTRY_CZECHIA(33),
    /**
     * <pre>
     * DEMOCRATIC REPUBLIC OF THE CONGO
     * </pre>
     *
     * <code>COUNTRY_DEMOCRATIC_REPUBLIC_OF_THE_CONGO = 34;</code>
     */
    COUNTRY_DEMOCRATIC_REPUBLIC_OF_THE_CONGO(34),
    /**
     * <pre>
     * DENMARK
     * </pre>
     *
     * <code>COUNTRY_DENMARK = 35;</code>
     */
    COUNTRY_DENMARK(35),
    /**
     * <pre>
     * DOMINICAN REPUBLIC
     * </pre>
     *
     * <code>COUNTRY_DOMINICAN_REPUBLIC = 36;</code>
     */
    COUNTRY_DOMINICAN_REPUBLIC(36),
    /**
     * <pre>
     * ECUADOR
     * </pre>
     *
     * <code>COUNTRY_ECUADOR = 37;</code>
     */
    COUNTRY_ECUADOR(37),
    /**
     * <pre>
     * EGYPT
     * </pre>
     *
     * <code>COUNTRY_EGYPT = 38;</code>
     */
    COUNTRY_EGYPT(38),
    /**
     * <pre>
     * EL SALVADOR
     * </pre>
     *
     * <code>COUNTRY_EL_SALVADOR = 39;</code>
     */
    COUNTRY_EL_SALVADOR(39),
    /**
     * <pre>
     * ESTONIA
     * </pre>
     *
     * <code>COUNTRY_ESTONIA = 40;</code>
     */
    COUNTRY_ESTONIA(40),
    /**
     * <pre>
     * EUROPEAN UNION
     * </pre>
     *
     * <code>COUNTRY_EUROPEAN_UNION = 41;</code>
     */
    COUNTRY_EUROPEAN_UNION(41),
    /**
     * <pre>
     * FINLAND
     * </pre>
     *
     * <code>COUNTRY_FINLAND = 42;</code>
     */
    COUNTRY_FINLAND(42),
    /**
     * <pre>
     * FRANCE
     * </pre>
     *
     * <code>COUNTRY_FRANCE = 43;</code>
     */
    COUNTRY_FRANCE(43),
    /**
     * <pre>
     * GEORGIA
     * </pre>
     *
     * <code>COUNTRY_GEORGIA = 44;</code>
     */
    COUNTRY_GEORGIA(44),
    /**
     * <pre>
     * GERMANY
     * </pre>
     *
     * <code>COUNTRY_GERMANY = 45;</code>
     */
    COUNTRY_GERMANY(45),
    /**
     * <pre>
     * GHANA
     * </pre>
     *
     * <code>COUNTRY_GHANA = 46;</code>
     */
    COUNTRY_GHANA(46),
    /**
     * <pre>
     * GREECE
     * </pre>
     *
     * <code>COUNTRY_GREECE = 47;</code>
     */
    COUNTRY_GREECE(47),
    /**
     * <pre>
     * GUATEMALA
     * </pre>
     *
     * <code>COUNTRY_GUATEMALA = 48;</code>
     */
    COUNTRY_GUATEMALA(48),
    /**
     * <pre>
     * HAITI
     * </pre>
     *
     * <code>COUNTRY_HAITI = 49;</code>
     */
    COUNTRY_HAITI(49),
    /**
     * <pre>
     * HONDURAS
     * </pre>
     *
     * <code>COUNTRY_HONDURAS = 50;</code>
     */
    COUNTRY_HONDURAS(50),
    /**
     * <pre>
     * HONG KONG
     * </pre>
     *
     * <code>COUNTRY_HONG_KONG = 51;</code>
     */
    COUNTRY_HONG_KONG(51),
    /**
     * <pre>
     * HUNGARY
     * </pre>
     *
     * <code>COUNTRY_HUNGARY = 52;</code>
     */
    COUNTRY_HUNGARY(52),
    /**
     * <pre>
     * ICELAND
     * </pre>
     *
     * <code>COUNTRY_ICELAND = 53;</code>
     */
    COUNTRY_ICELAND(53),
    /**
     * <pre>
     * INDIA
     * </pre>
     *
     * <code>COUNTRY_INDIA = 54;</code>
     */
    COUNTRY_INDIA(54),
    /**
     * <pre>
     * INDONESIA
     * </pre>
     *
     * <code>COUNTRY_INDONESIA = 55;</code>
     */
    COUNTRY_INDONESIA(55),
    /**
     * <pre>
     * IRAN
     * </pre>
     *
     * <code>COUNTRY_IRAN = 56;</code>
     */
    COUNTRY_IRAN(56),
    /**
     * <pre>
     * IRAQ
     * </pre>
     *
     * <code>COUNTRY_IRAQ = 57;</code>
     */
    COUNTRY_IRAQ(57),
    /**
     * <pre>
     * IRELAND
     * </pre>
     *
     * <code>COUNTRY_IRELAND = 58;</code>
     */
    COUNTRY_IRELAND(58),
    /**
     * <pre>
     * ISRAEL
     * </pre>
     *
     * <code>COUNTRY_ISRAEL = 59;</code>
     */
    COUNTRY_ISRAEL(59),
    /**
     * <pre>
     * ITALY
     * </pre>
     *
     * <code>COUNTRY_ITALY = 60;</code>
     */
    COUNTRY_ITALY(60),
    /**
     * <pre>
     * IVORY COAST
     * </pre>
     *
     * <code>COUNTRY_IVORY_COAST = 61;</code>
     */
    COUNTRY_IVORY_COAST(61),
    /**
     * <pre>
     * JAMAICA
     * </pre>
     *
     * <code>COUNTRY_JAMAICA = 62;</code>
     */
    COUNTRY_JAMAICA(62),
    /**
     * <pre>
     * JAPAN
     * </pre>
     *
     * <code>COUNTRY_JAPAN = 63;</code>
     */
    COUNTRY_JAPAN(63),
    /**
     * <pre>
     * JORDAN
     * </pre>
     *
     * <code>COUNTRY_JORDAN = 64;</code>
     */
    COUNTRY_JORDAN(64),
    /**
     * <pre>
     * KAZAKHSTAN
     * </pre>
     *
     * <code>COUNTRY_KAZAKHSTAN = 65;</code>
     */
    COUNTRY_KAZAKHSTAN(65),
    /**
     * <pre>
     * KENYA
     * </pre>
     *
     * <code>COUNTRY_KENYA = 66;</code>
     */
    COUNTRY_KENYA(66),
    /**
     * <pre>
     * KOSOVO
     * </pre>
     *
     * <code>COUNTRY_KOSOVO = 67;</code>
     */
    COUNTRY_KOSOVO(67),
    /**
     * <pre>
     * KUWAIT
     * </pre>
     *
     * <code>COUNTRY_KUWAIT = 68;</code>
     */
    COUNTRY_KUWAIT(68),
    /**
     * <pre>
     * LATVIA
     * </pre>
     *
     * <code>COUNTRY_LATVIA = 69;</code>
     */
    COUNTRY_LATVIA(69),
    /**
     * <pre>
     * LIBYA
     * </pre>
     *
     * <code>COUNTRY_LIBYA = 70;</code>
     */
    COUNTRY_LIBYA(70),
    /**
     * <pre>
     * LIECHTENSTEIN
     * </pre>
     *
     * <code>COUNTRY_LIECHTENSTEIN = 71;</code>
     */
    COUNTRY_LIECHTENSTEIN(71),
    /**
     * <pre>
     * LITHUANIA
     * </pre>
     *
     * <code>COUNTRY_LITHUANIA = 72;</code>
     */
    COUNTRY_LITHUANIA(72),
    /**
     * <pre>
     * LUXEMBOURG
     * </pre>
     *
     * <code>COUNTRY_LUXEMBOURG = 73;</code>
     */
    COUNTRY_LUXEMBOURG(73),
    /**
     * <pre>
     * MALAYSIA
     * </pre>
     *
     * <code>COUNTRY_MALAYSIA = 74;</code>
     */
    COUNTRY_MALAYSIA(74),
    /**
     * <pre>
     * MALDIVES
     * </pre>
     *
     * <code>COUNTRY_MALDIVES = 75;</code>
     */
    COUNTRY_MALDIVES(75),
    /**
     * <pre>
     * MALTA
     * </pre>
     *
     * <code>COUNTRY_MALTA = 76;</code>
     */
    COUNTRY_MALTA(76),
    /**
     * <pre>
     * MAURITIUS
     * </pre>
     *
     * <code>COUNTRY_MAURITIUS = 77;</code>
     */
    COUNTRY_MAURITIUS(77),
    /**
     * <pre>
     * MEXICO
     * </pre>
     *
     * <code>COUNTRY_MEXICO = 78;</code>
     */
    COUNTRY_MEXICO(78),
    /**
     * <pre>
     * MOLDOVA
     * </pre>
     *
     * <code>COUNTRY_MOLDOVA = 79;</code>
     */
    COUNTRY_MOLDOVA(79),
    /**
     * <pre>
     * MONACO
     * </pre>
     *
     * <code>COUNTRY_MONACO = 80;</code>
     */
    COUNTRY_MONACO(80),
    /**
     * <pre>
     * MONTENEGRO
     * </pre>
     *
     * <code>COUNTRY_MONTENEGRO = 81;</code>
     */
    COUNTRY_MONTENEGRO(81),
    /**
     * <pre>
     * MOROCCO
     * </pre>
     *
     * <code>COUNTRY_MOROCCO = 82;</code>
     */
    COUNTRY_MOROCCO(82),
    /**
     * <pre>
     * NAMIBIA
     * </pre>
     *
     * <code>COUNTRY_NAMIBIA = 83;</code>
     */
    COUNTRY_NAMIBIA(83),
    /**
     * <pre>
     * NEPAL
     * </pre>
     *
     * <code>COUNTRY_NEPAL = 84;</code>
     */
    COUNTRY_NEPAL(84),
    /**
     * <pre>
     * NETHERLANDS
     * </pre>
     *
     * <code>COUNTRY_NETHERLANDS = 85;</code>
     */
    COUNTRY_NETHERLANDS(85),
    /**
     * <pre>
     * NEW ZEALAND
     * </pre>
     *
     * <code>COUNTRY_NEW_ZEALAND = 86;</code>
     */
    COUNTRY_NEW_ZEALAND(86),
    /**
     * <pre>
     * NICARAGUA
     * </pre>
     *
     * <code>COUNTRY_NICARAGUA = 87;</code>
     */
    COUNTRY_NICARAGUA(87),
    /**
     * <pre>
     * NIGERIA
     * </pre>
     *
     * <code>COUNTRY_NIGERIA = 88;</code>
     */
    COUNTRY_NIGERIA(88),
    /**
     * <pre>
     * NORTH MACEDONIA
     * </pre>
     *
     * <code>COUNTRY_NORTH_MACEDONIA = 89;</code>
     */
    COUNTRY_NORTH_MACEDONIA(89),
    /**
     * <pre>
     * NORWAY
     * </pre>
     *
     * <code>COUNTRY_NORWAY = 90;</code>
     */
    COUNTRY_NORWAY(90),
    /**
     * <pre>
     * OMAN
     * </pre>
     *
     * <code>COUNTRY_OMAN = 91;</code>
     */
    COUNTRY_OMAN(91),
    /**
     * <pre>
     * PAKISTAN
     * </pre>
     *
     * <code>COUNTRY_PAKISTAN = 92;</code>
     */
    COUNTRY_PAKISTAN(92),
    /**
     * <pre>
     * PALESTINE
     * </pre>
     *
     * <code>COUNTRY_PALESTINE = 93;</code>
     */
    COUNTRY_PALESTINE(93),
    /**
     * <pre>
     * PANAMA
     * </pre>
     *
     * <code>COUNTRY_PANAMA = 94;</code>
     */
    COUNTRY_PANAMA(94),
    /**
     * <pre>
     * PARAGUAY
     * </pre>
     *
     * <code>COUNTRY_PARAGUAY = 95;</code>
     */
    COUNTRY_PARAGUAY(95),
    /**
     * <pre>
     * PERU
     * </pre>
     *
     * <code>COUNTRY_PERU = 96;</code>
     */
    COUNTRY_PERU(96),
    /**
     * <pre>
     * PHILIPPINES
     * </pre>
     *
     * <code>COUNTRY_PHILIPPINES = 97;</code>
     */
    COUNTRY_PHILIPPINES(97),
    /**
     * <pre>
     * POLAND
     * </pre>
     *
     * <code>COUNTRY_POLAND = 98;</code>
     */
    COUNTRY_POLAND(98),
    /**
     * <pre>
     * PORTUGAL
     * </pre>
     *
     * <code>COUNTRY_PORTUGAL = 99;</code>
     */
    COUNTRY_PORTUGAL(99),
    /**
     * <pre>
     * PUERTO RICO
     * </pre>
     *
     * <code>COUNTRY_PUERTO_RICO = 100;</code>
     */
    COUNTRY_PUERTO_RICO(100),
    /**
     * <pre>
     * QATAR
     * </pre>
     *
     * <code>COUNTRY_QATAR = 101;</code>
     */
    COUNTRY_QATAR(101),
    /**
     * <pre>
     * ROMANIA
     * </pre>
     *
     * <code>COUNTRY_ROMANIA = 102;</code>
     */
    COUNTRY_ROMANIA(102),
    /**
     * <pre>
     * RUSSIA
     * </pre>
     *
     * <code>COUNTRY_RUSSIA = 103;</code>
     */
    COUNTRY_RUSSIA(103),
    /**
     * <pre>
     * SAINT KITTS AND NEVIS
     * </pre>
     *
     * <code>COUNTRY_SAINT_KITTS_AND_NEVIS = 104;</code>
     */
    COUNTRY_SAINT_KITTS_AND_NEVIS(104),
    /**
     * <pre>
     * SAINT LUCIA
     * </pre>
     *
     * <code>COUNTRY_SAINT_LUCIA = 105;</code>
     */
    COUNTRY_SAINT_LUCIA(105),
    /**
     * <pre>
     * SAUDI ARABIA
     * </pre>
     *
     * <code>COUNTRY_SAUDI_ARABIA = 106;</code>
     */
    COUNTRY_SAUDI_ARABIA(106),
    /**
     * <pre>
     * SCHENGEN AREA
     * </pre>
     *
     * <code>COUNTRY_SCHENGEN_AREA = 107;</code>
     */
    COUNTRY_SCHENGEN_AREA(107),
    /**
     * <pre>
     * SERBIA
     * </pre>
     *
     * <code>COUNTRY_SERBIA = 108;</code>
     */
    COUNTRY_SERBIA(108),
    /**
     * <pre>
     * SINGAPORE
     * </pre>
     *
     * <code>COUNTRY_SINGAPORE = 109;</code>
     */
    COUNTRY_SINGAPORE(109),
    /**
     * <pre>
     * SLOVAKIA
     * </pre>
     *
     * <code>COUNTRY_SLOVAKIA = 110;</code>
     */
    COUNTRY_SLOVAKIA(110),
    /**
     * <pre>
     * SLOVENIA
     * </pre>
     *
     * <code>COUNTRY_SLOVENIA = 111;</code>
     */
    COUNTRY_SLOVENIA(111),
    /**
     * <pre>
     * SOUTH AFRICA
     * </pre>
     *
     * <code>COUNTRY_SOUTH_AFRICA = 112;</code>
     */
    COUNTRY_SOUTH_AFRICA(112),
    /**
     * <pre>
     * SOUTH KOREA
     * </pre>
     *
     * <code>COUNTRY_SOUTH_KOREA = 113;</code>
     */
    COUNTRY_SOUTH_KOREA(113),
    /**
     * <pre>
     * SPAIN
     * </pre>
     *
     * <code>COUNTRY_SPAIN = 114;</code>
     */
    COUNTRY_SPAIN(114),
    /**
     * <pre>
     * SRI LANKA
     * </pre>
     *
     * <code>COUNTRY_SRI_LANKA = 115;</code>
     */
    COUNTRY_SRI_LANKA(115),
    /**
     * <pre>
     * SUDAN
     * </pre>
     *
     * <code>COUNTRY_SUDAN = 116;</code>
     */
    COUNTRY_SUDAN(116),
    /**
     * <pre>
     * SWEDEN
     * </pre>
     *
     * <code>COUNTRY_SWEDEN = 117;</code>
     */
    COUNTRY_SWEDEN(117),
    /**
     * <pre>
     * SWITZERLAND
     * </pre>
     *
     * <code>COUNTRY_SWITZERLAND = 118;</code>
     */
    COUNTRY_SWITZERLAND(118),
    /**
     * <pre>
     * TAIWAN
     * </pre>
     *
     * <code>COUNTRY_TAIWAN = 119;</code>
     */
    COUNTRY_TAIWAN(119),
    /**
     * <pre>
     * TANZANIA
     * </pre>
     *
     * <code>COUNTRY_TANZANIA = 120;</code>
     */
    COUNTRY_TANZANIA(120),
    /**
     * <pre>
     * THAILAND
     * </pre>
     *
     * <code>COUNTRY_THAILAND = 121;</code>
     */
    COUNTRY_THAILAND(121),
    /**
     * <pre>
     * TRINIDAD AND TOBAGO
     * </pre>
     *
     * <code>COUNTRY_TRINIDAD_AND_TOBAGO = 122;</code>
     */
    COUNTRY_TRINIDAD_AND_TOBAGO(122),
    /**
     * <pre>
     * TUNISIA
     * </pre>
     *
     * <code>COUNTRY_TUNISIA = 123;</code>
     */
    COUNTRY_TUNISIA(123),
    /**
     * <pre>
     * TURKEY
     * </pre>
     *
     * <code>COUNTRY_TURKEY = 124;</code>
     */
    COUNTRY_TURKEY(124),
    /**
     * <pre>
     * UAE
     * </pre>
     *
     * <code>COUNTRY_UAE = 125;</code>
     */
    COUNTRY_UAE(125),
    /**
     * <pre>
     * UK
     * </pre>
     *
     * <code>COUNTRY_UK = 126;</code>
     */
    COUNTRY_UK(126),
    /**
     * <pre>
     * UKRAINE
     * </pre>
     *
     * <code>COUNTRY_UKRAINE = 127;</code>
     */
    COUNTRY_UKRAINE(127),
    /**
     * <pre>
     * URUGUAY
     * </pre>
     *
     * <code>COUNTRY_URUGUAY = 128;</code>
     */
    COUNTRY_URUGUAY(128),
    /**
     * <pre>
     * USA
     * </pre>
     *
     * <code>COUNTRY_USA = 129;</code>
     */
    COUNTRY_USA(129),
    /**
     * <pre>
     * UZBEKISTAN
     * </pre>
     *
     * <code>COUNTRY_UZBEKISTAN = 130;</code>
     */
    COUNTRY_UZBEKISTAN(130),
    /**
     * <pre>
     * VENEZUELA
     * </pre>
     *
     * <code>COUNTRY_VENEZUELA = 131;</code>
     */
    COUNTRY_VENEZUELA(131),
    /**
     * <pre>
     * VIETNAM
     * </pre>
     *
     * <code>COUNTRY_VIETNAM = 132;</code>
     */
    COUNTRY_VIETNAM(132),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 2,
        /* suffix= */ "",
        Country.class.getName());
    }
    /**
     * <pre>
     * Not available
     * </pre>
     *
     * <code>COUNTRY_NOT_AVAILABLE = 0;</code>
     */
    public static final int COUNTRY_NOT_AVAILABLE_VALUE = 0;
    /**
     * <pre>
     * AFGHANISTAN
     * </pre>
     *
     * <code>COUNTRY_AFGHANISTAN = 1;</code>
     */
    public static final int COUNTRY_AFGHANISTAN_VALUE = 1;
    /**
     * <pre>
     * ALBANIA
     * </pre>
     *
     * <code>COUNTRY_ALBANIA = 2;</code>
     */
    public static final int COUNTRY_ALBANIA_VALUE = 2;
    /**
     * <pre>
     * ALGERIA
     * </pre>
     *
     * <code>COUNTRY_ALGERIA = 3;</code>
     */
    public static final int COUNTRY_ALGERIA_VALUE = 3;
    /**
     * <pre>
     * ANTIGUA AND BARBUDA
     * </pre>
     *
     * <code>COUNTRY_ANTIGUA_AND_BARBUDA = 4;</code>
     */
    public static final int COUNTRY_ANTIGUA_AND_BARBUDA_VALUE = 4;
    /**
     * <pre>
     * ARGENTINA
     * </pre>
     *
     * <code>COUNTRY_ARGENTINA = 5;</code>
     */
    public static final int COUNTRY_ARGENTINA_VALUE = 5;
    /**
     * <pre>
     * ARMENIA
     * </pre>
     *
     * <code>COUNTRY_ARMENIA = 6;</code>
     */
    public static final int COUNTRY_ARMENIA_VALUE = 6;
    /**
     * <pre>
     * AUSTRALIA
     * </pre>
     *
     * <code>COUNTRY_AUSTRALIA = 7;</code>
     */
    public static final int COUNTRY_AUSTRALIA_VALUE = 7;
    /**
     * <pre>
     * AUSTRIA
     * </pre>
     *
     * <code>COUNTRY_AUSTRIA = 8;</code>
     */
    public static final int COUNTRY_AUSTRIA_VALUE = 8;
    /**
     * <pre>
     * AZERBAIJAN
     * </pre>
     *
     * <code>COUNTRY_AZERBAIJAN = 9;</code>
     */
    public static final int COUNTRY_AZERBAIJAN_VALUE = 9;
    /**
     * <pre>
     * BAHAMAS
     * </pre>
     *
     * <code>COUNTRY_BAHAMAS = 10;</code>
     */
    public static final int COUNTRY_BAHAMAS_VALUE = 10;
    /**
     * <pre>
     * BAHRAIN
     * </pre>
     *
     * <code>COUNTRY_BAHRAIN = 11;</code>
     */
    public static final int COUNTRY_BAHRAIN_VALUE = 11;
    /**
     * <pre>
     * BANGLADESH
     * </pre>
     *
     * <code>COUNTRY_BANGLADESH = 12;</code>
     */
    public static final int COUNTRY_BANGLADESH_VALUE = 12;
    /**
     * <pre>
     * BARBADOS
     * </pre>
     *
     * <code>COUNTRY_BARBADOS = 13;</code>
     */
    public static final int COUNTRY_BARBADOS_VALUE = 13;
    /**
     * <pre>
     * BELARUS
     * </pre>
     *
     * <code>COUNTRY_BELARUS = 14;</code>
     */
    public static final int COUNTRY_BELARUS_VALUE = 14;
    /**
     * <pre>
     * BELGIUM
     * </pre>
     *
     * <code>COUNTRY_BELGIUM = 15;</code>
     */
    public static final int COUNTRY_BELGIUM_VALUE = 15;
    /**
     * <pre>
     * BERMUDA
     * </pre>
     *
     * <code>COUNTRY_BERMUDA = 16;</code>
     */
    public static final int COUNTRY_BERMUDA_VALUE = 16;
    /**
     * <pre>
     * BOLIVIA
     * </pre>
     *
     * <code>COUNTRY_BOLIVIA = 17;</code>
     */
    public static final int COUNTRY_BOLIVIA_VALUE = 17;
    /**
     * <pre>
     * BOSNIA AND HERZEGOVINA
     * </pre>
     *
     * <code>COUNTRY_BOSNIA_AND_HERZEGOVINA = 18;</code>
     */
    public static final int COUNTRY_BOSNIA_AND_HERZEGOVINA_VALUE = 18;
    /**
     * <pre>
     * BRAZIL
     * </pre>
     *
     * <code>COUNTRY_BRAZIL = 19;</code>
     */
    public static final int COUNTRY_BRAZIL_VALUE = 19;
    /**
     * <pre>
     * BRUNEI
     * </pre>
     *
     * <code>COUNTRY_BRUNEI = 20;</code>
     */
    public static final int COUNTRY_BRUNEI_VALUE = 20;
    /**
     * <pre>
     * BULGARIA
     * </pre>
     *
     * <code>COUNTRY_BULGARIA = 21;</code>
     */
    public static final int COUNTRY_BULGARIA_VALUE = 21;
    /**
     * <pre>
     * CAMBODIA
     * </pre>
     *
     * <code>COUNTRY_CAMBODIA = 22;</code>
     */
    public static final int COUNTRY_CAMBODIA_VALUE = 22;
    /**
     * <pre>
     * CAMEROON
     * </pre>
     *
     * <code>COUNTRY_CAMEROON = 23;</code>
     */
    public static final int COUNTRY_CAMEROON_VALUE = 23;
    /**
     * <pre>
     * CANADA
     * </pre>
     *
     * <code>COUNTRY_CANADA = 24;</code>
     */
    public static final int COUNTRY_CANADA_VALUE = 24;
    /**
     * <pre>
     * CAYMAN ISLANDS
     * </pre>
     *
     * <code>COUNTRY_CAYMAN_ISLANDS = 25;</code>
     */
    public static final int COUNTRY_CAYMAN_ISLANDS_VALUE = 25;
    /**
     * <pre>
     * CHILE
     * </pre>
     *
     * <code>COUNTRY_CHILE = 26;</code>
     */
    public static final int COUNTRY_CHILE_VALUE = 26;
    /**
     * <pre>
     * CHINA
     * </pre>
     *
     * <code>COUNTRY_CHINA = 27;</code>
     */
    public static final int COUNTRY_CHINA_VALUE = 27;
    /**
     * <pre>
     * COLOMBIA
     * </pre>
     *
     * <code>COUNTRY_COLOMBIA = 28;</code>
     */
    public static final int COUNTRY_COLOMBIA_VALUE = 28;
    /**
     * <pre>
     * COSTA RICA
     * </pre>
     *
     * <code>COUNTRY_COSTA_RICA = 29;</code>
     */
    public static final int COUNTRY_COSTA_RICA_VALUE = 29;
    /**
     * <pre>
     * CROATIA
     * </pre>
     *
     * <code>COUNTRY_CROATIA = 30;</code>
     */
    public static final int COUNTRY_CROATIA_VALUE = 30;
    /**
     * <pre>
     * CUBA
     * </pre>
     *
     * <code>COUNTRY_CUBA = 31;</code>
     */
    public static final int COUNTRY_CUBA_VALUE = 31;
    /**
     * <pre>
     * CYPRUS
     * </pre>
     *
     * <code>COUNTRY_CYPRUS = 32;</code>
     */
    public static final int COUNTRY_CYPRUS_VALUE = 32;
    /**
     * <pre>
     * CZECHIA
     * </pre>
     *
     * <code>COUNTRY_CZECHIA = 33;</code>
     */
    public static final int COUNTRY_CZECHIA_VALUE = 33;
    /**
     * <pre>
     * DEMOCRATIC REPUBLIC OF THE CONGO
     * </pre>
     *
     * <code>COUNTRY_DEMOCRATIC_REPUBLIC_OF_THE_CONGO = 34;</code>
     */
    public static final int COUNTRY_DEMOCRATIC_REPUBLIC_OF_THE_CONGO_VALUE = 34;
    /**
     * <pre>
     * DENMARK
     * </pre>
     *
     * <code>COUNTRY_DENMARK = 35;</code>
     */
    public static final int COUNTRY_DENMARK_VALUE = 35;
    /**
     * <pre>
     * DOMINICAN REPUBLIC
     * </pre>
     *
     * <code>COUNTRY_DOMINICAN_REPUBLIC = 36;</code>
     */
    public static final int COUNTRY_DOMINICAN_REPUBLIC_VALUE = 36;
    /**
     * <pre>
     * ECUADOR
     * </pre>
     *
     * <code>COUNTRY_ECUADOR = 37;</code>
     */
    public static final int COUNTRY_ECUADOR_VALUE = 37;
    /**
     * <pre>
     * EGYPT
     * </pre>
     *
     * <code>COUNTRY_EGYPT = 38;</code>
     */
    public static final int COUNTRY_EGYPT_VALUE = 38;
    /**
     * <pre>
     * EL SALVADOR
     * </pre>
     *
     * <code>COUNTRY_EL_SALVADOR = 39;</code>
     */
    public static final int COUNTRY_EL_SALVADOR_VALUE = 39;
    /**
     * <pre>
     * ESTONIA
     * </pre>
     *
     * <code>COUNTRY_ESTONIA = 40;</code>
     */
    public static final int COUNTRY_ESTONIA_VALUE = 40;
    /**
     * <pre>
     * EUROPEAN UNION
     * </pre>
     *
     * <code>COUNTRY_EUROPEAN_UNION = 41;</code>
     */
    public static final int COUNTRY_EUROPEAN_UNION_VALUE = 41;
    /**
     * <pre>
     * FINLAND
     * </pre>
     *
     * <code>COUNTRY_FINLAND = 42;</code>
     */
    public static final int COUNTRY_FINLAND_VALUE = 42;
    /**
     * <pre>
     * FRANCE
     * </pre>
     *
     * <code>COUNTRY_FRANCE = 43;</code>
     */
    public static final int COUNTRY_FRANCE_VALUE = 43;
    /**
     * <pre>
     * GEORGIA
     * </pre>
     *
     * <code>COUNTRY_GEORGIA = 44;</code>
     */
    public static final int COUNTRY_GEORGIA_VALUE = 44;
    /**
     * <pre>
     * GERMANY
     * </pre>
     *
     * <code>COUNTRY_GERMANY = 45;</code>
     */
    public static final int COUNTRY_GERMANY_VALUE = 45;
    /**
     * <pre>
     * GHANA
     * </pre>
     *
     * <code>COUNTRY_GHANA = 46;</code>
     */
    public static final int COUNTRY_GHANA_VALUE = 46;
    /**
     * <pre>
     * GREECE
     * </pre>
     *
     * <code>COUNTRY_GREECE = 47;</code>
     */
    public static final int COUNTRY_GREECE_VALUE = 47;
    /**
     * <pre>
     * GUATEMALA
     * </pre>
     *
     * <code>COUNTRY_GUATEMALA = 48;</code>
     */
    public static final int COUNTRY_GUATEMALA_VALUE = 48;
    /**
     * <pre>
     * HAITI
     * </pre>
     *
     * <code>COUNTRY_HAITI = 49;</code>
     */
    public static final int COUNTRY_HAITI_VALUE = 49;
    /**
     * <pre>
     * HONDURAS
     * </pre>
     *
     * <code>COUNTRY_HONDURAS = 50;</code>
     */
    public static final int COUNTRY_HONDURAS_VALUE = 50;
    /**
     * <pre>
     * HONG KONG
     * </pre>
     *
     * <code>COUNTRY_HONG_KONG = 51;</code>
     */
    public static final int COUNTRY_HONG_KONG_VALUE = 51;
    /**
     * <pre>
     * HUNGARY
     * </pre>
     *
     * <code>COUNTRY_HUNGARY = 52;</code>
     */
    public static final int COUNTRY_HUNGARY_VALUE = 52;
    /**
     * <pre>
     * ICELAND
     * </pre>
     *
     * <code>COUNTRY_ICELAND = 53;</code>
     */
    public static final int COUNTRY_ICELAND_VALUE = 53;
    /**
     * <pre>
     * INDIA
     * </pre>
     *
     * <code>COUNTRY_INDIA = 54;</code>
     */
    public static final int COUNTRY_INDIA_VALUE = 54;
    /**
     * <pre>
     * INDONESIA
     * </pre>
     *
     * <code>COUNTRY_INDONESIA = 55;</code>
     */
    public static final int COUNTRY_INDONESIA_VALUE = 55;
    /**
     * <pre>
     * IRAN
     * </pre>
     *
     * <code>COUNTRY_IRAN = 56;</code>
     */
    public static final int COUNTRY_IRAN_VALUE = 56;
    /**
     * <pre>
     * IRAQ
     * </pre>
     *
     * <code>COUNTRY_IRAQ = 57;</code>
     */
    public static final int COUNTRY_IRAQ_VALUE = 57;
    /**
     * <pre>
     * IRELAND
     * </pre>
     *
     * <code>COUNTRY_IRELAND = 58;</code>
     */
    public static final int COUNTRY_IRELAND_VALUE = 58;
    /**
     * <pre>
     * ISRAEL
     * </pre>
     *
     * <code>COUNTRY_ISRAEL = 59;</code>
     */
    public static final int COUNTRY_ISRAEL_VALUE = 59;
    /**
     * <pre>
     * ITALY
     * </pre>
     *
     * <code>COUNTRY_ITALY = 60;</code>
     */
    public static final int COUNTRY_ITALY_VALUE = 60;
    /**
     * <pre>
     * IVORY COAST
     * </pre>
     *
     * <code>COUNTRY_IVORY_COAST = 61;</code>
     */
    public static final int COUNTRY_IVORY_COAST_VALUE = 61;
    /**
     * <pre>
     * JAMAICA
     * </pre>
     *
     * <code>COUNTRY_JAMAICA = 62;</code>
     */
    public static final int COUNTRY_JAMAICA_VALUE = 62;
    /**
     * <pre>
     * JAPAN
     * </pre>
     *
     * <code>COUNTRY_JAPAN = 63;</code>
     */
    public static final int COUNTRY_JAPAN_VALUE = 63;
    /**
     * <pre>
     * JORDAN
     * </pre>
     *
     * <code>COUNTRY_JORDAN = 64;</code>
     */
    public static final int COUNTRY_JORDAN_VALUE = 64;
    /**
     * <pre>
     * KAZAKHSTAN
     * </pre>
     *
     * <code>COUNTRY_KAZAKHSTAN = 65;</code>
     */
    public static final int COUNTRY_KAZAKHSTAN_VALUE = 65;
    /**
     * <pre>
     * KENYA
     * </pre>
     *
     * <code>COUNTRY_KENYA = 66;</code>
     */
    public static final int COUNTRY_KENYA_VALUE = 66;
    /**
     * <pre>
     * KOSOVO
     * </pre>
     *
     * <code>COUNTRY_KOSOVO = 67;</code>
     */
    public static final int COUNTRY_KOSOVO_VALUE = 67;
    /**
     * <pre>
     * KUWAIT
     * </pre>
     *
     * <code>COUNTRY_KUWAIT = 68;</code>
     */
    public static final int COUNTRY_KUWAIT_VALUE = 68;
    /**
     * <pre>
     * LATVIA
     * </pre>
     *
     * <code>COUNTRY_LATVIA = 69;</code>
     */
    public static final int COUNTRY_LATVIA_VALUE = 69;
    /**
     * <pre>
     * LIBYA
     * </pre>
     *
     * <code>COUNTRY_LIBYA = 70;</code>
     */
    public static final int COUNTRY_LIBYA_VALUE = 70;
    /**
     * <pre>
     * LIECHTENSTEIN
     * </pre>
     *
     * <code>COUNTRY_LIECHTENSTEIN = 71;</code>
     */
    public static final int COUNTRY_LIECHTENSTEIN_VALUE = 71;
    /**
     * <pre>
     * LITHUANIA
     * </pre>
     *
     * <code>COUNTRY_LITHUANIA = 72;</code>
     */
    public static final int COUNTRY_LITHUANIA_VALUE = 72;
    /**
     * <pre>
     * LUXEMBOURG
     * </pre>
     *
     * <code>COUNTRY_LUXEMBOURG = 73;</code>
     */
    public static final int COUNTRY_LUXEMBOURG_VALUE = 73;
    /**
     * <pre>
     * MALAYSIA
     * </pre>
     *
     * <code>COUNTRY_MALAYSIA = 74;</code>
     */
    public static final int COUNTRY_MALAYSIA_VALUE = 74;
    /**
     * <pre>
     * MALDIVES
     * </pre>
     *
     * <code>COUNTRY_MALDIVES = 75;</code>
     */
    public static final int COUNTRY_MALDIVES_VALUE = 75;
    /**
     * <pre>
     * MALTA
     * </pre>
     *
     * <code>COUNTRY_MALTA = 76;</code>
     */
    public static final int COUNTRY_MALTA_VALUE = 76;
    /**
     * <pre>
     * MAURITIUS
     * </pre>
     *
     * <code>COUNTRY_MAURITIUS = 77;</code>
     */
    public static final int COUNTRY_MAURITIUS_VALUE = 77;
    /**
     * <pre>
     * MEXICO
     * </pre>
     *
     * <code>COUNTRY_MEXICO = 78;</code>
     */
    public static final int COUNTRY_MEXICO_VALUE = 78;
    /**
     * <pre>
     * MOLDOVA
     * </pre>
     *
     * <code>COUNTRY_MOLDOVA = 79;</code>
     */
    public static final int COUNTRY_MOLDOVA_VALUE = 79;
    /**
     * <pre>
     * MONACO
     * </pre>
     *
     * <code>COUNTRY_MONACO = 80;</code>
     */
    public static final int COUNTRY_MONACO_VALUE = 80;
    /**
     * <pre>
     * MONTENEGRO
     * </pre>
     *
     * <code>COUNTRY_MONTENEGRO = 81;</code>
     */
    public static final int COUNTRY_MONTENEGRO_VALUE = 81;
    /**
     * <pre>
     * MOROCCO
     * </pre>
     *
     * <code>COUNTRY_MOROCCO = 82;</code>
     */
    public static final int COUNTRY_MOROCCO_VALUE = 82;
    /**
     * <pre>
     * NAMIBIA
     * </pre>
     *
     * <code>COUNTRY_NAMIBIA = 83;</code>
     */
    public static final int COUNTRY_NAMIBIA_VALUE = 83;
    /**
     * <pre>
     * NEPAL
     * </pre>
     *
     * <code>COUNTRY_NEPAL = 84;</code>
     */
    public static final int COUNTRY_NEPAL_VALUE = 84;
    /**
     * <pre>
     * NETHERLANDS
     * </pre>
     *
     * <code>COUNTRY_NETHERLANDS = 85;</code>
     */
    public static final int COUNTRY_NETHERLANDS_VALUE = 85;
    /**
     * <pre>
     * NEW ZEALAND
     * </pre>
     *
     * <code>COUNTRY_NEW_ZEALAND = 86;</code>
     */
    public static final int COUNTRY_NEW_ZEALAND_VALUE = 86;
    /**
     * <pre>
     * NICARAGUA
     * </pre>
     *
     * <code>COUNTRY_NICARAGUA = 87;</code>
     */
    public static final int COUNTRY_NICARAGUA_VALUE = 87;
    /**
     * <pre>
     * NIGERIA
     * </pre>
     *
     * <code>COUNTRY_NIGERIA = 88;</code>
     */
    public static final int COUNTRY_NIGERIA_VALUE = 88;
    /**
     * <pre>
     * NORTH MACEDONIA
     * </pre>
     *
     * <code>COUNTRY_NORTH_MACEDONIA = 89;</code>
     */
    public static final int COUNTRY_NORTH_MACEDONIA_VALUE = 89;
    /**
     * <pre>
     * NORWAY
     * </pre>
     *
     * <code>COUNTRY_NORWAY = 90;</code>
     */
    public static final int COUNTRY_NORWAY_VALUE = 90;
    /**
     * <pre>
     * OMAN
     * </pre>
     *
     * <code>COUNTRY_OMAN = 91;</code>
     */
    public static final int COUNTRY_OMAN_VALUE = 91;
    /**
     * <pre>
     * PAKISTAN
     * </pre>
     *
     * <code>COUNTRY_PAKISTAN = 92;</code>
     */
    public static final int COUNTRY_PAKISTAN_VALUE = 92;
    /**
     * <pre>
     * PALESTINE
     * </pre>
     *
     * <code>COUNTRY_PALESTINE = 93;</code>
     */
    public static final int COUNTRY_PALESTINE_VALUE = 93;
    /**
     * <pre>
     * PANAMA
     * </pre>
     *
     * <code>COUNTRY_PANAMA = 94;</code>
     */
    public static final int COUNTRY_PANAMA_VALUE = 94;
    /**
     * <pre>
     * PARAGUAY
     * </pre>
     *
     * <code>COUNTRY_PARAGUAY = 95;</code>
     */
    public static final int COUNTRY_PARAGUAY_VALUE = 95;
    /**
     * <pre>
     * PERU
     * </pre>
     *
     * <code>COUNTRY_PERU = 96;</code>
     */
    public static final int COUNTRY_PERU_VALUE = 96;
    /**
     * <pre>
     * PHILIPPINES
     * </pre>
     *
     * <code>COUNTRY_PHILIPPINES = 97;</code>
     */
    public static final int COUNTRY_PHILIPPINES_VALUE = 97;
    /**
     * <pre>
     * POLAND
     * </pre>
     *
     * <code>COUNTRY_POLAND = 98;</code>
     */
    public static final int COUNTRY_POLAND_VALUE = 98;
    /**
     * <pre>
     * PORTUGAL
     * </pre>
     *
     * <code>COUNTRY_PORTUGAL = 99;</code>
     */
    public static final int COUNTRY_PORTUGAL_VALUE = 99;
    /**
     * <pre>
     * PUERTO RICO
     * </pre>
     *
     * <code>COUNTRY_PUERTO_RICO = 100;</code>
     */
    public static final int COUNTRY_PUERTO_RICO_VALUE = 100;
    /**
     * <pre>
     * QATAR
     * </pre>
     *
     * <code>COUNTRY_QATAR = 101;</code>
     */
    public static final int COUNTRY_QATAR_VALUE = 101;
    /**
     * <pre>
     * ROMANIA
     * </pre>
     *
     * <code>COUNTRY_ROMANIA = 102;</code>
     */
    public static final int COUNTRY_ROMANIA_VALUE = 102;
    /**
     * <pre>
     * RUSSIA
     * </pre>
     *
     * <code>COUNTRY_RUSSIA = 103;</code>
     */
    public static final int COUNTRY_RUSSIA_VALUE = 103;
    /**
     * <pre>
     * SAINT KITTS AND NEVIS
     * </pre>
     *
     * <code>COUNTRY_SAINT_KITTS_AND_NEVIS = 104;</code>
     */
    public static final int COUNTRY_SAINT_KITTS_AND_NEVIS_VALUE = 104;
    /**
     * <pre>
     * SAINT LUCIA
     * </pre>
     *
     * <code>COUNTRY_SAINT_LUCIA = 105;</code>
     */
    public static final int COUNTRY_SAINT_LUCIA_VALUE = 105;
    /**
     * <pre>
     * SAUDI ARABIA
     * </pre>
     *
     * <code>COUNTRY_SAUDI_ARABIA = 106;</code>
     */
    public static final int COUNTRY_SAUDI_ARABIA_VALUE = 106;
    /**
     * <pre>
     * SCHENGEN AREA
     * </pre>
     *
     * <code>COUNTRY_SCHENGEN_AREA = 107;</code>
     */
    public static final int COUNTRY_SCHENGEN_AREA_VALUE = 107;
    /**
     * <pre>
     * SERBIA
     * </pre>
     *
     * <code>COUNTRY_SERBIA = 108;</code>
     */
    public static final int COUNTRY_SERBIA_VALUE = 108;
    /**
     * <pre>
     * SINGAPORE
     * </pre>
     *
     * <code>COUNTRY_SINGAPORE = 109;</code>
     */
    public static final int COUNTRY_SINGAPORE_VALUE = 109;
    /**
     * <pre>
     * SLOVAKIA
     * </pre>
     *
     * <code>COUNTRY_SLOVAKIA = 110;</code>
     */
    public static final int COUNTRY_SLOVAKIA_VALUE = 110;
    /**
     * <pre>
     * SLOVENIA
     * </pre>
     *
     * <code>COUNTRY_SLOVENIA = 111;</code>
     */
    public static final int COUNTRY_SLOVENIA_VALUE = 111;
    /**
     * <pre>
     * SOUTH AFRICA
     * </pre>
     *
     * <code>COUNTRY_SOUTH_AFRICA = 112;</code>
     */
    public static final int COUNTRY_SOUTH_AFRICA_VALUE = 112;
    /**
     * <pre>
     * SOUTH KOREA
     * </pre>
     *
     * <code>COUNTRY_SOUTH_KOREA = 113;</code>
     */
    public static final int COUNTRY_SOUTH_KOREA_VALUE = 113;
    /**
     * <pre>
     * SPAIN
     * </pre>
     *
     * <code>COUNTRY_SPAIN = 114;</code>
     */
    public static final int COUNTRY_SPAIN_VALUE = 114;
    /**
     * <pre>
     * SRI LANKA
     * </pre>
     *
     * <code>COUNTRY_SRI_LANKA = 115;</code>
     */
    public static final int COUNTRY_SRI_LANKA_VALUE = 115;
    /**
     * <pre>
     * SUDAN
     * </pre>
     *
     * <code>COUNTRY_SUDAN = 116;</code>
     */
    public static final int COUNTRY_SUDAN_VALUE = 116;
    /**
     * <pre>
     * SWEDEN
     * </pre>
     *
     * <code>COUNTRY_SWEDEN = 117;</code>
     */
    public static final int COUNTRY_SWEDEN_VALUE = 117;
    /**
     * <pre>
     * SWITZERLAND
     * </pre>
     *
     * <code>COUNTRY_SWITZERLAND = 118;</code>
     */
    public static final int COUNTRY_SWITZERLAND_VALUE = 118;
    /**
     * <pre>
     * TAIWAN
     * </pre>
     *
     * <code>COUNTRY_TAIWAN = 119;</code>
     */
    public static final int COUNTRY_TAIWAN_VALUE = 119;
    /**
     * <pre>
     * TANZANIA
     * </pre>
     *
     * <code>COUNTRY_TANZANIA = 120;</code>
     */
    public static final int COUNTRY_TANZANIA_VALUE = 120;
    /**
     * <pre>
     * THAILAND
     * </pre>
     *
     * <code>COUNTRY_THAILAND = 121;</code>
     */
    public static final int COUNTRY_THAILAND_VALUE = 121;
    /**
     * <pre>
     * TRINIDAD AND TOBAGO
     * </pre>
     *
     * <code>COUNTRY_TRINIDAD_AND_TOBAGO = 122;</code>
     */
    public static final int COUNTRY_TRINIDAD_AND_TOBAGO_VALUE = 122;
    /**
     * <pre>
     * TUNISIA
     * </pre>
     *
     * <code>COUNTRY_TUNISIA = 123;</code>
     */
    public static final int COUNTRY_TUNISIA_VALUE = 123;
    /**
     * <pre>
     * TURKEY
     * </pre>
     *
     * <code>COUNTRY_TURKEY = 124;</code>
     */
    public static final int COUNTRY_TURKEY_VALUE = 124;
    /**
     * <pre>
     * UAE
     * </pre>
     *
     * <code>COUNTRY_UAE = 125;</code>
     */
    public static final int COUNTRY_UAE_VALUE = 125;
    /**
     * <pre>
     * UK
     * </pre>
     *
     * <code>COUNTRY_UK = 126;</code>
     */
    public static final int COUNTRY_UK_VALUE = 126;
    /**
     * <pre>
     * UKRAINE
     * </pre>
     *
     * <code>COUNTRY_UKRAINE = 127;</code>
     */
    public static final int COUNTRY_UKRAINE_VALUE = 127;
    /**
     * <pre>
     * URUGUAY
     * </pre>
     *
     * <code>COUNTRY_URUGUAY = 128;</code>
     */
    public static final int COUNTRY_URUGUAY_VALUE = 128;
    /**
     * <pre>
     * USA
     * </pre>
     *
     * <code>COUNTRY_USA = 129;</code>
     */
    public static final int COUNTRY_USA_VALUE = 129;
    /**
     * <pre>
     * UZBEKISTAN
     * </pre>
     *
     * <code>COUNTRY_UZBEKISTAN = 130;</code>
     */
    public static final int COUNTRY_UZBEKISTAN_VALUE = 130;
    /**
     * <pre>
     * VENEZUELA
     * </pre>
     *
     * <code>COUNTRY_VENEZUELA = 131;</code>
     */
    public static final int COUNTRY_VENEZUELA_VALUE = 131;
    /**
     * <pre>
     * VIETNAM
     * </pre>
     *
     * <code>COUNTRY_VIETNAM = 132;</code>
     */
    public static final int COUNTRY_VIETNAM_VALUE = 132;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Country valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Country forNumber(int value) {
      switch (value) {
        case 0: return COUNTRY_NOT_AVAILABLE;
        case 1: return COUNTRY_AFGHANISTAN;
        case 2: return COUNTRY_ALBANIA;
        case 3: return COUNTRY_ALGERIA;
        case 4: return COUNTRY_ANTIGUA_AND_BARBUDA;
        case 5: return COUNTRY_ARGENTINA;
        case 6: return COUNTRY_ARMENIA;
        case 7: return COUNTRY_AUSTRALIA;
        case 8: return COUNTRY_AUSTRIA;
        case 9: return COUNTRY_AZERBAIJAN;
        case 10: return COUNTRY_BAHAMAS;
        case 11: return COUNTRY_BAHRAIN;
        case 12: return COUNTRY_BANGLADESH;
        case 13: return COUNTRY_BARBADOS;
        case 14: return COUNTRY_BELARUS;
        case 15: return COUNTRY_BELGIUM;
        case 16: return COUNTRY_BERMUDA;
        case 17: return COUNTRY_BOLIVIA;
        case 18: return COUNTRY_BOSNIA_AND_HERZEGOVINA;
        case 19: return COUNTRY_BRAZIL;
        case 20: return COUNTRY_BRUNEI;
        case 21: return COUNTRY_BULGARIA;
        case 22: return COUNTRY_CAMBODIA;
        case 23: return COUNTRY_CAMEROON;
        case 24: return COUNTRY_CANADA;
        case 25: return COUNTRY_CAYMAN_ISLANDS;
        case 26: return COUNTRY_CHILE;
        case 27: return COUNTRY_CHINA;
        case 28: return COUNTRY_COLOMBIA;
        case 29: return COUNTRY_COSTA_RICA;
        case 30: return COUNTRY_CROATIA;
        case 31: return COUNTRY_CUBA;
        case 32: return COUNTRY_CYPRUS;
        case 33: return COUNTRY_CZECHIA;
        case 34: return COUNTRY_DEMOCRATIC_REPUBLIC_OF_THE_CONGO;
        case 35: return COUNTRY_DENMARK;
        case 36: return COUNTRY_DOMINICAN_REPUBLIC;
        case 37: return COUNTRY_ECUADOR;
        case 38: return COUNTRY_EGYPT;
        case 39: return COUNTRY_EL_SALVADOR;
        case 40: return COUNTRY_ESTONIA;
        case 41: return COUNTRY_EUROPEAN_UNION;
        case 42: return COUNTRY_FINLAND;
        case 43: return COUNTRY_FRANCE;
        case 44: return COUNTRY_GEORGIA;
        case 45: return COUNTRY_GERMANY;
        case 46: return COUNTRY_GHANA;
        case 47: return COUNTRY_GREECE;
        case 48: return COUNTRY_GUATEMALA;
        case 49: return COUNTRY_HAITI;
        case 50: return COUNTRY_HONDURAS;
        case 51: return COUNTRY_HONG_KONG;
        case 52: return COUNTRY_HUNGARY;
        case 53: return COUNTRY_ICELAND;
        case 54: return COUNTRY_INDIA;
        case 55: return COUNTRY_INDONESIA;
        case 56: return COUNTRY_IRAN;
        case 57: return COUNTRY_IRAQ;
        case 58: return COUNTRY_IRELAND;
        case 59: return COUNTRY_ISRAEL;
        case 60: return COUNTRY_ITALY;
        case 61: return COUNTRY_IVORY_COAST;
        case 62: return COUNTRY_JAMAICA;
        case 63: return COUNTRY_JAPAN;
        case 64: return COUNTRY_JORDAN;
        case 65: return COUNTRY_KAZAKHSTAN;
        case 66: return COUNTRY_KENYA;
        case 67: return COUNTRY_KOSOVO;
        case 68: return COUNTRY_KUWAIT;
        case 69: return COUNTRY_LATVIA;
        case 70: return COUNTRY_LIBYA;
        case 71: return COUNTRY_LIECHTENSTEIN;
        case 72: return COUNTRY_LITHUANIA;
        case 73: return COUNTRY_LUXEMBOURG;
        case 74: return COUNTRY_MALAYSIA;
        case 75: return COUNTRY_MALDIVES;
        case 76: return COUNTRY_MALTA;
        case 77: return COUNTRY_MAURITIUS;
        case 78: return COUNTRY_MEXICO;
        case 79: return COUNTRY_MOLDOVA;
        case 80: return COUNTRY_MONACO;
        case 81: return COUNTRY_MONTENEGRO;
        case 82: return COUNTRY_MOROCCO;
        case 83: return COUNTRY_NAMIBIA;
        case 84: return COUNTRY_NEPAL;
        case 85: return COUNTRY_NETHERLANDS;
        case 86: return COUNTRY_NEW_ZEALAND;
        case 87: return COUNTRY_NICARAGUA;
        case 88: return COUNTRY_NIGERIA;
        case 89: return COUNTRY_NORTH_MACEDONIA;
        case 90: return COUNTRY_NORWAY;
        case 91: return COUNTRY_OMAN;
        case 92: return COUNTRY_PAKISTAN;
        case 93: return COUNTRY_PALESTINE;
        case 94: return COUNTRY_PANAMA;
        case 95: return COUNTRY_PARAGUAY;
        case 96: return COUNTRY_PERU;
        case 97: return COUNTRY_PHILIPPINES;
        case 98: return COUNTRY_POLAND;
        case 99: return COUNTRY_PORTUGAL;
        case 100: return COUNTRY_PUERTO_RICO;
        case 101: return COUNTRY_QATAR;
        case 102: return COUNTRY_ROMANIA;
        case 103: return COUNTRY_RUSSIA;
        case 104: return COUNTRY_SAINT_KITTS_AND_NEVIS;
        case 105: return COUNTRY_SAINT_LUCIA;
        case 106: return COUNTRY_SAUDI_ARABIA;
        case 107: return COUNTRY_SCHENGEN_AREA;
        case 108: return COUNTRY_SERBIA;
        case 109: return COUNTRY_SINGAPORE;
        case 110: return COUNTRY_SLOVAKIA;
        case 111: return COUNTRY_SLOVENIA;
        case 112: return COUNTRY_SOUTH_AFRICA;
        case 113: return COUNTRY_SOUTH_KOREA;
        case 114: return COUNTRY_SPAIN;
        case 115: return COUNTRY_SRI_LANKA;
        case 116: return COUNTRY_SUDAN;
        case 117: return COUNTRY_SWEDEN;
        case 118: return COUNTRY_SWITZERLAND;
        case 119: return COUNTRY_TAIWAN;
        case 120: return COUNTRY_TANZANIA;
        case 121: return COUNTRY_THAILAND;
        case 122: return COUNTRY_TRINIDAD_AND_TOBAGO;
        case 123: return COUNTRY_TUNISIA;
        case 124: return COUNTRY_TURKEY;
        case 125: return COUNTRY_UAE;
        case 126: return COUNTRY_UK;
        case 127: return COUNTRY_UKRAINE;
        case 128: return COUNTRY_URUGUAY;
        case 129: return COUNTRY_USA;
        case 130: return COUNTRY_UZBEKISTAN;
        case 131: return COUNTRY_VENEZUELA;
        case 132: return COUNTRY_VIETNAM;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Country>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Country> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Country>() {
            public Country findValueByNumber(int number) {
              return Country.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return proto.ddx.v1.CountriesEnum.getDescriptor().getEnumTypes().get(0);
    }

    private static final Country[] VALUES = values();

    public static Country valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Country(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:proto.ddx.v1.Country)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!proto/ddx/v1/countries_enum.proto\022\014pro" +
      "to.ddx.v1*\227\027\n\007Country\022\031\n\025COUNTRY_NOT_AVA" +
      "ILABLE\020\000\022\027\n\023COUNTRY_AFGHANISTAN\020\001\022\023\n\017COU" +
      "NTRY_ALBANIA\020\002\022\023\n\017COUNTRY_ALGERIA\020\003\022\037\n\033C" +
      "OUNTRY_ANTIGUA_AND_BARBUDA\020\004\022\025\n\021COUNTRY_" +
      "ARGENTINA\020\005\022\023\n\017COUNTRY_ARMENIA\020\006\022\025\n\021COUN" +
      "TRY_AUSTRALIA\020\007\022\023\n\017COUNTRY_AUSTRIA\020\010\022\026\n\022" +
      "COUNTRY_AZERBAIJAN\020\t\022\023\n\017COUNTRY_BAHAMAS\020" +
      "\n\022\023\n\017COUNTRY_BAHRAIN\020\013\022\026\n\022COUNTRY_BANGLA" +
      "DESH\020\014\022\024\n\020COUNTRY_BARBADOS\020\r\022\023\n\017COUNTRY_" +
      "BELARUS\020\016\022\023\n\017COUNTRY_BELGIUM\020\017\022\023\n\017COUNTR" +
      "Y_BERMUDA\020\020\022\023\n\017COUNTRY_BOLIVIA\020\021\022\"\n\036COUN" +
      "TRY_BOSNIA_AND_HERZEGOVINA\020\022\022\022\n\016COUNTRY_" +
      "BRAZIL\020\023\022\022\n\016COUNTRY_BRUNEI\020\024\022\024\n\020COUNTRY_" +
      "BULGARIA\020\025\022\024\n\020COUNTRY_CAMBODIA\020\026\022\024\n\020COUN" +
      "TRY_CAMEROON\020\027\022\022\n\016COUNTRY_CANADA\020\030\022\032\n\026CO" +
      "UNTRY_CAYMAN_ISLANDS\020\031\022\021\n\rCOUNTRY_CHILE\020" +
      "\032\022\021\n\rCOUNTRY_CHINA\020\033\022\024\n\020COUNTRY_COLOMBIA" +
      "\020\034\022\026\n\022COUNTRY_COSTA_RICA\020\035\022\023\n\017COUNTRY_CR" +
      "OATIA\020\036\022\020\n\014COUNTRY_CUBA\020\037\022\022\n\016COUNTRY_CYP" +
      "RUS\020 \022\023\n\017COUNTRY_CZECHIA\020!\022,\n(COUNTRY_DE" +
      "MOCRATIC_REPUBLIC_OF_THE_CONGO\020\"\022\023\n\017COUN" +
      "TRY_DENMARK\020#\022\036\n\032COUNTRY_DOMINICAN_REPUB" +
      "LIC\020$\022\023\n\017COUNTRY_ECUADOR\020%\022\021\n\rCOUNTRY_EG" +
      "YPT\020&\022\027\n\023COUNTRY_EL_SALVADOR\020\'\022\023\n\017COUNTR" +
      "Y_ESTONIA\020(\022\032\n\026COUNTRY_EUROPEAN_UNION\020)\022" +
      "\023\n\017COUNTRY_FINLAND\020*\022\022\n\016COUNTRY_FRANCE\020+" +
      "\022\023\n\017COUNTRY_GEORGIA\020,\022\023\n\017COUNTRY_GERMANY" +
      "\020-\022\021\n\rCOUNTRY_GHANA\020.\022\022\n\016COUNTRY_GREECE\020" +
      "/\022\025\n\021COUNTRY_GUATEMALA\0200\022\021\n\rCOUNTRY_HAIT" +
      "I\0201\022\024\n\020COUNTRY_HONDURAS\0202\022\025\n\021COUNTRY_HON" +
      "G_KONG\0203\022\023\n\017COUNTRY_HUNGARY\0204\022\023\n\017COUNTRY" +
      "_ICELAND\0205\022\021\n\rCOUNTRY_INDIA\0206\022\025\n\021COUNTRY" +
      "_INDONESIA\0207\022\020\n\014COUNTRY_IRAN\0208\022\020\n\014COUNTR" +
      "Y_IRAQ\0209\022\023\n\017COUNTRY_IRELAND\020:\022\022\n\016COUNTRY" +
      "_ISRAEL\020;\022\021\n\rCOUNTRY_ITALY\020<\022\027\n\023COUNTRY_" +
      "IVORY_COAST\020=\022\023\n\017COUNTRY_JAMAICA\020>\022\021\n\rCO" +
      "UNTRY_JAPAN\020?\022\022\n\016COUNTRY_JORDAN\020@\022\026\n\022COU" +
      "NTRY_KAZAKHSTAN\020A\022\021\n\rCOUNTRY_KENYA\020B\022\022\n\016" +
      "COUNTRY_KOSOVO\020C\022\022\n\016COUNTRY_KUWAIT\020D\022\022\n\016" +
      "COUNTRY_LATVIA\020E\022\021\n\rCOUNTRY_LIBYA\020F\022\031\n\025C" +
      "OUNTRY_LIECHTENSTEIN\020G\022\025\n\021COUNTRY_LITHUA" +
      "NIA\020H\022\026\n\022COUNTRY_LUXEMBOURG\020I\022\024\n\020COUNTRY" +
      "_MALAYSIA\020J\022\024\n\020COUNTRY_MALDIVES\020K\022\021\n\rCOU" +
      "NTRY_MALTA\020L\022\025\n\021COUNTRY_MAURITIUS\020M\022\022\n\016C" +
      "OUNTRY_MEXICO\020N\022\023\n\017COUNTRY_MOLDOVA\020O\022\022\n\016" +
      "COUNTRY_MONACO\020P\022\026\n\022COUNTRY_MONTENEGRO\020Q" +
      "\022\023\n\017COUNTRY_MOROCCO\020R\022\023\n\017COUNTRY_NAMIBIA" +
      "\020S\022\021\n\rCOUNTRY_NEPAL\020T\022\027\n\023COUNTRY_NETHERL" +
      "ANDS\020U\022\027\n\023COUNTRY_NEW_ZEALAND\020V\022\025\n\021COUNT" +
      "RY_NICARAGUA\020W\022\023\n\017COUNTRY_NIGERIA\020X\022\033\n\027C" +
      "OUNTRY_NORTH_MACEDONIA\020Y\022\022\n\016COUNTRY_NORW" +
      "AY\020Z\022\020\n\014COUNTRY_OMAN\020[\022\024\n\020COUNTRY_PAKIST" +
      "AN\020\\\022\025\n\021COUNTRY_PALESTINE\020]\022\022\n\016COUNTRY_P" +
      "ANAMA\020^\022\024\n\020COUNTRY_PARAGUAY\020_\022\020\n\014COUNTRY" +
      "_PERU\020`\022\027\n\023COUNTRY_PHILIPPINES\020a\022\022\n\016COUN" +
      "TRY_POLAND\020b\022\024\n\020COUNTRY_PORTUGAL\020c\022\027\n\023CO" +
      "UNTRY_PUERTO_RICO\020d\022\021\n\rCOUNTRY_QATAR\020e\022\023" +
      "\n\017COUNTRY_ROMANIA\020f\022\022\n\016COUNTRY_RUSSIA\020g\022" +
      "!\n\035COUNTRY_SAINT_KITTS_AND_NEVIS\020h\022\027\n\023CO" +
      "UNTRY_SAINT_LUCIA\020i\022\030\n\024COUNTRY_SAUDI_ARA" +
      "BIA\020j\022\031\n\025COUNTRY_SCHENGEN_AREA\020k\022\022\n\016COUN" +
      "TRY_SERBIA\020l\022\025\n\021COUNTRY_SINGAPORE\020m\022\024\n\020C" +
      "OUNTRY_SLOVAKIA\020n\022\024\n\020COUNTRY_SLOVENIA\020o\022" +
      "\030\n\024COUNTRY_SOUTH_AFRICA\020p\022\027\n\023COUNTRY_SOU" +
      "TH_KOREA\020q\022\021\n\rCOUNTRY_SPAIN\020r\022\025\n\021COUNTRY" +
      "_SRI_LANKA\020s\022\021\n\rCOUNTRY_SUDAN\020t\022\022\n\016COUNT" +
      "RY_SWEDEN\020u\022\027\n\023COUNTRY_SWITZERLAND\020v\022\022\n\016" +
      "COUNTRY_TAIWAN\020w\022\024\n\020COUNTRY_TANZANIA\020x\022\024" +
      "\n\020COUNTRY_THAILAND\020y\022\037\n\033COUNTRY_TRINIDAD" +
      "_AND_TOBAGO\020z\022\023\n\017COUNTRY_TUNISIA\020{\022\022\n\016CO" +
      "UNTRY_TURKEY\020|\022\017\n\013COUNTRY_UAE\020}\022\016\n\nCOUNT" +
      "RY_UK\020~\022\023\n\017COUNTRY_UKRAINE\020\177\022\024\n\017COUNTRY_" +
      "URUGUAY\020\200\001\022\020\n\013COUNTRY_USA\020\201\001\022\027\n\022COUNTRY_" +
      "UZBEKISTAN\020\202\001\022\026\n\021COUNTRY_VENEZUELA\020\203\001\022\024\n" +
      "\017COUNTRY_VIETNAM\020\204\001B4Z2github.com/veridi" +
      "l/id-extract-service/proto/ddx/v1b\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
