// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/ddx/v1/mrz.proto
// Protobuf Java Version: 4.28.2

package proto.ddx.v1;

public final class Mrz {
  private Mrz() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      Mrz.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MrzFieldsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.ddx.v1.MrzFields)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string document_type = 1 [json_name = "documentType"];</code>
     * @return The documentType.
     */
    java.lang.String getDocumentType();
    /**
     * <code>string document_type = 1 [json_name = "documentType"];</code>
     * @return The bytes for documentType.
     */
    com.google.protobuf.ByteString
        getDocumentTypeBytes();

    /**
     * <code>string country_code = 2 [json_name = "countryCode"];</code>
     * @return The countryCode.
     */
    java.lang.String getCountryCode();
    /**
     * <code>string country_code = 2 [json_name = "countryCode"];</code>
     * @return The bytes for countryCode.
     */
    com.google.protobuf.ByteString
        getCountryCodeBytes();

    /**
     * <code>string document_number = 3 [json_name = "documentNumber"];</code>
     * @return The documentNumber.
     */
    java.lang.String getDocumentNumber();
    /**
     * <code>string document_number = 3 [json_name = "documentNumber"];</code>
     * @return The bytes for documentNumber.
     */
    com.google.protobuf.ByteString
        getDocumentNumberBytes();

    /**
     * <code>string birthdate = 4 [json_name = "birthdate"];</code>
     * @return The birthdate.
     */
    java.lang.String getBirthdate();
    /**
     * <code>string birthdate = 4 [json_name = "birthdate"];</code>
     * @return The bytes for birthdate.
     */
    com.google.protobuf.ByteString
        getBirthdateBytes();

    /**
     * <code>string sex = 5 [json_name = "sex"];</code>
     * @return The sex.
     */
    java.lang.String getSex();
    /**
     * <code>string sex = 5 [json_name = "sex"];</code>
     * @return The bytes for sex.
     */
    com.google.protobuf.ByteString
        getSexBytes();

    /**
     * <code>string expiry_date = 6 [json_name = "expiryDate"];</code>
     * @return The expiryDate.
     */
    java.lang.String getExpiryDate();
    /**
     * <code>string expiry_date = 6 [json_name = "expiryDate"];</code>
     * @return The bytes for expiryDate.
     */
    com.google.protobuf.ByteString
        getExpiryDateBytes();

    /**
     * <code>string nationality = 7 [json_name = "nationality"];</code>
     * @return The nationality.
     */
    java.lang.String getNationality();
    /**
     * <code>string nationality = 7 [json_name = "nationality"];</code>
     * @return The bytes for nationality.
     */
    com.google.protobuf.ByteString
        getNationalityBytes();

    /**
     * <code>string final_check_digit = 8 [json_name = "finalCheckDigit"];</code>
     * @return The finalCheckDigit.
     */
    java.lang.String getFinalCheckDigit();
    /**
     * <code>string final_check_digit = 8 [json_name = "finalCheckDigit"];</code>
     * @return The bytes for finalCheckDigit.
     */
    com.google.protobuf.ByteString
        getFinalCheckDigitBytes();

    /**
     * <code>string name = 9 [json_name = "name"];</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 9 [json_name = "name"];</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string surname = 10 [json_name = "surname"];</code>
     * @return The surname.
     */
    java.lang.String getSurname();
    /**
     * <code>string surname = 10 [json_name = "surname"];</code>
     * @return The bytes for surname.
     */
    com.google.protobuf.ByteString
        getSurnameBytes();

    /**
     * <code>string given_name = 11 [json_name = "givenName"];</code>
     * @return The givenName.
     */
    java.lang.String getGivenName();
    /**
     * <code>string given_name = 11 [json_name = "givenName"];</code>
     * @return The bytes for givenName.
     */
    com.google.protobuf.ByteString
        getGivenNameBytes();

    /**
     * <code>string optional_data1 = 12 [json_name = "optionalData1"];</code>
     * @return The optionalData1.
     */
    java.lang.String getOptionalData1();
    /**
     * <code>string optional_data1 = 12 [json_name = "optionalData1"];</code>
     * @return The bytes for optionalData1.
     */
    com.google.protobuf.ByteString
        getOptionalData1Bytes();

    /**
     * <code>string optional_data2 = 13 [json_name = "optionalData2"];</code>
     * @return The optionalData2.
     */
    java.lang.String getOptionalData2();
    /**
     * <code>string optional_data2 = 13 [json_name = "optionalData2"];</code>
     * @return The bytes for optionalData2.
     */
    com.google.protobuf.ByteString
        getOptionalData2Bytes();

    /**
     * <pre>
     * is_visa - true for VISAs' MRZ
     * </pre>
     *
     * <code>bool is_visa = 14 [json_name = "isVisa"];</code>
     * @return The isVisa.
     */
    boolean getIsVisa();
  }
  /**
   * <pre>
   * MrzFields - a set of fields extracted from MRZ. Any of the fields can be empty!!
   * Depending on what was stored in the MRZ
   * </pre>
   *
   * Protobuf type {@code proto.ddx.v1.MrzFields}
   */
  public static final class MrzFields extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:proto.ddx.v1.MrzFields)
      MrzFieldsOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 2,
        /* suffix= */ "",
        MrzFields.class.getName());
    }
    // Use MrzFields.newBuilder() to construct.
    private MrzFields(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private MrzFields() {
      documentType_ = "";
      countryCode_ = "";
      documentNumber_ = "";
      birthdate_ = "";
      sex_ = "";
      expiryDate_ = "";
      nationality_ = "";
      finalCheckDigit_ = "";
      name_ = "";
      surname_ = "";
      givenName_ = "";
      optionalData1_ = "";
      optionalData2_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.ddx.v1.Mrz.internal_static_proto_ddx_v1_MrzFields_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.ddx.v1.Mrz.internal_static_proto_ddx_v1_MrzFields_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.ddx.v1.Mrz.MrzFields.class, proto.ddx.v1.Mrz.MrzFields.Builder.class);
    }

    public static final int DOCUMENT_TYPE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object documentType_ = "";
    /**
     * <code>string document_type = 1 [json_name = "documentType"];</code>
     * @return The documentType.
     */
    @java.lang.Override
    public java.lang.String getDocumentType() {
      java.lang.Object ref = documentType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        documentType_ = s;
        return s;
      }
    }
    /**
     * <code>string document_type = 1 [json_name = "documentType"];</code>
     * @return The bytes for documentType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDocumentTypeBytes() {
      java.lang.Object ref = documentType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        documentType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COUNTRY_CODE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object countryCode_ = "";
    /**
     * <code>string country_code = 2 [json_name = "countryCode"];</code>
     * @return The countryCode.
     */
    @java.lang.Override
    public java.lang.String getCountryCode() {
      java.lang.Object ref = countryCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        countryCode_ = s;
        return s;
      }
    }
    /**
     * <code>string country_code = 2 [json_name = "countryCode"];</code>
     * @return The bytes for countryCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCountryCodeBytes() {
      java.lang.Object ref = countryCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        countryCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DOCUMENT_NUMBER_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object documentNumber_ = "";
    /**
     * <code>string document_number = 3 [json_name = "documentNumber"];</code>
     * @return The documentNumber.
     */
    @java.lang.Override
    public java.lang.String getDocumentNumber() {
      java.lang.Object ref = documentNumber_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        documentNumber_ = s;
        return s;
      }
    }
    /**
     * <code>string document_number = 3 [json_name = "documentNumber"];</code>
     * @return The bytes for documentNumber.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDocumentNumberBytes() {
      java.lang.Object ref = documentNumber_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        documentNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BIRTHDATE_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object birthdate_ = "";
    /**
     * <code>string birthdate = 4 [json_name = "birthdate"];</code>
     * @return The birthdate.
     */
    @java.lang.Override
    public java.lang.String getBirthdate() {
      java.lang.Object ref = birthdate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        birthdate_ = s;
        return s;
      }
    }
    /**
     * <code>string birthdate = 4 [json_name = "birthdate"];</code>
     * @return The bytes for birthdate.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBirthdateBytes() {
      java.lang.Object ref = birthdate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        birthdate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEX_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object sex_ = "";
    /**
     * <code>string sex = 5 [json_name = "sex"];</code>
     * @return The sex.
     */
    @java.lang.Override
    public java.lang.String getSex() {
      java.lang.Object ref = sex_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sex_ = s;
        return s;
      }
    }
    /**
     * <code>string sex = 5 [json_name = "sex"];</code>
     * @return The bytes for sex.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSexBytes() {
      java.lang.Object ref = sex_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sex_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXPIRY_DATE_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object expiryDate_ = "";
    /**
     * <code>string expiry_date = 6 [json_name = "expiryDate"];</code>
     * @return The expiryDate.
     */
    @java.lang.Override
    public java.lang.String getExpiryDate() {
      java.lang.Object ref = expiryDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        expiryDate_ = s;
        return s;
      }
    }
    /**
     * <code>string expiry_date = 6 [json_name = "expiryDate"];</code>
     * @return The bytes for expiryDate.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getExpiryDateBytes() {
      java.lang.Object ref = expiryDate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        expiryDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NATIONALITY_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private volatile java.lang.Object nationality_ = "";
    /**
     * <code>string nationality = 7 [json_name = "nationality"];</code>
     * @return The nationality.
     */
    @java.lang.Override
    public java.lang.String getNationality() {
      java.lang.Object ref = nationality_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nationality_ = s;
        return s;
      }
    }
    /**
     * <code>string nationality = 7 [json_name = "nationality"];</code>
     * @return The bytes for nationality.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNationalityBytes() {
      java.lang.Object ref = nationality_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nationality_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FINAL_CHECK_DIGIT_FIELD_NUMBER = 8;
    @SuppressWarnings("serial")
    private volatile java.lang.Object finalCheckDigit_ = "";
    /**
     * <code>string final_check_digit = 8 [json_name = "finalCheckDigit"];</code>
     * @return The finalCheckDigit.
     */
    @java.lang.Override
    public java.lang.String getFinalCheckDigit() {
      java.lang.Object ref = finalCheckDigit_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        finalCheckDigit_ = s;
        return s;
      }
    }
    /**
     * <code>string final_check_digit = 8 [json_name = "finalCheckDigit"];</code>
     * @return The bytes for finalCheckDigit.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFinalCheckDigitBytes() {
      java.lang.Object ref = finalCheckDigit_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        finalCheckDigit_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 9;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 9 [json_name = "name"];</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 9 [json_name = "name"];</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SURNAME_FIELD_NUMBER = 10;
    @SuppressWarnings("serial")
    private volatile java.lang.Object surname_ = "";
    /**
     * <code>string surname = 10 [json_name = "surname"];</code>
     * @return The surname.
     */
    @java.lang.Override
    public java.lang.String getSurname() {
      java.lang.Object ref = surname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        surname_ = s;
        return s;
      }
    }
    /**
     * <code>string surname = 10 [json_name = "surname"];</code>
     * @return The bytes for surname.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSurnameBytes() {
      java.lang.Object ref = surname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        surname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GIVEN_NAME_FIELD_NUMBER = 11;
    @SuppressWarnings("serial")
    private volatile java.lang.Object givenName_ = "";
    /**
     * <code>string given_name = 11 [json_name = "givenName"];</code>
     * @return The givenName.
     */
    @java.lang.Override
    public java.lang.String getGivenName() {
      java.lang.Object ref = givenName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        givenName_ = s;
        return s;
      }
    }
    /**
     * <code>string given_name = 11 [json_name = "givenName"];</code>
     * @return The bytes for givenName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getGivenNameBytes() {
      java.lang.Object ref = givenName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        givenName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OPTIONAL_DATA1_FIELD_NUMBER = 12;
    @SuppressWarnings("serial")
    private volatile java.lang.Object optionalData1_ = "";
    /**
     * <code>string optional_data1 = 12 [json_name = "optionalData1"];</code>
     * @return The optionalData1.
     */
    @java.lang.Override
    public java.lang.String getOptionalData1() {
      java.lang.Object ref = optionalData1_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        optionalData1_ = s;
        return s;
      }
    }
    /**
     * <code>string optional_data1 = 12 [json_name = "optionalData1"];</code>
     * @return The bytes for optionalData1.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOptionalData1Bytes() {
      java.lang.Object ref = optionalData1_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        optionalData1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OPTIONAL_DATA2_FIELD_NUMBER = 13;
    @SuppressWarnings("serial")
    private volatile java.lang.Object optionalData2_ = "";
    /**
     * <code>string optional_data2 = 13 [json_name = "optionalData2"];</code>
     * @return The optionalData2.
     */
    @java.lang.Override
    public java.lang.String getOptionalData2() {
      java.lang.Object ref = optionalData2_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        optionalData2_ = s;
        return s;
      }
    }
    /**
     * <code>string optional_data2 = 13 [json_name = "optionalData2"];</code>
     * @return The bytes for optionalData2.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOptionalData2Bytes() {
      java.lang.Object ref = optionalData2_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        optionalData2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IS_VISA_FIELD_NUMBER = 14;
    private boolean isVisa_ = false;
    /**
     * <pre>
     * is_visa - true for VISAs' MRZ
     * </pre>
     *
     * <code>bool is_visa = 14 [json_name = "isVisa"];</code>
     * @return The isVisa.
     */
    @java.lang.Override
    public boolean getIsVisa() {
      return isVisa_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(documentType_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, documentType_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(countryCode_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, countryCode_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(documentNumber_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, documentNumber_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(birthdate_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, birthdate_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sex_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, sex_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(expiryDate_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 6, expiryDate_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nationality_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 7, nationality_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(finalCheckDigit_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 8, finalCheckDigit_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 9, name_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(surname_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 10, surname_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(givenName_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 11, givenName_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(optionalData1_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 12, optionalData1_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(optionalData2_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 13, optionalData2_);
      }
      if (isVisa_ != false) {
        output.writeBool(14, isVisa_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(documentType_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, documentType_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(countryCode_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, countryCode_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(documentNumber_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, documentNumber_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(birthdate_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, birthdate_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sex_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(5, sex_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(expiryDate_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(6, expiryDate_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nationality_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(7, nationality_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(finalCheckDigit_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(8, finalCheckDigit_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(9, name_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(surname_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(10, surname_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(givenName_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(11, givenName_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(optionalData1_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(12, optionalData1_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(optionalData2_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(13, optionalData2_);
      }
      if (isVisa_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(14, isVisa_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.ddx.v1.Mrz.MrzFields)) {
        return super.equals(obj);
      }
      proto.ddx.v1.Mrz.MrzFields other = (proto.ddx.v1.Mrz.MrzFields) obj;

      if (!getDocumentType()
          .equals(other.getDocumentType())) return false;
      if (!getCountryCode()
          .equals(other.getCountryCode())) return false;
      if (!getDocumentNumber()
          .equals(other.getDocumentNumber())) return false;
      if (!getBirthdate()
          .equals(other.getBirthdate())) return false;
      if (!getSex()
          .equals(other.getSex())) return false;
      if (!getExpiryDate()
          .equals(other.getExpiryDate())) return false;
      if (!getNationality()
          .equals(other.getNationality())) return false;
      if (!getFinalCheckDigit()
          .equals(other.getFinalCheckDigit())) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getSurname()
          .equals(other.getSurname())) return false;
      if (!getGivenName()
          .equals(other.getGivenName())) return false;
      if (!getOptionalData1()
          .equals(other.getOptionalData1())) return false;
      if (!getOptionalData2()
          .equals(other.getOptionalData2())) return false;
      if (getIsVisa()
          != other.getIsVisa()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DOCUMENT_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getDocumentType().hashCode();
      hash = (37 * hash) + COUNTRY_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCountryCode().hashCode();
      hash = (37 * hash) + DOCUMENT_NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getDocumentNumber().hashCode();
      hash = (37 * hash) + BIRTHDATE_FIELD_NUMBER;
      hash = (53 * hash) + getBirthdate().hashCode();
      hash = (37 * hash) + SEX_FIELD_NUMBER;
      hash = (53 * hash) + getSex().hashCode();
      hash = (37 * hash) + EXPIRY_DATE_FIELD_NUMBER;
      hash = (53 * hash) + getExpiryDate().hashCode();
      hash = (37 * hash) + NATIONALITY_FIELD_NUMBER;
      hash = (53 * hash) + getNationality().hashCode();
      hash = (37 * hash) + FINAL_CHECK_DIGIT_FIELD_NUMBER;
      hash = (53 * hash) + getFinalCheckDigit().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + SURNAME_FIELD_NUMBER;
      hash = (53 * hash) + getSurname().hashCode();
      hash = (37 * hash) + GIVEN_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getGivenName().hashCode();
      hash = (37 * hash) + OPTIONAL_DATA1_FIELD_NUMBER;
      hash = (53 * hash) + getOptionalData1().hashCode();
      hash = (37 * hash) + OPTIONAL_DATA2_FIELD_NUMBER;
      hash = (53 * hash) + getOptionalData2().hashCode();
      hash = (37 * hash) + IS_VISA_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsVisa());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.ddx.v1.Mrz.MrzFields parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.ddx.v1.Mrz.MrzFields parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.ddx.v1.Mrz.MrzFields parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.ddx.v1.Mrz.MrzFields parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.ddx.v1.Mrz.MrzFields parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.ddx.v1.Mrz.MrzFields parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.ddx.v1.Mrz.MrzFields parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static proto.ddx.v1.Mrz.MrzFields parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static proto.ddx.v1.Mrz.MrzFields parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static proto.ddx.v1.Mrz.MrzFields parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.ddx.v1.Mrz.MrzFields parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static proto.ddx.v1.Mrz.MrzFields parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.ddx.v1.Mrz.MrzFields prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * MrzFields - a set of fields extracted from MRZ. Any of the fields can be empty!!
     * Depending on what was stored in the MRZ
     * </pre>
     *
     * Protobuf type {@code proto.ddx.v1.MrzFields}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.ddx.v1.MrzFields)
        proto.ddx.v1.Mrz.MrzFieldsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.ddx.v1.Mrz.internal_static_proto_ddx_v1_MrzFields_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.ddx.v1.Mrz.internal_static_proto_ddx_v1_MrzFields_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.ddx.v1.Mrz.MrzFields.class, proto.ddx.v1.Mrz.MrzFields.Builder.class);
      }

      // Construct using proto.ddx.v1.Mrz.MrzFields.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        documentType_ = "";
        countryCode_ = "";
        documentNumber_ = "";
        birthdate_ = "";
        sex_ = "";
        expiryDate_ = "";
        nationality_ = "";
        finalCheckDigit_ = "";
        name_ = "";
        surname_ = "";
        givenName_ = "";
        optionalData1_ = "";
        optionalData2_ = "";
        isVisa_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.ddx.v1.Mrz.internal_static_proto_ddx_v1_MrzFields_descriptor;
      }

      @java.lang.Override
      public proto.ddx.v1.Mrz.MrzFields getDefaultInstanceForType() {
        return proto.ddx.v1.Mrz.MrzFields.getDefaultInstance();
      }

      @java.lang.Override
      public proto.ddx.v1.Mrz.MrzFields build() {
        proto.ddx.v1.Mrz.MrzFields result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.ddx.v1.Mrz.MrzFields buildPartial() {
        proto.ddx.v1.Mrz.MrzFields result = new proto.ddx.v1.Mrz.MrzFields(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(proto.ddx.v1.Mrz.MrzFields result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.documentType_ = documentType_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.countryCode_ = countryCode_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.documentNumber_ = documentNumber_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.birthdate_ = birthdate_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.sex_ = sex_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.expiryDate_ = expiryDate_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.nationality_ = nationality_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.finalCheckDigit_ = finalCheckDigit_;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.surname_ = surname_;
        }
        if (((from_bitField0_ & 0x00000400) != 0)) {
          result.givenName_ = givenName_;
        }
        if (((from_bitField0_ & 0x00000800) != 0)) {
          result.optionalData1_ = optionalData1_;
        }
        if (((from_bitField0_ & 0x00001000) != 0)) {
          result.optionalData2_ = optionalData2_;
        }
        if (((from_bitField0_ & 0x00002000) != 0)) {
          result.isVisa_ = isVisa_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.ddx.v1.Mrz.MrzFields) {
          return mergeFrom((proto.ddx.v1.Mrz.MrzFields)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.ddx.v1.Mrz.MrzFields other) {
        if (other == proto.ddx.v1.Mrz.MrzFields.getDefaultInstance()) return this;
        if (!other.getDocumentType().isEmpty()) {
          documentType_ = other.documentType_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getCountryCode().isEmpty()) {
          countryCode_ = other.countryCode_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getDocumentNumber().isEmpty()) {
          documentNumber_ = other.documentNumber_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getBirthdate().isEmpty()) {
          birthdate_ = other.birthdate_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.getSex().isEmpty()) {
          sex_ = other.sex_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (!other.getExpiryDate().isEmpty()) {
          expiryDate_ = other.expiryDate_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        if (!other.getNationality().isEmpty()) {
          nationality_ = other.nationality_;
          bitField0_ |= 0x00000040;
          onChanged();
        }
        if (!other.getFinalCheckDigit().isEmpty()) {
          finalCheckDigit_ = other.finalCheckDigit_;
          bitField0_ |= 0x00000080;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000100;
          onChanged();
        }
        if (!other.getSurname().isEmpty()) {
          surname_ = other.surname_;
          bitField0_ |= 0x00000200;
          onChanged();
        }
        if (!other.getGivenName().isEmpty()) {
          givenName_ = other.givenName_;
          bitField0_ |= 0x00000400;
          onChanged();
        }
        if (!other.getOptionalData1().isEmpty()) {
          optionalData1_ = other.optionalData1_;
          bitField0_ |= 0x00000800;
          onChanged();
        }
        if (!other.getOptionalData2().isEmpty()) {
          optionalData2_ = other.optionalData2_;
          bitField0_ |= 0x00001000;
          onChanged();
        }
        if (other.getIsVisa() != false) {
          setIsVisa(other.getIsVisa());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                documentType_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                countryCode_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                documentNumber_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                birthdate_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                sex_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                expiryDate_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 58: {
                nationality_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              case 66: {
                finalCheckDigit_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000080;
                break;
              } // case 66
              case 74: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000100;
                break;
              } // case 74
              case 82: {
                surname_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000200;
                break;
              } // case 82
              case 90: {
                givenName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000400;
                break;
              } // case 90
              case 98: {
                optionalData1_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000800;
                break;
              } // case 98
              case 106: {
                optionalData2_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00001000;
                break;
              } // case 106
              case 112: {
                isVisa_ = input.readBool();
                bitField0_ |= 0x00002000;
                break;
              } // case 112
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object documentType_ = "";
      /**
       * <code>string document_type = 1 [json_name = "documentType"];</code>
       * @return The documentType.
       */
      public java.lang.String getDocumentType() {
        java.lang.Object ref = documentType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          documentType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string document_type = 1 [json_name = "documentType"];</code>
       * @return The bytes for documentType.
       */
      public com.google.protobuf.ByteString
          getDocumentTypeBytes() {
        java.lang.Object ref = documentType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          documentType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string document_type = 1 [json_name = "documentType"];</code>
       * @param value The documentType to set.
       * @return This builder for chaining.
       */
      public Builder setDocumentType(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        documentType_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string document_type = 1 [json_name = "documentType"];</code>
       * @return This builder for chaining.
       */
      public Builder clearDocumentType() {
        documentType_ = getDefaultInstance().getDocumentType();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string document_type = 1 [json_name = "documentType"];</code>
       * @param value The bytes for documentType to set.
       * @return This builder for chaining.
       */
      public Builder setDocumentTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        documentType_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object countryCode_ = "";
      /**
       * <code>string country_code = 2 [json_name = "countryCode"];</code>
       * @return The countryCode.
       */
      public java.lang.String getCountryCode() {
        java.lang.Object ref = countryCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          countryCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string country_code = 2 [json_name = "countryCode"];</code>
       * @return The bytes for countryCode.
       */
      public com.google.protobuf.ByteString
          getCountryCodeBytes() {
        java.lang.Object ref = countryCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          countryCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string country_code = 2 [json_name = "countryCode"];</code>
       * @param value The countryCode to set.
       * @return This builder for chaining.
       */
      public Builder setCountryCode(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        countryCode_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string country_code = 2 [json_name = "countryCode"];</code>
       * @return This builder for chaining.
       */
      public Builder clearCountryCode() {
        countryCode_ = getDefaultInstance().getCountryCode();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string country_code = 2 [json_name = "countryCode"];</code>
       * @param value The bytes for countryCode to set.
       * @return This builder for chaining.
       */
      public Builder setCountryCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        countryCode_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object documentNumber_ = "";
      /**
       * <code>string document_number = 3 [json_name = "documentNumber"];</code>
       * @return The documentNumber.
       */
      public java.lang.String getDocumentNumber() {
        java.lang.Object ref = documentNumber_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          documentNumber_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string document_number = 3 [json_name = "documentNumber"];</code>
       * @return The bytes for documentNumber.
       */
      public com.google.protobuf.ByteString
          getDocumentNumberBytes() {
        java.lang.Object ref = documentNumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          documentNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string document_number = 3 [json_name = "documentNumber"];</code>
       * @param value The documentNumber to set.
       * @return This builder for chaining.
       */
      public Builder setDocumentNumber(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        documentNumber_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string document_number = 3 [json_name = "documentNumber"];</code>
       * @return This builder for chaining.
       */
      public Builder clearDocumentNumber() {
        documentNumber_ = getDefaultInstance().getDocumentNumber();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string document_number = 3 [json_name = "documentNumber"];</code>
       * @param value The bytes for documentNumber to set.
       * @return This builder for chaining.
       */
      public Builder setDocumentNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        documentNumber_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object birthdate_ = "";
      /**
       * <code>string birthdate = 4 [json_name = "birthdate"];</code>
       * @return The birthdate.
       */
      public java.lang.String getBirthdate() {
        java.lang.Object ref = birthdate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          birthdate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string birthdate = 4 [json_name = "birthdate"];</code>
       * @return The bytes for birthdate.
       */
      public com.google.protobuf.ByteString
          getBirthdateBytes() {
        java.lang.Object ref = birthdate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          birthdate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string birthdate = 4 [json_name = "birthdate"];</code>
       * @param value The birthdate to set.
       * @return This builder for chaining.
       */
      public Builder setBirthdate(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        birthdate_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string birthdate = 4 [json_name = "birthdate"];</code>
       * @return This builder for chaining.
       */
      public Builder clearBirthdate() {
        birthdate_ = getDefaultInstance().getBirthdate();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string birthdate = 4 [json_name = "birthdate"];</code>
       * @param value The bytes for birthdate to set.
       * @return This builder for chaining.
       */
      public Builder setBirthdateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        birthdate_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object sex_ = "";
      /**
       * <code>string sex = 5 [json_name = "sex"];</code>
       * @return The sex.
       */
      public java.lang.String getSex() {
        java.lang.Object ref = sex_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sex_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sex = 5 [json_name = "sex"];</code>
       * @return The bytes for sex.
       */
      public com.google.protobuf.ByteString
          getSexBytes() {
        java.lang.Object ref = sex_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sex_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sex = 5 [json_name = "sex"];</code>
       * @param value The sex to set.
       * @return This builder for chaining.
       */
      public Builder setSex(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        sex_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string sex = 5 [json_name = "sex"];</code>
       * @return This builder for chaining.
       */
      public Builder clearSex() {
        sex_ = getDefaultInstance().getSex();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string sex = 5 [json_name = "sex"];</code>
       * @param value The bytes for sex to set.
       * @return This builder for chaining.
       */
      public Builder setSexBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        sex_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private java.lang.Object expiryDate_ = "";
      /**
       * <code>string expiry_date = 6 [json_name = "expiryDate"];</code>
       * @return The expiryDate.
       */
      public java.lang.String getExpiryDate() {
        java.lang.Object ref = expiryDate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          expiryDate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string expiry_date = 6 [json_name = "expiryDate"];</code>
       * @return The bytes for expiryDate.
       */
      public com.google.protobuf.ByteString
          getExpiryDateBytes() {
        java.lang.Object ref = expiryDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          expiryDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string expiry_date = 6 [json_name = "expiryDate"];</code>
       * @param value The expiryDate to set.
       * @return This builder for chaining.
       */
      public Builder setExpiryDate(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        expiryDate_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>string expiry_date = 6 [json_name = "expiryDate"];</code>
       * @return This builder for chaining.
       */
      public Builder clearExpiryDate() {
        expiryDate_ = getDefaultInstance().getExpiryDate();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>string expiry_date = 6 [json_name = "expiryDate"];</code>
       * @param value The bytes for expiryDate to set.
       * @return This builder for chaining.
       */
      public Builder setExpiryDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        expiryDate_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private java.lang.Object nationality_ = "";
      /**
       * <code>string nationality = 7 [json_name = "nationality"];</code>
       * @return The nationality.
       */
      public java.lang.String getNationality() {
        java.lang.Object ref = nationality_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nationality_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nationality = 7 [json_name = "nationality"];</code>
       * @return The bytes for nationality.
       */
      public com.google.protobuf.ByteString
          getNationalityBytes() {
        java.lang.Object ref = nationality_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nationality_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nationality = 7 [json_name = "nationality"];</code>
       * @param value The nationality to set.
       * @return This builder for chaining.
       */
      public Builder setNationality(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        nationality_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>string nationality = 7 [json_name = "nationality"];</code>
       * @return This builder for chaining.
       */
      public Builder clearNationality() {
        nationality_ = getDefaultInstance().getNationality();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <code>string nationality = 7 [json_name = "nationality"];</code>
       * @param value The bytes for nationality to set.
       * @return This builder for chaining.
       */
      public Builder setNationalityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        nationality_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }

      private java.lang.Object finalCheckDigit_ = "";
      /**
       * <code>string final_check_digit = 8 [json_name = "finalCheckDigit"];</code>
       * @return The finalCheckDigit.
       */
      public java.lang.String getFinalCheckDigit() {
        java.lang.Object ref = finalCheckDigit_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          finalCheckDigit_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string final_check_digit = 8 [json_name = "finalCheckDigit"];</code>
       * @return The bytes for finalCheckDigit.
       */
      public com.google.protobuf.ByteString
          getFinalCheckDigitBytes() {
        java.lang.Object ref = finalCheckDigit_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          finalCheckDigit_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string final_check_digit = 8 [json_name = "finalCheckDigit"];</code>
       * @param value The finalCheckDigit to set.
       * @return This builder for chaining.
       */
      public Builder setFinalCheckDigit(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        finalCheckDigit_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>string final_check_digit = 8 [json_name = "finalCheckDigit"];</code>
       * @return This builder for chaining.
       */
      public Builder clearFinalCheckDigit() {
        finalCheckDigit_ = getDefaultInstance().getFinalCheckDigit();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }
      /**
       * <code>string final_check_digit = 8 [json_name = "finalCheckDigit"];</code>
       * @param value The bytes for finalCheckDigit to set.
       * @return This builder for chaining.
       */
      public Builder setFinalCheckDigitBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        finalCheckDigit_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 9 [json_name = "name"];</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 9 [json_name = "name"];</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 9 [json_name = "name"];</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 9 [json_name = "name"];</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000100);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 9 [json_name = "name"];</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }

      private java.lang.Object surname_ = "";
      /**
       * <code>string surname = 10 [json_name = "surname"];</code>
       * @return The surname.
       */
      public java.lang.String getSurname() {
        java.lang.Object ref = surname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          surname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string surname = 10 [json_name = "surname"];</code>
       * @return The bytes for surname.
       */
      public com.google.protobuf.ByteString
          getSurnameBytes() {
        java.lang.Object ref = surname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          surname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string surname = 10 [json_name = "surname"];</code>
       * @param value The surname to set.
       * @return This builder for chaining.
       */
      public Builder setSurname(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        surname_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }
      /**
       * <code>string surname = 10 [json_name = "surname"];</code>
       * @return This builder for chaining.
       */
      public Builder clearSurname() {
        surname_ = getDefaultInstance().getSurname();
        bitField0_ = (bitField0_ & ~0x00000200);
        onChanged();
        return this;
      }
      /**
       * <code>string surname = 10 [json_name = "surname"];</code>
       * @param value The bytes for surname to set.
       * @return This builder for chaining.
       */
      public Builder setSurnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        surname_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }

      private java.lang.Object givenName_ = "";
      /**
       * <code>string given_name = 11 [json_name = "givenName"];</code>
       * @return The givenName.
       */
      public java.lang.String getGivenName() {
        java.lang.Object ref = givenName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          givenName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string given_name = 11 [json_name = "givenName"];</code>
       * @return The bytes for givenName.
       */
      public com.google.protobuf.ByteString
          getGivenNameBytes() {
        java.lang.Object ref = givenName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          givenName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string given_name = 11 [json_name = "givenName"];</code>
       * @param value The givenName to set.
       * @return This builder for chaining.
       */
      public Builder setGivenName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        givenName_ = value;
        bitField0_ |= 0x00000400;
        onChanged();
        return this;
      }
      /**
       * <code>string given_name = 11 [json_name = "givenName"];</code>
       * @return This builder for chaining.
       */
      public Builder clearGivenName() {
        givenName_ = getDefaultInstance().getGivenName();
        bitField0_ = (bitField0_ & ~0x00000400);
        onChanged();
        return this;
      }
      /**
       * <code>string given_name = 11 [json_name = "givenName"];</code>
       * @param value The bytes for givenName to set.
       * @return This builder for chaining.
       */
      public Builder setGivenNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        givenName_ = value;
        bitField0_ |= 0x00000400;
        onChanged();
        return this;
      }

      private java.lang.Object optionalData1_ = "";
      /**
       * <code>string optional_data1 = 12 [json_name = "optionalData1"];</code>
       * @return The optionalData1.
       */
      public java.lang.String getOptionalData1() {
        java.lang.Object ref = optionalData1_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          optionalData1_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string optional_data1 = 12 [json_name = "optionalData1"];</code>
       * @return The bytes for optionalData1.
       */
      public com.google.protobuf.ByteString
          getOptionalData1Bytes() {
        java.lang.Object ref = optionalData1_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          optionalData1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string optional_data1 = 12 [json_name = "optionalData1"];</code>
       * @param value The optionalData1 to set.
       * @return This builder for chaining.
       */
      public Builder setOptionalData1(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        optionalData1_ = value;
        bitField0_ |= 0x00000800;
        onChanged();
        return this;
      }
      /**
       * <code>string optional_data1 = 12 [json_name = "optionalData1"];</code>
       * @return This builder for chaining.
       */
      public Builder clearOptionalData1() {
        optionalData1_ = getDefaultInstance().getOptionalData1();
        bitField0_ = (bitField0_ & ~0x00000800);
        onChanged();
        return this;
      }
      /**
       * <code>string optional_data1 = 12 [json_name = "optionalData1"];</code>
       * @param value The bytes for optionalData1 to set.
       * @return This builder for chaining.
       */
      public Builder setOptionalData1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        optionalData1_ = value;
        bitField0_ |= 0x00000800;
        onChanged();
        return this;
      }

      private java.lang.Object optionalData2_ = "";
      /**
       * <code>string optional_data2 = 13 [json_name = "optionalData2"];</code>
       * @return The optionalData2.
       */
      public java.lang.String getOptionalData2() {
        java.lang.Object ref = optionalData2_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          optionalData2_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string optional_data2 = 13 [json_name = "optionalData2"];</code>
       * @return The bytes for optionalData2.
       */
      public com.google.protobuf.ByteString
          getOptionalData2Bytes() {
        java.lang.Object ref = optionalData2_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          optionalData2_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string optional_data2 = 13 [json_name = "optionalData2"];</code>
       * @param value The optionalData2 to set.
       * @return This builder for chaining.
       */
      public Builder setOptionalData2(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        optionalData2_ = value;
        bitField0_ |= 0x00001000;
        onChanged();
        return this;
      }
      /**
       * <code>string optional_data2 = 13 [json_name = "optionalData2"];</code>
       * @return This builder for chaining.
       */
      public Builder clearOptionalData2() {
        optionalData2_ = getDefaultInstance().getOptionalData2();
        bitField0_ = (bitField0_ & ~0x00001000);
        onChanged();
        return this;
      }
      /**
       * <code>string optional_data2 = 13 [json_name = "optionalData2"];</code>
       * @param value The bytes for optionalData2 to set.
       * @return This builder for chaining.
       */
      public Builder setOptionalData2Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        optionalData2_ = value;
        bitField0_ |= 0x00001000;
        onChanged();
        return this;
      }

      private boolean isVisa_ ;
      /**
       * <pre>
       * is_visa - true for VISAs' MRZ
       * </pre>
       *
       * <code>bool is_visa = 14 [json_name = "isVisa"];</code>
       * @return The isVisa.
       */
      @java.lang.Override
      public boolean getIsVisa() {
        return isVisa_;
      }
      /**
       * <pre>
       * is_visa - true for VISAs' MRZ
       * </pre>
       *
       * <code>bool is_visa = 14 [json_name = "isVisa"];</code>
       * @param value The isVisa to set.
       * @return This builder for chaining.
       */
      public Builder setIsVisa(boolean value) {

        isVisa_ = value;
        bitField0_ |= 0x00002000;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * is_visa - true for VISAs' MRZ
       * </pre>
       *
       * <code>bool is_visa = 14 [json_name = "isVisa"];</code>
       * @return This builder for chaining.
       */
      public Builder clearIsVisa() {
        bitField0_ = (bitField0_ & ~0x00002000);
        isVisa_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.ddx.v1.MrzFields)
    }

    // @@protoc_insertion_point(class_scope:proto.ddx.v1.MrzFields)
    private static final proto.ddx.v1.Mrz.MrzFields DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.ddx.v1.Mrz.MrzFields();
    }

    public static proto.ddx.v1.Mrz.MrzFields getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MrzFields>
        PARSER = new com.google.protobuf.AbstractParser<MrzFields>() {
      @java.lang.Override
      public MrzFields parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MrzFields> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MrzFields> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.ddx.v1.Mrz.MrzFields getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ddx_v1_MrzFields_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_ddx_v1_MrzFields_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026proto/ddx/v1/mrz.proto\022\014proto.ddx.v1\"\317" +
      "\003\n\tMrzFields\022#\n\rdocument_type\030\001 \001(\tR\014doc" +
      "umentType\022!\n\014country_code\030\002 \001(\tR\013country" +
      "Code\022\'\n\017document_number\030\003 \001(\tR\016documentN" +
      "umber\022\034\n\tbirthdate\030\004 \001(\tR\tbirthdate\022\020\n\003s" +
      "ex\030\005 \001(\tR\003sex\022\037\n\013expiry_date\030\006 \001(\tR\nexpi" +
      "ryDate\022 \n\013nationality\030\007 \001(\tR\013nationality" +
      "\022*\n\021final_check_digit\030\010 \001(\tR\017finalCheckD" +
      "igit\022\022\n\004name\030\t \001(\tR\004name\022\030\n\007surname\030\n \001(" +
      "\tR\007surname\022\035\n\ngiven_name\030\013 \001(\tR\tgivenNam" +
      "e\022%\n\016optional_data1\030\014 \001(\tR\roptionalData1" +
      "\022%\n\016optional_data2\030\r \001(\tR\roptionalData2\022" +
      "\027\n\007is_visa\030\016 \001(\010R\006isVisaB4Z2github.com/v" +
      "eridil/id-extract-service/proto/ddx/v1b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_proto_ddx_v1_MrzFields_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_ddx_v1_MrzFields_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_ddx_v1_MrzFields_descriptor,
        new java.lang.String[] { "DocumentType", "CountryCode", "DocumentNumber", "Birthdate", "Sex", "ExpiryDate", "Nationality", "FinalCheckDigit", "Name", "Surname", "GivenName", "OptionalData1", "OptionalData2", "IsVisa", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
