// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/ddx/v1/territory_enum.proto
// Protobuf Java Version: 4.28.2

package proto.ddx.v1;

public final class TerritoryEnum {
  private TerritoryEnum() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      TerritoryEnum.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * Territory - enumeration of supported regions.
   * </pre>
   *
   * Protobuf enum {@code proto.ddx.v1.Territory}
   */
  public enum Territory
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * Undefined
     * </pre>
     *
     * <code>TERRITORY_NOT_AVAILABLE = 0;</code>
     */
    TERRITORY_NOT_AVAILABLE(0),
    /**
     * <pre>
     * Australian Capital Territory in Australia
     * </pre>
     *
     * <code>TERRITORY_AUSTRALIA_AUSTRALIAN_CAPITAL_TERRITORY = 1;</code>
     */
    TERRITORY_AUSTRALIA_AUSTRALIAN_CAPITAL_TERRITORY(1),
    /**
     * <pre>
     * New South Wales in Australia
     * </pre>
     *
     * <code>TERRITORY_AUSTRALIA_NEW_SOUTH_WALES = 2;</code>
     */
    TERRITORY_AUSTRALIA_NEW_SOUTH_WALES(2),
    /**
     * <pre>
     * Northern Territory in Australia
     * </pre>
     *
     * <code>TERRITORY_AUSTRALIA_NORTHERN_TERRITORY = 3;</code>
     */
    TERRITORY_AUSTRALIA_NORTHERN_TERRITORY(3),
    /**
     * <pre>
     * Queensland in Australia
     * </pre>
     *
     * <code>TERRITORY_AUSTRALIA_QUEENSLAND = 4;</code>
     */
    TERRITORY_AUSTRALIA_QUEENSLAND(4),
    /**
     * <pre>
     * South Australia in Australia
     * </pre>
     *
     * <code>TERRITORY_AUSTRALIA_SOUTH_AUSTRALIA = 5;</code>
     */
    TERRITORY_AUSTRALIA_SOUTH_AUSTRALIA(5),
    /**
     * <pre>
     * Tasmania in Australia
     * </pre>
     *
     * <code>TERRITORY_AUSTRALIA_TASMANIA = 6;</code>
     */
    TERRITORY_AUSTRALIA_TASMANIA(6),
    /**
     * <pre>
     * Victoria in Australia
     * </pre>
     *
     * <code>TERRITORY_AUSTRALIA_VICTORIA = 7;</code>
     */
    TERRITORY_AUSTRALIA_VICTORIA(7),
    /**
     * <pre>
     * Western Australia in Australia
     * </pre>
     *
     * <code>TERRITORY_AUSTRALIA_WESTERN_AUSTRALIA = 8;</code>
     */
    TERRITORY_AUSTRALIA_WESTERN_AUSTRALIA(8),
    /**
     * <pre>
     * Alagoas in Brazil
     * </pre>
     *
     * <code>TERRITORY_BRAZIL_ALAGOAS = 9;</code>
     */
    TERRITORY_BRAZIL_ALAGOAS(9),
    /**
     * <pre>
     * Ceara in Brazil
     * </pre>
     *
     * <code>TERRITORY_BRAZIL_CEARA = 10;</code>
     */
    TERRITORY_BRAZIL_CEARA(10),
    /**
     * <pre>
     * Distrito Federal in Brazil
     * </pre>
     *
     * <code>TERRITORY_BRAZIL_DISTRITO_FEDERAL = 11;</code>
     */
    TERRITORY_BRAZIL_DISTRITO_FEDERAL(11),
    /**
     * <pre>
     * Goias in Brazil
     * </pre>
     *
     * <code>TERRITORY_BRAZIL_GOIAS = 12;</code>
     */
    TERRITORY_BRAZIL_GOIAS(12),
    /**
     * <pre>
     * Maranhao in Brazil
     * </pre>
     *
     * <code>TERRITORY_BRAZIL_MARANHAO = 13;</code>
     */
    TERRITORY_BRAZIL_MARANHAO(13),
    /**
     * <pre>
     * Mato Grosso in Brazil
     * </pre>
     *
     * <code>TERRITORY_BRAZIL_MATO_GROSSO = 14;</code>
     */
    TERRITORY_BRAZIL_MATO_GROSSO(14),
    /**
     * <pre>
     * Minas Gerais in Brazil
     * </pre>
     *
     * <code>TERRITORY_BRAZIL_MINAS_GERAIS = 15;</code>
     */
    TERRITORY_BRAZIL_MINAS_GERAIS(15),
    /**
     * <pre>
     * Para in Brazil
     * </pre>
     *
     * <code>TERRITORY_BRAZIL_PARA = 16;</code>
     */
    TERRITORY_BRAZIL_PARA(16),
    /**
     * <pre>
     * Parana in Brazil
     * </pre>
     *
     * <code>TERRITORY_BRAZIL_PARANA = 17;</code>
     */
    TERRITORY_BRAZIL_PARANA(17),
    /**
     * <pre>
     * Pernambuco in Brazil
     * </pre>
     *
     * <code>TERRITORY_BRAZIL_PERNAMBUCO = 18;</code>
     */
    TERRITORY_BRAZIL_PERNAMBUCO(18),
    /**
     * <pre>
     * Rio De Janeiro in Brazil
     * </pre>
     *
     * <code>TERRITORY_BRAZIL_RIO_DE_JANEIRO = 19;</code>
     */
    TERRITORY_BRAZIL_RIO_DE_JANEIRO(19),
    /**
     * <pre>
     * Rio Grande Do Sul in Brazil
     * </pre>
     *
     * <code>TERRITORY_BRAZIL_RIO_GRANDE_DO_SUL = 20;</code>
     */
    TERRITORY_BRAZIL_RIO_GRANDE_DO_SUL(20),
    /**
     * <pre>
     * Santa Catarina in Brazil
     * </pre>
     *
     * <code>TERRITORY_BRAZIL_SANTA_CATARINA = 21;</code>
     */
    TERRITORY_BRAZIL_SANTA_CATARINA(21),
    /**
     * <pre>
     * Sao Paolo in Brazil
     * </pre>
     *
     * <code>TERRITORY_BRAZIL_SAO_PAOLO = 22;</code>
     */
    TERRITORY_BRAZIL_SAO_PAOLO(22),
    /**
     * <pre>
     * Sergipe in Brazil
     * </pre>
     *
     * <code>TERRITORY_BRAZIL_SERGIPE = 23;</code>
     */
    TERRITORY_BRAZIL_SERGIPE(23),
    /**
     * <pre>
     * Alberta in Canada
     * </pre>
     *
     * <code>TERRITORY_CANADA_ALBERTA = 24;</code>
     */
    TERRITORY_CANADA_ALBERTA(24),
    /**
     * <pre>
     * British Columbia in Canada
     * </pre>
     *
     * <code>TERRITORY_CANADA_BRITISH_COLUMBIA = 25;</code>
     */
    TERRITORY_CANADA_BRITISH_COLUMBIA(25),
    /**
     * <pre>
     * Manitoba in Canada
     * </pre>
     *
     * <code>TERRITORY_CANADA_MANITOBA = 26;</code>
     */
    TERRITORY_CANADA_MANITOBA(26),
    /**
     * <pre>
     * New Brunswick in Canada
     * </pre>
     *
     * <code>TERRITORY_CANADA_NEW_BRUNSWICK = 27;</code>
     */
    TERRITORY_CANADA_NEW_BRUNSWICK(27),
    /**
     * <pre>
     * Newfoundland And Labrador in Canada
     * </pre>
     *
     * <code>TERRITORY_CANADA_NEWFOUNDLAND_AND_LABRADOR = 28;</code>
     */
    TERRITORY_CANADA_NEWFOUNDLAND_AND_LABRADOR(28),
    /**
     * <pre>
     * Northwest Territories in Canada
     * </pre>
     *
     * <code>TERRITORY_CANADA_NORTHWEST_TERRITORIES = 29;</code>
     */
    TERRITORY_CANADA_NORTHWEST_TERRITORIES(29),
    /**
     * <pre>
     * Nova Scotia in Canada
     * </pre>
     *
     * <code>TERRITORY_CANADA_NOVA_SCOTIA = 30;</code>
     */
    TERRITORY_CANADA_NOVA_SCOTIA(30),
    /**
     * <pre>
     * Nunavut in Canada
     * </pre>
     *
     * <code>TERRITORY_CANADA_NUNAVUT = 31;</code>
     */
    TERRITORY_CANADA_NUNAVUT(31),
    /**
     * <pre>
     * Ontario in Canada
     * </pre>
     *
     * <code>TERRITORY_CANADA_ONTARIO = 32;</code>
     */
    TERRITORY_CANADA_ONTARIO(32),
    /**
     * <pre>
     * Prince Edward Island in Canada
     * </pre>
     *
     * <code>TERRITORY_CANADA_PRINCE_EDWARD_ISLAND = 33;</code>
     */
    TERRITORY_CANADA_PRINCE_EDWARD_ISLAND(33),
    /**
     * <pre>
     * Quebec in Canada
     * </pre>
     *
     * <code>TERRITORY_CANADA_QUEBEC = 34;</code>
     */
    TERRITORY_CANADA_QUEBEC(34),
    /**
     * <pre>
     * Saskatchewan in Canada
     * </pre>
     *
     * <code>TERRITORY_CANADA_SASKATCHEWAN = 35;</code>
     */
    TERRITORY_CANADA_SASKATCHEWAN(35),
    /**
     * <pre>
     * Yukon in Canada
     * </pre>
     *
     * <code>TERRITORY_CANADA_YUKON = 36;</code>
     */
    TERRITORY_CANADA_YUKON(36),
    /**
     * <pre>
     * Andhra Pradesh in India
     * </pre>
     *
     * <code>TERRITORY_INDIA_ANDHRA_PRADESH = 37;</code>
     */
    TERRITORY_INDIA_ANDHRA_PRADESH(37),
    /**
     * <pre>
     * Gujarat in India
     * </pre>
     *
     * <code>TERRITORY_INDIA_GUJARAT = 38;</code>
     */
    TERRITORY_INDIA_GUJARAT(38),
    /**
     * <pre>
     * Haryana in India
     * </pre>
     *
     * <code>TERRITORY_INDIA_HARYANA = 39;</code>
     */
    TERRITORY_INDIA_HARYANA(39),
    /**
     * <pre>
     * Karnataka in India
     * </pre>
     *
     * <code>TERRITORY_INDIA_KARNATAKA = 40;</code>
     */
    TERRITORY_INDIA_KARNATAKA(40),
    /**
     * <pre>
     * Kerala in India
     * </pre>
     *
     * <code>TERRITORY_INDIA_KERALA = 41;</code>
     */
    TERRITORY_INDIA_KERALA(41),
    /**
     * <pre>
     * Madhya Pradesh in India
     * </pre>
     *
     * <code>TERRITORY_INDIA_MADHYA_PRADESH = 42;</code>
     */
    TERRITORY_INDIA_MADHYA_PRADESH(42),
    /**
     * <pre>
     * Maharashtra in India
     * </pre>
     *
     * <code>TERRITORY_INDIA_MAHARASHTRA = 43;</code>
     */
    TERRITORY_INDIA_MAHARASHTRA(43),
    /**
     * <pre>
     * Punjab in India
     * </pre>
     *
     * <code>TERRITORY_INDIA_PUNJAB = 44;</code>
     */
    TERRITORY_INDIA_PUNJAB(44),
    /**
     * <pre>
     * Tamil Nadu in India
     * </pre>
     *
     * <code>TERRITORY_INDIA_TAMIL_NADU = 45;</code>
     */
    TERRITORY_INDIA_TAMIL_NADU(45),
    /**
     * <pre>
     * Aguascalientes in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_AGUASCALIENTES = 46;</code>
     */
    TERRITORY_MEXICO_AGUASCALIENTES(46),
    /**
     * <pre>
     * Baja California in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_BAJA_CALIFORNIA = 47;</code>
     */
    TERRITORY_MEXICO_BAJA_CALIFORNIA(47),
    /**
     * <pre>
     * Baja California Sur in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_BAJA_CALIFORNIA_SUR = 48;</code>
     */
    TERRITORY_MEXICO_BAJA_CALIFORNIA_SUR(48),
    /**
     * <pre>
     * Campeche in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_CAMPECHE = 49;</code>
     */
    TERRITORY_MEXICO_CAMPECHE(49),
    /**
     * <pre>
     * Chiapas in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_CHIAPAS = 50;</code>
     */
    TERRITORY_MEXICO_CHIAPAS(50),
    /**
     * <pre>
     * Chihuahua in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_CHIHUAHUA = 51;</code>
     */
    TERRITORY_MEXICO_CHIHUAHUA(51),
    /**
     * <pre>
     * Ciudad De Mexico in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_CIUDAD_DE_MEXICO = 52;</code>
     */
    TERRITORY_MEXICO_CIUDAD_DE_MEXICO(52),
    /**
     * <pre>
     * Coahuila in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_COAHUILA = 53;</code>
     */
    TERRITORY_MEXICO_COAHUILA(53),
    /**
     * <pre>
     * Colima in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_COLIMA = 54;</code>
     */
    TERRITORY_MEXICO_COLIMA(54),
    /**
     * <pre>
     * Durango in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_DURANGO = 55;</code>
     */
    TERRITORY_MEXICO_DURANGO(55),
    /**
     * <pre>
     * Guanajuato in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_GUANAJUATO = 56;</code>
     */
    TERRITORY_MEXICO_GUANAJUATO(56),
    /**
     * <pre>
     * Guerrero in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_GUERRERO = 57;</code>
     */
    TERRITORY_MEXICO_GUERRERO(57),
    /**
     * <pre>
     * Hidalgo in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_HIDALGO = 58;</code>
     */
    TERRITORY_MEXICO_HIDALGO(58),
    /**
     * <pre>
     * Jalisco in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_JALISCO = 59;</code>
     */
    TERRITORY_MEXICO_JALISCO(59),
    /**
     * <pre>
     * Mexico in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_MEXICO = 60;</code>
     */
    TERRITORY_MEXICO_MEXICO(60),
    /**
     * <pre>
     * Michoacan in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_MICHOACAN = 61;</code>
     */
    TERRITORY_MEXICO_MICHOACAN(61),
    /**
     * <pre>
     * Morelos in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_MORELOS = 62;</code>
     */
    TERRITORY_MEXICO_MORELOS(62),
    /**
     * <pre>
     * Nayarit in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_NAYARIT = 63;</code>
     */
    TERRITORY_MEXICO_NAYARIT(63),
    /**
     * <pre>
     * Nuevo Leon in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_NUEVO_LEON = 64;</code>
     */
    TERRITORY_MEXICO_NUEVO_LEON(64),
    /**
     * <pre>
     * Oaxaca in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_OAXACA = 65;</code>
     */
    TERRITORY_MEXICO_OAXACA(65),
    /**
     * <pre>
     * Puebla in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_PUEBLA = 66;</code>
     */
    TERRITORY_MEXICO_PUEBLA(66),
    /**
     * <pre>
     * Queretaro in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_QUERETARO = 67;</code>
     */
    TERRITORY_MEXICO_QUERETARO(67),
    /**
     * <pre>
     * Quintana Roo in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_QUINTANA_ROO = 68;</code>
     */
    TERRITORY_MEXICO_QUINTANA_ROO(68),
    /**
     * <pre>
     * San Luis Potosi in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_SAN_LUIS_POTOSI = 69;</code>
     */
    TERRITORY_MEXICO_SAN_LUIS_POTOSI(69),
    /**
     * <pre>
     * Sinaloa in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_SINALOA = 70;</code>
     */
    TERRITORY_MEXICO_SINALOA(70),
    /**
     * <pre>
     * Sonora in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_SONORA = 71;</code>
     */
    TERRITORY_MEXICO_SONORA(71),
    /**
     * <pre>
     * Tabasco in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_TABASCO = 72;</code>
     */
    TERRITORY_MEXICO_TABASCO(72),
    /**
     * <pre>
     * Tamaulipas in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_TAMAULIPAS = 73;</code>
     */
    TERRITORY_MEXICO_TAMAULIPAS(73),
    /**
     * <pre>
     * Tlaxcala in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_TLAXCALA = 74;</code>
     */
    TERRITORY_MEXICO_TLAXCALA(74),
    /**
     * <pre>
     * Veracruz in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_VERACRUZ = 75;</code>
     */
    TERRITORY_MEXICO_VERACRUZ(75),
    /**
     * <pre>
     * Yucatan in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_YUCATAN = 76;</code>
     */
    TERRITORY_MEXICO_YUCATAN(76),
    /**
     * <pre>
     * Zacatecas in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_ZACATECAS = 77;</code>
     */
    TERRITORY_MEXICO_ZACATECAS(77),
    /**
     * <pre>
     * Khyber Pakhtunkhwa in Pakistan
     * </pre>
     *
     * <code>TERRITORY_PAKISTAN_KHYBER_PAKHTUNKHWA = 78;</code>
     */
    TERRITORY_PAKISTAN_KHYBER_PAKHTUNKHWA(78),
    /**
     * <pre>
     * Punjab in Pakistan
     * </pre>
     *
     * <code>TERRITORY_PAKISTAN_PUNJAB = 79;</code>
     */
    TERRITORY_PAKISTAN_PUNJAB(79),
    /**
     * <pre>
     * Alabama in USA
     * </pre>
     *
     * <code>TERRITORY_USA_ALABAMA = 80;</code>
     */
    TERRITORY_USA_ALABAMA(80),
    /**
     * <pre>
     * Alaska in USA
     * </pre>
     *
     * <code>TERRITORY_USA_ALASKA = 81;</code>
     */
    TERRITORY_USA_ALASKA(81),
    /**
     * <pre>
     * Arizona in USA
     * </pre>
     *
     * <code>TERRITORY_USA_ARIZONA = 82;</code>
     */
    TERRITORY_USA_ARIZONA(82),
    /**
     * <pre>
     * Arkansas in USA
     * </pre>
     *
     * <code>TERRITORY_USA_ARKANSAS = 83;</code>
     */
    TERRITORY_USA_ARKANSAS(83),
    /**
     * <pre>
     * California in USA
     * </pre>
     *
     * <code>TERRITORY_USA_CALIFORNIA = 84;</code>
     */
    TERRITORY_USA_CALIFORNIA(84),
    /**
     * <pre>
     * Colorado in USA
     * </pre>
     *
     * <code>TERRITORY_USA_COLORADO = 85;</code>
     */
    TERRITORY_USA_COLORADO(85),
    /**
     * <pre>
     * Connecticut in USA
     * </pre>
     *
     * <code>TERRITORY_USA_CONNECTICUT = 86;</code>
     */
    TERRITORY_USA_CONNECTICUT(86),
    /**
     * <pre>
     * Delaware in USA
     * </pre>
     *
     * <code>TERRITORY_USA_DELAWARE = 87;</code>
     */
    TERRITORY_USA_DELAWARE(87),
    /**
     * <pre>
     * District Of Columbia in USA
     * </pre>
     *
     * <code>TERRITORY_USA_DISTRICT_OF_COLUMBIA = 88;</code>
     */
    TERRITORY_USA_DISTRICT_OF_COLUMBIA(88),
    /**
     * <pre>
     * Florida in USA
     * </pre>
     *
     * <code>TERRITORY_USA_FLORIDA = 89;</code>
     */
    TERRITORY_USA_FLORIDA(89),
    /**
     * <pre>
     * Georgia in USA
     * </pre>
     *
     * <code>TERRITORY_USA_GEORGIA = 90;</code>
     */
    TERRITORY_USA_GEORGIA(90),
    /**
     * <pre>
     * Hawaii in USA
     * </pre>
     *
     * <code>TERRITORY_USA_HAWAII = 91;</code>
     */
    TERRITORY_USA_HAWAII(91),
    /**
     * <pre>
     * Idaho in USA
     * </pre>
     *
     * <code>TERRITORY_USA_IDAHO = 92;</code>
     */
    TERRITORY_USA_IDAHO(92),
    /**
     * <pre>
     * Illinois in USA
     * </pre>
     *
     * <code>TERRITORY_USA_ILLINOIS = 93;</code>
     */
    TERRITORY_USA_ILLINOIS(93),
    /**
     * <pre>
     * Indiana in USA
     * </pre>
     *
     * <code>TERRITORY_USA_INDIANA = 94;</code>
     */
    TERRITORY_USA_INDIANA(94),
    /**
     * <pre>
     * Iowa in USA
     * </pre>
     *
     * <code>TERRITORY_USA_IOWA = 95;</code>
     */
    TERRITORY_USA_IOWA(95),
    /**
     * <pre>
     * Kansas in USA
     * </pre>
     *
     * <code>TERRITORY_USA_KANSAS = 96;</code>
     */
    TERRITORY_USA_KANSAS(96),
    /**
     * <pre>
     * Kentucky in USA
     * </pre>
     *
     * <code>TERRITORY_USA_KENTUCKY = 97;</code>
     */
    TERRITORY_USA_KENTUCKY(97),
    /**
     * <pre>
     * Louisiana in USA
     * </pre>
     *
     * <code>TERRITORY_USA_LOUISIANA = 98;</code>
     */
    TERRITORY_USA_LOUISIANA(98),
    /**
     * <pre>
     * Maine in USA
     * </pre>
     *
     * <code>TERRITORY_USA_MAINE = 99;</code>
     */
    TERRITORY_USA_MAINE(99),
    /**
     * <pre>
     * Maryland in USA
     * </pre>
     *
     * <code>TERRITORY_USA_MARYLAND = 100;</code>
     */
    TERRITORY_USA_MARYLAND(100),
    /**
     * <pre>
     * Massachusetts in USA
     * </pre>
     *
     * <code>TERRITORY_USA_MASSACHUSETTS = 101;</code>
     */
    TERRITORY_USA_MASSACHUSETTS(101),
    /**
     * <pre>
     * Michigan in USA
     * </pre>
     *
     * <code>TERRITORY_USA_MICHIGAN = 102;</code>
     */
    TERRITORY_USA_MICHIGAN(102),
    /**
     * <pre>
     * Minnesota in USA
     * </pre>
     *
     * <code>TERRITORY_USA_MINNESOTA = 103;</code>
     */
    TERRITORY_USA_MINNESOTA(103),
    /**
     * <pre>
     * Mississippi in USA
     * </pre>
     *
     * <code>TERRITORY_USA_MISSISSIPPI = 104;</code>
     */
    TERRITORY_USA_MISSISSIPPI(104),
    /**
     * <pre>
     * Missouri in USA
     * </pre>
     *
     * <code>TERRITORY_USA_MISSOURI = 105;</code>
     */
    TERRITORY_USA_MISSOURI(105),
    /**
     * <pre>
     * Montana in USA
     * </pre>
     *
     * <code>TERRITORY_USA_MONTANA = 106;</code>
     */
    TERRITORY_USA_MONTANA(106),
    /**
     * <pre>
     * Nebraska in USA
     * </pre>
     *
     * <code>TERRITORY_USA_NEBRASKA = 107;</code>
     */
    TERRITORY_USA_NEBRASKA(107),
    /**
     * <pre>
     * Nevada in USA
     * </pre>
     *
     * <code>TERRITORY_USA_NEVADA = 108;</code>
     */
    TERRITORY_USA_NEVADA(108),
    /**
     * <pre>
     * New Hampshire in USA
     * </pre>
     *
     * <code>TERRITORY_USA_NEW_HAMPSHIRE = 109;</code>
     */
    TERRITORY_USA_NEW_HAMPSHIRE(109),
    /**
     * <pre>
     * New Jersey in USA
     * </pre>
     *
     * <code>TERRITORY_USA_NEW_JERSEY = 110;</code>
     */
    TERRITORY_USA_NEW_JERSEY(110),
    /**
     * <pre>
     * New Mexico in USA
     * </pre>
     *
     * <code>TERRITORY_USA_NEW_MEXICO = 111;</code>
     */
    TERRITORY_USA_NEW_MEXICO(111),
    /**
     * <pre>
     * New York in USA
     * </pre>
     *
     * <code>TERRITORY_USA_NEW_YORK = 112;</code>
     */
    TERRITORY_USA_NEW_YORK(112),
    /**
     * <pre>
     * New York City in USA
     * </pre>
     *
     * <code>TERRITORY_USA_NEW_YORK_CITY = 113;</code>
     */
    TERRITORY_USA_NEW_YORK_CITY(113),
    /**
     * <pre>
     * North Carolina in USA
     * </pre>
     *
     * <code>TERRITORY_USA_NORTH_CAROLINA = 114;</code>
     */
    TERRITORY_USA_NORTH_CAROLINA(114),
    /**
     * <pre>
     * North Dakota in USA
     * </pre>
     *
     * <code>TERRITORY_USA_NORTH_DAKOTA = 115;</code>
     */
    TERRITORY_USA_NORTH_DAKOTA(115),
    /**
     * <pre>
     * Ohio in USA
     * </pre>
     *
     * <code>TERRITORY_USA_OHIO = 116;</code>
     */
    TERRITORY_USA_OHIO(116),
    /**
     * <pre>
     * Oklahoma in USA
     * </pre>
     *
     * <code>TERRITORY_USA_OKLAHOMA = 117;</code>
     */
    TERRITORY_USA_OKLAHOMA(117),
    /**
     * <pre>
     * Oregon in USA
     * </pre>
     *
     * <code>TERRITORY_USA_OREGON = 118;</code>
     */
    TERRITORY_USA_OREGON(118),
    /**
     * <pre>
     * Pennsylvania in USA
     * </pre>
     *
     * <code>TERRITORY_USA_PENNSYLVANIA = 119;</code>
     */
    TERRITORY_USA_PENNSYLVANIA(119),
    /**
     * <pre>
     * Rhode Island in USA
     * </pre>
     *
     * <code>TERRITORY_USA_RHODE_ISLAND = 120;</code>
     */
    TERRITORY_USA_RHODE_ISLAND(120),
    /**
     * <pre>
     * South Carolina in USA
     * </pre>
     *
     * <code>TERRITORY_USA_SOUTH_CAROLINA = 121;</code>
     */
    TERRITORY_USA_SOUTH_CAROLINA(121),
    /**
     * <pre>
     * South Dakota in USA
     * </pre>
     *
     * <code>TERRITORY_USA_SOUTH_DAKOTA = 122;</code>
     */
    TERRITORY_USA_SOUTH_DAKOTA(122),
    /**
     * <pre>
     * Tennessee in USA
     * </pre>
     *
     * <code>TERRITORY_USA_TENNESSEE = 123;</code>
     */
    TERRITORY_USA_TENNESSEE(123),
    /**
     * <pre>
     * Texas in USA
     * </pre>
     *
     * <code>TERRITORY_USA_TEXAS = 124;</code>
     */
    TERRITORY_USA_TEXAS(124),
    /**
     * <pre>
     * Utah in USA
     * </pre>
     *
     * <code>TERRITORY_USA_UTAH = 125;</code>
     */
    TERRITORY_USA_UTAH(125),
    /**
     * <pre>
     * Vermont in USA
     * </pre>
     *
     * <code>TERRITORY_USA_VERMONT = 126;</code>
     */
    TERRITORY_USA_VERMONT(126),
    /**
     * <pre>
     * Virginia in USA
     * </pre>
     *
     * <code>TERRITORY_USA_VIRGINIA = 127;</code>
     */
    TERRITORY_USA_VIRGINIA(127),
    /**
     * <pre>
     * Washington in USA
     * </pre>
     *
     * <code>TERRITORY_USA_WASHINGTON = 128;</code>
     */
    TERRITORY_USA_WASHINGTON(128),
    /**
     * <pre>
     * West Virginia in USA
     * </pre>
     *
     * <code>TERRITORY_USA_WEST_VIRGINIA = 129;</code>
     */
    TERRITORY_USA_WEST_VIRGINIA(129),
    /**
     * <pre>
     * Wisconsin in USA
     * </pre>
     *
     * <code>TERRITORY_USA_WISCONSIN = 130;</code>
     */
    TERRITORY_USA_WISCONSIN(130),
    /**
     * <pre>
     * Wyoming in USA
     * </pre>
     *
     * <code>TERRITORY_USA_WYOMING = 131;</code>
     */
    TERRITORY_USA_WYOMING(131),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 2,
        /* suffix= */ "",
        Territory.class.getName());
    }
    /**
     * <pre>
     * Undefined
     * </pre>
     *
     * <code>TERRITORY_NOT_AVAILABLE = 0;</code>
     */
    public static final int TERRITORY_NOT_AVAILABLE_VALUE = 0;
    /**
     * <pre>
     * Australian Capital Territory in Australia
     * </pre>
     *
     * <code>TERRITORY_AUSTRALIA_AUSTRALIAN_CAPITAL_TERRITORY = 1;</code>
     */
    public static final int TERRITORY_AUSTRALIA_AUSTRALIAN_CAPITAL_TERRITORY_VALUE = 1;
    /**
     * <pre>
     * New South Wales in Australia
     * </pre>
     *
     * <code>TERRITORY_AUSTRALIA_NEW_SOUTH_WALES = 2;</code>
     */
    public static final int TERRITORY_AUSTRALIA_NEW_SOUTH_WALES_VALUE = 2;
    /**
     * <pre>
     * Northern Territory in Australia
     * </pre>
     *
     * <code>TERRITORY_AUSTRALIA_NORTHERN_TERRITORY = 3;</code>
     */
    public static final int TERRITORY_AUSTRALIA_NORTHERN_TERRITORY_VALUE = 3;
    /**
     * <pre>
     * Queensland in Australia
     * </pre>
     *
     * <code>TERRITORY_AUSTRALIA_QUEENSLAND = 4;</code>
     */
    public static final int TERRITORY_AUSTRALIA_QUEENSLAND_VALUE = 4;
    /**
     * <pre>
     * South Australia in Australia
     * </pre>
     *
     * <code>TERRITORY_AUSTRALIA_SOUTH_AUSTRALIA = 5;</code>
     */
    public static final int TERRITORY_AUSTRALIA_SOUTH_AUSTRALIA_VALUE = 5;
    /**
     * <pre>
     * Tasmania in Australia
     * </pre>
     *
     * <code>TERRITORY_AUSTRALIA_TASMANIA = 6;</code>
     */
    public static final int TERRITORY_AUSTRALIA_TASMANIA_VALUE = 6;
    /**
     * <pre>
     * Victoria in Australia
     * </pre>
     *
     * <code>TERRITORY_AUSTRALIA_VICTORIA = 7;</code>
     */
    public static final int TERRITORY_AUSTRALIA_VICTORIA_VALUE = 7;
    /**
     * <pre>
     * Western Australia in Australia
     * </pre>
     *
     * <code>TERRITORY_AUSTRALIA_WESTERN_AUSTRALIA = 8;</code>
     */
    public static final int TERRITORY_AUSTRALIA_WESTERN_AUSTRALIA_VALUE = 8;
    /**
     * <pre>
     * Alagoas in Brazil
     * </pre>
     *
     * <code>TERRITORY_BRAZIL_ALAGOAS = 9;</code>
     */
    public static final int TERRITORY_BRAZIL_ALAGOAS_VALUE = 9;
    /**
     * <pre>
     * Ceara in Brazil
     * </pre>
     *
     * <code>TERRITORY_BRAZIL_CEARA = 10;</code>
     */
    public static final int TERRITORY_BRAZIL_CEARA_VALUE = 10;
    /**
     * <pre>
     * Distrito Federal in Brazil
     * </pre>
     *
     * <code>TERRITORY_BRAZIL_DISTRITO_FEDERAL = 11;</code>
     */
    public static final int TERRITORY_BRAZIL_DISTRITO_FEDERAL_VALUE = 11;
    /**
     * <pre>
     * Goias in Brazil
     * </pre>
     *
     * <code>TERRITORY_BRAZIL_GOIAS = 12;</code>
     */
    public static final int TERRITORY_BRAZIL_GOIAS_VALUE = 12;
    /**
     * <pre>
     * Maranhao in Brazil
     * </pre>
     *
     * <code>TERRITORY_BRAZIL_MARANHAO = 13;</code>
     */
    public static final int TERRITORY_BRAZIL_MARANHAO_VALUE = 13;
    /**
     * <pre>
     * Mato Grosso in Brazil
     * </pre>
     *
     * <code>TERRITORY_BRAZIL_MATO_GROSSO = 14;</code>
     */
    public static final int TERRITORY_BRAZIL_MATO_GROSSO_VALUE = 14;
    /**
     * <pre>
     * Minas Gerais in Brazil
     * </pre>
     *
     * <code>TERRITORY_BRAZIL_MINAS_GERAIS = 15;</code>
     */
    public static final int TERRITORY_BRAZIL_MINAS_GERAIS_VALUE = 15;
    /**
     * <pre>
     * Para in Brazil
     * </pre>
     *
     * <code>TERRITORY_BRAZIL_PARA = 16;</code>
     */
    public static final int TERRITORY_BRAZIL_PARA_VALUE = 16;
    /**
     * <pre>
     * Parana in Brazil
     * </pre>
     *
     * <code>TERRITORY_BRAZIL_PARANA = 17;</code>
     */
    public static final int TERRITORY_BRAZIL_PARANA_VALUE = 17;
    /**
     * <pre>
     * Pernambuco in Brazil
     * </pre>
     *
     * <code>TERRITORY_BRAZIL_PERNAMBUCO = 18;</code>
     */
    public static final int TERRITORY_BRAZIL_PERNAMBUCO_VALUE = 18;
    /**
     * <pre>
     * Rio De Janeiro in Brazil
     * </pre>
     *
     * <code>TERRITORY_BRAZIL_RIO_DE_JANEIRO = 19;</code>
     */
    public static final int TERRITORY_BRAZIL_RIO_DE_JANEIRO_VALUE = 19;
    /**
     * <pre>
     * Rio Grande Do Sul in Brazil
     * </pre>
     *
     * <code>TERRITORY_BRAZIL_RIO_GRANDE_DO_SUL = 20;</code>
     */
    public static final int TERRITORY_BRAZIL_RIO_GRANDE_DO_SUL_VALUE = 20;
    /**
     * <pre>
     * Santa Catarina in Brazil
     * </pre>
     *
     * <code>TERRITORY_BRAZIL_SANTA_CATARINA = 21;</code>
     */
    public static final int TERRITORY_BRAZIL_SANTA_CATARINA_VALUE = 21;
    /**
     * <pre>
     * Sao Paolo in Brazil
     * </pre>
     *
     * <code>TERRITORY_BRAZIL_SAO_PAOLO = 22;</code>
     */
    public static final int TERRITORY_BRAZIL_SAO_PAOLO_VALUE = 22;
    /**
     * <pre>
     * Sergipe in Brazil
     * </pre>
     *
     * <code>TERRITORY_BRAZIL_SERGIPE = 23;</code>
     */
    public static final int TERRITORY_BRAZIL_SERGIPE_VALUE = 23;
    /**
     * <pre>
     * Alberta in Canada
     * </pre>
     *
     * <code>TERRITORY_CANADA_ALBERTA = 24;</code>
     */
    public static final int TERRITORY_CANADA_ALBERTA_VALUE = 24;
    /**
     * <pre>
     * British Columbia in Canada
     * </pre>
     *
     * <code>TERRITORY_CANADA_BRITISH_COLUMBIA = 25;</code>
     */
    public static final int TERRITORY_CANADA_BRITISH_COLUMBIA_VALUE = 25;
    /**
     * <pre>
     * Manitoba in Canada
     * </pre>
     *
     * <code>TERRITORY_CANADA_MANITOBA = 26;</code>
     */
    public static final int TERRITORY_CANADA_MANITOBA_VALUE = 26;
    /**
     * <pre>
     * New Brunswick in Canada
     * </pre>
     *
     * <code>TERRITORY_CANADA_NEW_BRUNSWICK = 27;</code>
     */
    public static final int TERRITORY_CANADA_NEW_BRUNSWICK_VALUE = 27;
    /**
     * <pre>
     * Newfoundland And Labrador in Canada
     * </pre>
     *
     * <code>TERRITORY_CANADA_NEWFOUNDLAND_AND_LABRADOR = 28;</code>
     */
    public static final int TERRITORY_CANADA_NEWFOUNDLAND_AND_LABRADOR_VALUE = 28;
    /**
     * <pre>
     * Northwest Territories in Canada
     * </pre>
     *
     * <code>TERRITORY_CANADA_NORTHWEST_TERRITORIES = 29;</code>
     */
    public static final int TERRITORY_CANADA_NORTHWEST_TERRITORIES_VALUE = 29;
    /**
     * <pre>
     * Nova Scotia in Canada
     * </pre>
     *
     * <code>TERRITORY_CANADA_NOVA_SCOTIA = 30;</code>
     */
    public static final int TERRITORY_CANADA_NOVA_SCOTIA_VALUE = 30;
    /**
     * <pre>
     * Nunavut in Canada
     * </pre>
     *
     * <code>TERRITORY_CANADA_NUNAVUT = 31;</code>
     */
    public static final int TERRITORY_CANADA_NUNAVUT_VALUE = 31;
    /**
     * <pre>
     * Ontario in Canada
     * </pre>
     *
     * <code>TERRITORY_CANADA_ONTARIO = 32;</code>
     */
    public static final int TERRITORY_CANADA_ONTARIO_VALUE = 32;
    /**
     * <pre>
     * Prince Edward Island in Canada
     * </pre>
     *
     * <code>TERRITORY_CANADA_PRINCE_EDWARD_ISLAND = 33;</code>
     */
    public static final int TERRITORY_CANADA_PRINCE_EDWARD_ISLAND_VALUE = 33;
    /**
     * <pre>
     * Quebec in Canada
     * </pre>
     *
     * <code>TERRITORY_CANADA_QUEBEC = 34;</code>
     */
    public static final int TERRITORY_CANADA_QUEBEC_VALUE = 34;
    /**
     * <pre>
     * Saskatchewan in Canada
     * </pre>
     *
     * <code>TERRITORY_CANADA_SASKATCHEWAN = 35;</code>
     */
    public static final int TERRITORY_CANADA_SASKATCHEWAN_VALUE = 35;
    /**
     * <pre>
     * Yukon in Canada
     * </pre>
     *
     * <code>TERRITORY_CANADA_YUKON = 36;</code>
     */
    public static final int TERRITORY_CANADA_YUKON_VALUE = 36;
    /**
     * <pre>
     * Andhra Pradesh in India
     * </pre>
     *
     * <code>TERRITORY_INDIA_ANDHRA_PRADESH = 37;</code>
     */
    public static final int TERRITORY_INDIA_ANDHRA_PRADESH_VALUE = 37;
    /**
     * <pre>
     * Gujarat in India
     * </pre>
     *
     * <code>TERRITORY_INDIA_GUJARAT = 38;</code>
     */
    public static final int TERRITORY_INDIA_GUJARAT_VALUE = 38;
    /**
     * <pre>
     * Haryana in India
     * </pre>
     *
     * <code>TERRITORY_INDIA_HARYANA = 39;</code>
     */
    public static final int TERRITORY_INDIA_HARYANA_VALUE = 39;
    /**
     * <pre>
     * Karnataka in India
     * </pre>
     *
     * <code>TERRITORY_INDIA_KARNATAKA = 40;</code>
     */
    public static final int TERRITORY_INDIA_KARNATAKA_VALUE = 40;
    /**
     * <pre>
     * Kerala in India
     * </pre>
     *
     * <code>TERRITORY_INDIA_KERALA = 41;</code>
     */
    public static final int TERRITORY_INDIA_KERALA_VALUE = 41;
    /**
     * <pre>
     * Madhya Pradesh in India
     * </pre>
     *
     * <code>TERRITORY_INDIA_MADHYA_PRADESH = 42;</code>
     */
    public static final int TERRITORY_INDIA_MADHYA_PRADESH_VALUE = 42;
    /**
     * <pre>
     * Maharashtra in India
     * </pre>
     *
     * <code>TERRITORY_INDIA_MAHARASHTRA = 43;</code>
     */
    public static final int TERRITORY_INDIA_MAHARASHTRA_VALUE = 43;
    /**
     * <pre>
     * Punjab in India
     * </pre>
     *
     * <code>TERRITORY_INDIA_PUNJAB = 44;</code>
     */
    public static final int TERRITORY_INDIA_PUNJAB_VALUE = 44;
    /**
     * <pre>
     * Tamil Nadu in India
     * </pre>
     *
     * <code>TERRITORY_INDIA_TAMIL_NADU = 45;</code>
     */
    public static final int TERRITORY_INDIA_TAMIL_NADU_VALUE = 45;
    /**
     * <pre>
     * Aguascalientes in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_AGUASCALIENTES = 46;</code>
     */
    public static final int TERRITORY_MEXICO_AGUASCALIENTES_VALUE = 46;
    /**
     * <pre>
     * Baja California in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_BAJA_CALIFORNIA = 47;</code>
     */
    public static final int TERRITORY_MEXICO_BAJA_CALIFORNIA_VALUE = 47;
    /**
     * <pre>
     * Baja California Sur in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_BAJA_CALIFORNIA_SUR = 48;</code>
     */
    public static final int TERRITORY_MEXICO_BAJA_CALIFORNIA_SUR_VALUE = 48;
    /**
     * <pre>
     * Campeche in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_CAMPECHE = 49;</code>
     */
    public static final int TERRITORY_MEXICO_CAMPECHE_VALUE = 49;
    /**
     * <pre>
     * Chiapas in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_CHIAPAS = 50;</code>
     */
    public static final int TERRITORY_MEXICO_CHIAPAS_VALUE = 50;
    /**
     * <pre>
     * Chihuahua in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_CHIHUAHUA = 51;</code>
     */
    public static final int TERRITORY_MEXICO_CHIHUAHUA_VALUE = 51;
    /**
     * <pre>
     * Ciudad De Mexico in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_CIUDAD_DE_MEXICO = 52;</code>
     */
    public static final int TERRITORY_MEXICO_CIUDAD_DE_MEXICO_VALUE = 52;
    /**
     * <pre>
     * Coahuila in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_COAHUILA = 53;</code>
     */
    public static final int TERRITORY_MEXICO_COAHUILA_VALUE = 53;
    /**
     * <pre>
     * Colima in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_COLIMA = 54;</code>
     */
    public static final int TERRITORY_MEXICO_COLIMA_VALUE = 54;
    /**
     * <pre>
     * Durango in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_DURANGO = 55;</code>
     */
    public static final int TERRITORY_MEXICO_DURANGO_VALUE = 55;
    /**
     * <pre>
     * Guanajuato in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_GUANAJUATO = 56;</code>
     */
    public static final int TERRITORY_MEXICO_GUANAJUATO_VALUE = 56;
    /**
     * <pre>
     * Guerrero in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_GUERRERO = 57;</code>
     */
    public static final int TERRITORY_MEXICO_GUERRERO_VALUE = 57;
    /**
     * <pre>
     * Hidalgo in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_HIDALGO = 58;</code>
     */
    public static final int TERRITORY_MEXICO_HIDALGO_VALUE = 58;
    /**
     * <pre>
     * Jalisco in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_JALISCO = 59;</code>
     */
    public static final int TERRITORY_MEXICO_JALISCO_VALUE = 59;
    /**
     * <pre>
     * Mexico in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_MEXICO = 60;</code>
     */
    public static final int TERRITORY_MEXICO_MEXICO_VALUE = 60;
    /**
     * <pre>
     * Michoacan in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_MICHOACAN = 61;</code>
     */
    public static final int TERRITORY_MEXICO_MICHOACAN_VALUE = 61;
    /**
     * <pre>
     * Morelos in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_MORELOS = 62;</code>
     */
    public static final int TERRITORY_MEXICO_MORELOS_VALUE = 62;
    /**
     * <pre>
     * Nayarit in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_NAYARIT = 63;</code>
     */
    public static final int TERRITORY_MEXICO_NAYARIT_VALUE = 63;
    /**
     * <pre>
     * Nuevo Leon in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_NUEVO_LEON = 64;</code>
     */
    public static final int TERRITORY_MEXICO_NUEVO_LEON_VALUE = 64;
    /**
     * <pre>
     * Oaxaca in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_OAXACA = 65;</code>
     */
    public static final int TERRITORY_MEXICO_OAXACA_VALUE = 65;
    /**
     * <pre>
     * Puebla in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_PUEBLA = 66;</code>
     */
    public static final int TERRITORY_MEXICO_PUEBLA_VALUE = 66;
    /**
     * <pre>
     * Queretaro in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_QUERETARO = 67;</code>
     */
    public static final int TERRITORY_MEXICO_QUERETARO_VALUE = 67;
    /**
     * <pre>
     * Quintana Roo in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_QUINTANA_ROO = 68;</code>
     */
    public static final int TERRITORY_MEXICO_QUINTANA_ROO_VALUE = 68;
    /**
     * <pre>
     * San Luis Potosi in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_SAN_LUIS_POTOSI = 69;</code>
     */
    public static final int TERRITORY_MEXICO_SAN_LUIS_POTOSI_VALUE = 69;
    /**
     * <pre>
     * Sinaloa in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_SINALOA = 70;</code>
     */
    public static final int TERRITORY_MEXICO_SINALOA_VALUE = 70;
    /**
     * <pre>
     * Sonora in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_SONORA = 71;</code>
     */
    public static final int TERRITORY_MEXICO_SONORA_VALUE = 71;
    /**
     * <pre>
     * Tabasco in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_TABASCO = 72;</code>
     */
    public static final int TERRITORY_MEXICO_TABASCO_VALUE = 72;
    /**
     * <pre>
     * Tamaulipas in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_TAMAULIPAS = 73;</code>
     */
    public static final int TERRITORY_MEXICO_TAMAULIPAS_VALUE = 73;
    /**
     * <pre>
     * Tlaxcala in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_TLAXCALA = 74;</code>
     */
    public static final int TERRITORY_MEXICO_TLAXCALA_VALUE = 74;
    /**
     * <pre>
     * Veracruz in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_VERACRUZ = 75;</code>
     */
    public static final int TERRITORY_MEXICO_VERACRUZ_VALUE = 75;
    /**
     * <pre>
     * Yucatan in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_YUCATAN = 76;</code>
     */
    public static final int TERRITORY_MEXICO_YUCATAN_VALUE = 76;
    /**
     * <pre>
     * Zacatecas in Mexico
     * </pre>
     *
     * <code>TERRITORY_MEXICO_ZACATECAS = 77;</code>
     */
    public static final int TERRITORY_MEXICO_ZACATECAS_VALUE = 77;
    /**
     * <pre>
     * Khyber Pakhtunkhwa in Pakistan
     * </pre>
     *
     * <code>TERRITORY_PAKISTAN_KHYBER_PAKHTUNKHWA = 78;</code>
     */
    public static final int TERRITORY_PAKISTAN_KHYBER_PAKHTUNKHWA_VALUE = 78;
    /**
     * <pre>
     * Punjab in Pakistan
     * </pre>
     *
     * <code>TERRITORY_PAKISTAN_PUNJAB = 79;</code>
     */
    public static final int TERRITORY_PAKISTAN_PUNJAB_VALUE = 79;
    /**
     * <pre>
     * Alabama in USA
     * </pre>
     *
     * <code>TERRITORY_USA_ALABAMA = 80;</code>
     */
    public static final int TERRITORY_USA_ALABAMA_VALUE = 80;
    /**
     * <pre>
     * Alaska in USA
     * </pre>
     *
     * <code>TERRITORY_USA_ALASKA = 81;</code>
     */
    public static final int TERRITORY_USA_ALASKA_VALUE = 81;
    /**
     * <pre>
     * Arizona in USA
     * </pre>
     *
     * <code>TERRITORY_USA_ARIZONA = 82;</code>
     */
    public static final int TERRITORY_USA_ARIZONA_VALUE = 82;
    /**
     * <pre>
     * Arkansas in USA
     * </pre>
     *
     * <code>TERRITORY_USA_ARKANSAS = 83;</code>
     */
    public static final int TERRITORY_USA_ARKANSAS_VALUE = 83;
    /**
     * <pre>
     * California in USA
     * </pre>
     *
     * <code>TERRITORY_USA_CALIFORNIA = 84;</code>
     */
    public static final int TERRITORY_USA_CALIFORNIA_VALUE = 84;
    /**
     * <pre>
     * Colorado in USA
     * </pre>
     *
     * <code>TERRITORY_USA_COLORADO = 85;</code>
     */
    public static final int TERRITORY_USA_COLORADO_VALUE = 85;
    /**
     * <pre>
     * Connecticut in USA
     * </pre>
     *
     * <code>TERRITORY_USA_CONNECTICUT = 86;</code>
     */
    public static final int TERRITORY_USA_CONNECTICUT_VALUE = 86;
    /**
     * <pre>
     * Delaware in USA
     * </pre>
     *
     * <code>TERRITORY_USA_DELAWARE = 87;</code>
     */
    public static final int TERRITORY_USA_DELAWARE_VALUE = 87;
    /**
     * <pre>
     * District Of Columbia in USA
     * </pre>
     *
     * <code>TERRITORY_USA_DISTRICT_OF_COLUMBIA = 88;</code>
     */
    public static final int TERRITORY_USA_DISTRICT_OF_COLUMBIA_VALUE = 88;
    /**
     * <pre>
     * Florida in USA
     * </pre>
     *
     * <code>TERRITORY_USA_FLORIDA = 89;</code>
     */
    public static final int TERRITORY_USA_FLORIDA_VALUE = 89;
    /**
     * <pre>
     * Georgia in USA
     * </pre>
     *
     * <code>TERRITORY_USA_GEORGIA = 90;</code>
     */
    public static final int TERRITORY_USA_GEORGIA_VALUE = 90;
    /**
     * <pre>
     * Hawaii in USA
     * </pre>
     *
     * <code>TERRITORY_USA_HAWAII = 91;</code>
     */
    public static final int TERRITORY_USA_HAWAII_VALUE = 91;
    /**
     * <pre>
     * Idaho in USA
     * </pre>
     *
     * <code>TERRITORY_USA_IDAHO = 92;</code>
     */
    public static final int TERRITORY_USA_IDAHO_VALUE = 92;
    /**
     * <pre>
     * Illinois in USA
     * </pre>
     *
     * <code>TERRITORY_USA_ILLINOIS = 93;</code>
     */
    public static final int TERRITORY_USA_ILLINOIS_VALUE = 93;
    /**
     * <pre>
     * Indiana in USA
     * </pre>
     *
     * <code>TERRITORY_USA_INDIANA = 94;</code>
     */
    public static final int TERRITORY_USA_INDIANA_VALUE = 94;
    /**
     * <pre>
     * Iowa in USA
     * </pre>
     *
     * <code>TERRITORY_USA_IOWA = 95;</code>
     */
    public static final int TERRITORY_USA_IOWA_VALUE = 95;
    /**
     * <pre>
     * Kansas in USA
     * </pre>
     *
     * <code>TERRITORY_USA_KANSAS = 96;</code>
     */
    public static final int TERRITORY_USA_KANSAS_VALUE = 96;
    /**
     * <pre>
     * Kentucky in USA
     * </pre>
     *
     * <code>TERRITORY_USA_KENTUCKY = 97;</code>
     */
    public static final int TERRITORY_USA_KENTUCKY_VALUE = 97;
    /**
     * <pre>
     * Louisiana in USA
     * </pre>
     *
     * <code>TERRITORY_USA_LOUISIANA = 98;</code>
     */
    public static final int TERRITORY_USA_LOUISIANA_VALUE = 98;
    /**
     * <pre>
     * Maine in USA
     * </pre>
     *
     * <code>TERRITORY_USA_MAINE = 99;</code>
     */
    public static final int TERRITORY_USA_MAINE_VALUE = 99;
    /**
     * <pre>
     * Maryland in USA
     * </pre>
     *
     * <code>TERRITORY_USA_MARYLAND = 100;</code>
     */
    public static final int TERRITORY_USA_MARYLAND_VALUE = 100;
    /**
     * <pre>
     * Massachusetts in USA
     * </pre>
     *
     * <code>TERRITORY_USA_MASSACHUSETTS = 101;</code>
     */
    public static final int TERRITORY_USA_MASSACHUSETTS_VALUE = 101;
    /**
     * <pre>
     * Michigan in USA
     * </pre>
     *
     * <code>TERRITORY_USA_MICHIGAN = 102;</code>
     */
    public static final int TERRITORY_USA_MICHIGAN_VALUE = 102;
    /**
     * <pre>
     * Minnesota in USA
     * </pre>
     *
     * <code>TERRITORY_USA_MINNESOTA = 103;</code>
     */
    public static final int TERRITORY_USA_MINNESOTA_VALUE = 103;
    /**
     * <pre>
     * Mississippi in USA
     * </pre>
     *
     * <code>TERRITORY_USA_MISSISSIPPI = 104;</code>
     */
    public static final int TERRITORY_USA_MISSISSIPPI_VALUE = 104;
    /**
     * <pre>
     * Missouri in USA
     * </pre>
     *
     * <code>TERRITORY_USA_MISSOURI = 105;</code>
     */
    public static final int TERRITORY_USA_MISSOURI_VALUE = 105;
    /**
     * <pre>
     * Montana in USA
     * </pre>
     *
     * <code>TERRITORY_USA_MONTANA = 106;</code>
     */
    public static final int TERRITORY_USA_MONTANA_VALUE = 106;
    /**
     * <pre>
     * Nebraska in USA
     * </pre>
     *
     * <code>TERRITORY_USA_NEBRASKA = 107;</code>
     */
    public static final int TERRITORY_USA_NEBRASKA_VALUE = 107;
    /**
     * <pre>
     * Nevada in USA
     * </pre>
     *
     * <code>TERRITORY_USA_NEVADA = 108;</code>
     */
    public static final int TERRITORY_USA_NEVADA_VALUE = 108;
    /**
     * <pre>
     * New Hampshire in USA
     * </pre>
     *
     * <code>TERRITORY_USA_NEW_HAMPSHIRE = 109;</code>
     */
    public static final int TERRITORY_USA_NEW_HAMPSHIRE_VALUE = 109;
    /**
     * <pre>
     * New Jersey in USA
     * </pre>
     *
     * <code>TERRITORY_USA_NEW_JERSEY = 110;</code>
     */
    public static final int TERRITORY_USA_NEW_JERSEY_VALUE = 110;
    /**
     * <pre>
     * New Mexico in USA
     * </pre>
     *
     * <code>TERRITORY_USA_NEW_MEXICO = 111;</code>
     */
    public static final int TERRITORY_USA_NEW_MEXICO_VALUE = 111;
    /**
     * <pre>
     * New York in USA
     * </pre>
     *
     * <code>TERRITORY_USA_NEW_YORK = 112;</code>
     */
    public static final int TERRITORY_USA_NEW_YORK_VALUE = 112;
    /**
     * <pre>
     * New York City in USA
     * </pre>
     *
     * <code>TERRITORY_USA_NEW_YORK_CITY = 113;</code>
     */
    public static final int TERRITORY_USA_NEW_YORK_CITY_VALUE = 113;
    /**
     * <pre>
     * North Carolina in USA
     * </pre>
     *
     * <code>TERRITORY_USA_NORTH_CAROLINA = 114;</code>
     */
    public static final int TERRITORY_USA_NORTH_CAROLINA_VALUE = 114;
    /**
     * <pre>
     * North Dakota in USA
     * </pre>
     *
     * <code>TERRITORY_USA_NORTH_DAKOTA = 115;</code>
     */
    public static final int TERRITORY_USA_NORTH_DAKOTA_VALUE = 115;
    /**
     * <pre>
     * Ohio in USA
     * </pre>
     *
     * <code>TERRITORY_USA_OHIO = 116;</code>
     */
    public static final int TERRITORY_USA_OHIO_VALUE = 116;
    /**
     * <pre>
     * Oklahoma in USA
     * </pre>
     *
     * <code>TERRITORY_USA_OKLAHOMA = 117;</code>
     */
    public static final int TERRITORY_USA_OKLAHOMA_VALUE = 117;
    /**
     * <pre>
     * Oregon in USA
     * </pre>
     *
     * <code>TERRITORY_USA_OREGON = 118;</code>
     */
    public static final int TERRITORY_USA_OREGON_VALUE = 118;
    /**
     * <pre>
     * Pennsylvania in USA
     * </pre>
     *
     * <code>TERRITORY_USA_PENNSYLVANIA = 119;</code>
     */
    public static final int TERRITORY_USA_PENNSYLVANIA_VALUE = 119;
    /**
     * <pre>
     * Rhode Island in USA
     * </pre>
     *
     * <code>TERRITORY_USA_RHODE_ISLAND = 120;</code>
     */
    public static final int TERRITORY_USA_RHODE_ISLAND_VALUE = 120;
    /**
     * <pre>
     * South Carolina in USA
     * </pre>
     *
     * <code>TERRITORY_USA_SOUTH_CAROLINA = 121;</code>
     */
    public static final int TERRITORY_USA_SOUTH_CAROLINA_VALUE = 121;
    /**
     * <pre>
     * South Dakota in USA
     * </pre>
     *
     * <code>TERRITORY_USA_SOUTH_DAKOTA = 122;</code>
     */
    public static final int TERRITORY_USA_SOUTH_DAKOTA_VALUE = 122;
    /**
     * <pre>
     * Tennessee in USA
     * </pre>
     *
     * <code>TERRITORY_USA_TENNESSEE = 123;</code>
     */
    public static final int TERRITORY_USA_TENNESSEE_VALUE = 123;
    /**
     * <pre>
     * Texas in USA
     * </pre>
     *
     * <code>TERRITORY_USA_TEXAS = 124;</code>
     */
    public static final int TERRITORY_USA_TEXAS_VALUE = 124;
    /**
     * <pre>
     * Utah in USA
     * </pre>
     *
     * <code>TERRITORY_USA_UTAH = 125;</code>
     */
    public static final int TERRITORY_USA_UTAH_VALUE = 125;
    /**
     * <pre>
     * Vermont in USA
     * </pre>
     *
     * <code>TERRITORY_USA_VERMONT = 126;</code>
     */
    public static final int TERRITORY_USA_VERMONT_VALUE = 126;
    /**
     * <pre>
     * Virginia in USA
     * </pre>
     *
     * <code>TERRITORY_USA_VIRGINIA = 127;</code>
     */
    public static final int TERRITORY_USA_VIRGINIA_VALUE = 127;
    /**
     * <pre>
     * Washington in USA
     * </pre>
     *
     * <code>TERRITORY_USA_WASHINGTON = 128;</code>
     */
    public static final int TERRITORY_USA_WASHINGTON_VALUE = 128;
    /**
     * <pre>
     * West Virginia in USA
     * </pre>
     *
     * <code>TERRITORY_USA_WEST_VIRGINIA = 129;</code>
     */
    public static final int TERRITORY_USA_WEST_VIRGINIA_VALUE = 129;
    /**
     * <pre>
     * Wisconsin in USA
     * </pre>
     *
     * <code>TERRITORY_USA_WISCONSIN = 130;</code>
     */
    public static final int TERRITORY_USA_WISCONSIN_VALUE = 130;
    /**
     * <pre>
     * Wyoming in USA
     * </pre>
     *
     * <code>TERRITORY_USA_WYOMING = 131;</code>
     */
    public static final int TERRITORY_USA_WYOMING_VALUE = 131;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Territory valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Territory forNumber(int value) {
      switch (value) {
        case 0: return TERRITORY_NOT_AVAILABLE;
        case 1: return TERRITORY_AUSTRALIA_AUSTRALIAN_CAPITAL_TERRITORY;
        case 2: return TERRITORY_AUSTRALIA_NEW_SOUTH_WALES;
        case 3: return TERRITORY_AUSTRALIA_NORTHERN_TERRITORY;
        case 4: return TERRITORY_AUSTRALIA_QUEENSLAND;
        case 5: return TERRITORY_AUSTRALIA_SOUTH_AUSTRALIA;
        case 6: return TERRITORY_AUSTRALIA_TASMANIA;
        case 7: return TERRITORY_AUSTRALIA_VICTORIA;
        case 8: return TERRITORY_AUSTRALIA_WESTERN_AUSTRALIA;
        case 9: return TERRITORY_BRAZIL_ALAGOAS;
        case 10: return TERRITORY_BRAZIL_CEARA;
        case 11: return TERRITORY_BRAZIL_DISTRITO_FEDERAL;
        case 12: return TERRITORY_BRAZIL_GOIAS;
        case 13: return TERRITORY_BRAZIL_MARANHAO;
        case 14: return TERRITORY_BRAZIL_MATO_GROSSO;
        case 15: return TERRITORY_BRAZIL_MINAS_GERAIS;
        case 16: return TERRITORY_BRAZIL_PARA;
        case 17: return TERRITORY_BRAZIL_PARANA;
        case 18: return TERRITORY_BRAZIL_PERNAMBUCO;
        case 19: return TERRITORY_BRAZIL_RIO_DE_JANEIRO;
        case 20: return TERRITORY_BRAZIL_RIO_GRANDE_DO_SUL;
        case 21: return TERRITORY_BRAZIL_SANTA_CATARINA;
        case 22: return TERRITORY_BRAZIL_SAO_PAOLO;
        case 23: return TERRITORY_BRAZIL_SERGIPE;
        case 24: return TERRITORY_CANADA_ALBERTA;
        case 25: return TERRITORY_CANADA_BRITISH_COLUMBIA;
        case 26: return TERRITORY_CANADA_MANITOBA;
        case 27: return TERRITORY_CANADA_NEW_BRUNSWICK;
        case 28: return TERRITORY_CANADA_NEWFOUNDLAND_AND_LABRADOR;
        case 29: return TERRITORY_CANADA_NORTHWEST_TERRITORIES;
        case 30: return TERRITORY_CANADA_NOVA_SCOTIA;
        case 31: return TERRITORY_CANADA_NUNAVUT;
        case 32: return TERRITORY_CANADA_ONTARIO;
        case 33: return TERRITORY_CANADA_PRINCE_EDWARD_ISLAND;
        case 34: return TERRITORY_CANADA_QUEBEC;
        case 35: return TERRITORY_CANADA_SASKATCHEWAN;
        case 36: return TERRITORY_CANADA_YUKON;
        case 37: return TERRITORY_INDIA_ANDHRA_PRADESH;
        case 38: return TERRITORY_INDIA_GUJARAT;
        case 39: return TERRITORY_INDIA_HARYANA;
        case 40: return TERRITORY_INDIA_KARNATAKA;
        case 41: return TERRITORY_INDIA_KERALA;
        case 42: return TERRITORY_INDIA_MADHYA_PRADESH;
        case 43: return TERRITORY_INDIA_MAHARASHTRA;
        case 44: return TERRITORY_INDIA_PUNJAB;
        case 45: return TERRITORY_INDIA_TAMIL_NADU;
        case 46: return TERRITORY_MEXICO_AGUASCALIENTES;
        case 47: return TERRITORY_MEXICO_BAJA_CALIFORNIA;
        case 48: return TERRITORY_MEXICO_BAJA_CALIFORNIA_SUR;
        case 49: return TERRITORY_MEXICO_CAMPECHE;
        case 50: return TERRITORY_MEXICO_CHIAPAS;
        case 51: return TERRITORY_MEXICO_CHIHUAHUA;
        case 52: return TERRITORY_MEXICO_CIUDAD_DE_MEXICO;
        case 53: return TERRITORY_MEXICO_COAHUILA;
        case 54: return TERRITORY_MEXICO_COLIMA;
        case 55: return TERRITORY_MEXICO_DURANGO;
        case 56: return TERRITORY_MEXICO_GUANAJUATO;
        case 57: return TERRITORY_MEXICO_GUERRERO;
        case 58: return TERRITORY_MEXICO_HIDALGO;
        case 59: return TERRITORY_MEXICO_JALISCO;
        case 60: return TERRITORY_MEXICO_MEXICO;
        case 61: return TERRITORY_MEXICO_MICHOACAN;
        case 62: return TERRITORY_MEXICO_MORELOS;
        case 63: return TERRITORY_MEXICO_NAYARIT;
        case 64: return TERRITORY_MEXICO_NUEVO_LEON;
        case 65: return TERRITORY_MEXICO_OAXACA;
        case 66: return TERRITORY_MEXICO_PUEBLA;
        case 67: return TERRITORY_MEXICO_QUERETARO;
        case 68: return TERRITORY_MEXICO_QUINTANA_ROO;
        case 69: return TERRITORY_MEXICO_SAN_LUIS_POTOSI;
        case 70: return TERRITORY_MEXICO_SINALOA;
        case 71: return TERRITORY_MEXICO_SONORA;
        case 72: return TERRITORY_MEXICO_TABASCO;
        case 73: return TERRITORY_MEXICO_TAMAULIPAS;
        case 74: return TERRITORY_MEXICO_TLAXCALA;
        case 75: return TERRITORY_MEXICO_VERACRUZ;
        case 76: return TERRITORY_MEXICO_YUCATAN;
        case 77: return TERRITORY_MEXICO_ZACATECAS;
        case 78: return TERRITORY_PAKISTAN_KHYBER_PAKHTUNKHWA;
        case 79: return TERRITORY_PAKISTAN_PUNJAB;
        case 80: return TERRITORY_USA_ALABAMA;
        case 81: return TERRITORY_USA_ALASKA;
        case 82: return TERRITORY_USA_ARIZONA;
        case 83: return TERRITORY_USA_ARKANSAS;
        case 84: return TERRITORY_USA_CALIFORNIA;
        case 85: return TERRITORY_USA_COLORADO;
        case 86: return TERRITORY_USA_CONNECTICUT;
        case 87: return TERRITORY_USA_DELAWARE;
        case 88: return TERRITORY_USA_DISTRICT_OF_COLUMBIA;
        case 89: return TERRITORY_USA_FLORIDA;
        case 90: return TERRITORY_USA_GEORGIA;
        case 91: return TERRITORY_USA_HAWAII;
        case 92: return TERRITORY_USA_IDAHO;
        case 93: return TERRITORY_USA_ILLINOIS;
        case 94: return TERRITORY_USA_INDIANA;
        case 95: return TERRITORY_USA_IOWA;
        case 96: return TERRITORY_USA_KANSAS;
        case 97: return TERRITORY_USA_KENTUCKY;
        case 98: return TERRITORY_USA_LOUISIANA;
        case 99: return TERRITORY_USA_MAINE;
        case 100: return TERRITORY_USA_MARYLAND;
        case 101: return TERRITORY_USA_MASSACHUSETTS;
        case 102: return TERRITORY_USA_MICHIGAN;
        case 103: return TERRITORY_USA_MINNESOTA;
        case 104: return TERRITORY_USA_MISSISSIPPI;
        case 105: return TERRITORY_USA_MISSOURI;
        case 106: return TERRITORY_USA_MONTANA;
        case 107: return TERRITORY_USA_NEBRASKA;
        case 108: return TERRITORY_USA_NEVADA;
        case 109: return TERRITORY_USA_NEW_HAMPSHIRE;
        case 110: return TERRITORY_USA_NEW_JERSEY;
        case 111: return TERRITORY_USA_NEW_MEXICO;
        case 112: return TERRITORY_USA_NEW_YORK;
        case 113: return TERRITORY_USA_NEW_YORK_CITY;
        case 114: return TERRITORY_USA_NORTH_CAROLINA;
        case 115: return TERRITORY_USA_NORTH_DAKOTA;
        case 116: return TERRITORY_USA_OHIO;
        case 117: return TERRITORY_USA_OKLAHOMA;
        case 118: return TERRITORY_USA_OREGON;
        case 119: return TERRITORY_USA_PENNSYLVANIA;
        case 120: return TERRITORY_USA_RHODE_ISLAND;
        case 121: return TERRITORY_USA_SOUTH_CAROLINA;
        case 122: return TERRITORY_USA_SOUTH_DAKOTA;
        case 123: return TERRITORY_USA_TENNESSEE;
        case 124: return TERRITORY_USA_TEXAS;
        case 125: return TERRITORY_USA_UTAH;
        case 126: return TERRITORY_USA_VERMONT;
        case 127: return TERRITORY_USA_VIRGINIA;
        case 128: return TERRITORY_USA_WASHINGTON;
        case 129: return TERRITORY_USA_WEST_VIRGINIA;
        case 130: return TERRITORY_USA_WISCONSIN;
        case 131: return TERRITORY_USA_WYOMING;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Territory>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Territory> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Territory>() {
            public Territory findValueByNumber(int number) {
              return Territory.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return proto.ddx.v1.TerritoryEnum.getDescriptor().getEnumTypes().get(0);
    }

    private static final Territory[] VALUES = values();

    public static Territory valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Territory(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:proto.ddx.v1.Territory)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!proto/ddx/v1/territory_enum.proto\022\014pro" +
      "to.ddx.v1*\343 \n\tTerritory\022\033\n\027TERRITORY_NOT" +
      "_AVAILABLE\020\000\0224\n0TERRITORY_AUSTRALIA_AUST" +
      "RALIAN_CAPITAL_TERRITORY\020\001\022\'\n#TERRITORY_" +
      "AUSTRALIA_NEW_SOUTH_WALES\020\002\022*\n&TERRITORY" +
      "_AUSTRALIA_NORTHERN_TERRITORY\020\003\022\"\n\036TERRI" +
      "TORY_AUSTRALIA_QUEENSLAND\020\004\022\'\n#TERRITORY" +
      "_AUSTRALIA_SOUTH_AUSTRALIA\020\005\022 \n\034TERRITOR" +
      "Y_AUSTRALIA_TASMANIA\020\006\022 \n\034TERRITORY_AUST" +
      "RALIA_VICTORIA\020\007\022)\n%TERRITORY_AUSTRALIA_" +
      "WESTERN_AUSTRALIA\020\010\022\034\n\030TERRITORY_BRAZIL_" +
      "ALAGOAS\020\t\022\032\n\026TERRITORY_BRAZIL_CEARA\020\n\022%\n" +
      "!TERRITORY_BRAZIL_DISTRITO_FEDERAL\020\013\022\032\n\026" +
      "TERRITORY_BRAZIL_GOIAS\020\014\022\035\n\031TERRITORY_BR" +
      "AZIL_MARANHAO\020\r\022 \n\034TERRITORY_BRAZIL_MATO" +
      "_GROSSO\020\016\022!\n\035TERRITORY_BRAZIL_MINAS_GERA" +
      "IS\020\017\022\031\n\025TERRITORY_BRAZIL_PARA\020\020\022\033\n\027TERRI" +
      "TORY_BRAZIL_PARANA\020\021\022\037\n\033TERRITORY_BRAZIL" +
      "_PERNAMBUCO\020\022\022#\n\037TERRITORY_BRAZIL_RIO_DE" +
      "_JANEIRO\020\023\022&\n\"TERRITORY_BRAZIL_RIO_GRAND" +
      "E_DO_SUL\020\024\022#\n\037TERRITORY_BRAZIL_SANTA_CAT" +
      "ARINA\020\025\022\036\n\032TERRITORY_BRAZIL_SAO_PAOLO\020\026\022" +
      "\034\n\030TERRITORY_BRAZIL_SERGIPE\020\027\022\034\n\030TERRITO" +
      "RY_CANADA_ALBERTA\020\030\022%\n!TERRITORY_CANADA_" +
      "BRITISH_COLUMBIA\020\031\022\035\n\031TERRITORY_CANADA_M" +
      "ANITOBA\020\032\022\"\n\036TERRITORY_CANADA_NEW_BRUNSW" +
      "ICK\020\033\022.\n*TERRITORY_CANADA_NEWFOUNDLAND_A" +
      "ND_LABRADOR\020\034\022*\n&TERRITORY_CANADA_NORTHW" +
      "EST_TERRITORIES\020\035\022 \n\034TERRITORY_CANADA_NO" +
      "VA_SCOTIA\020\036\022\034\n\030TERRITORY_CANADA_NUNAVUT\020" +
      "\037\022\034\n\030TERRITORY_CANADA_ONTARIO\020 \022)\n%TERRI" +
      "TORY_CANADA_PRINCE_EDWARD_ISLAND\020!\022\033\n\027TE" +
      "RRITORY_CANADA_QUEBEC\020\"\022!\n\035TERRITORY_CAN" +
      "ADA_SASKATCHEWAN\020#\022\032\n\026TERRITORY_CANADA_Y" +
      "UKON\020$\022\"\n\036TERRITORY_INDIA_ANDHRA_PRADESH" +
      "\020%\022\033\n\027TERRITORY_INDIA_GUJARAT\020&\022\033\n\027TERRI" +
      "TORY_INDIA_HARYANA\020\'\022\035\n\031TERRITORY_INDIA_" +
      "KARNATAKA\020(\022\032\n\026TERRITORY_INDIA_KERALA\020)\022" +
      "\"\n\036TERRITORY_INDIA_MADHYA_PRADESH\020*\022\037\n\033T" +
      "ERRITORY_INDIA_MAHARASHTRA\020+\022\032\n\026TERRITOR" +
      "Y_INDIA_PUNJAB\020,\022\036\n\032TERRITORY_INDIA_TAMI" +
      "L_NADU\020-\022#\n\037TERRITORY_MEXICO_AGUASCALIEN" +
      "TES\020.\022$\n TERRITORY_MEXICO_BAJA_CALIFORNI" +
      "A\020/\022(\n$TERRITORY_MEXICO_BAJA_CALIFORNIA_" +
      "SUR\0200\022\035\n\031TERRITORY_MEXICO_CAMPECHE\0201\022\034\n\030" +
      "TERRITORY_MEXICO_CHIAPAS\0202\022\036\n\032TERRITORY_" +
      "MEXICO_CHIHUAHUA\0203\022%\n!TERRITORY_MEXICO_C" +
      "IUDAD_DE_MEXICO\0204\022\035\n\031TERRITORY_MEXICO_CO" +
      "AHUILA\0205\022\033\n\027TERRITORY_MEXICO_COLIMA\0206\022\034\n" +
      "\030TERRITORY_MEXICO_DURANGO\0207\022\037\n\033TERRITORY" +
      "_MEXICO_GUANAJUATO\0208\022\035\n\031TERRITORY_MEXICO" +
      "_GUERRERO\0209\022\034\n\030TERRITORY_MEXICO_HIDALGO\020" +
      ":\022\034\n\030TERRITORY_MEXICO_JALISCO\020;\022\033\n\027TERRI" +
      "TORY_MEXICO_MEXICO\020<\022\036\n\032TERRITORY_MEXICO" +
      "_MICHOACAN\020=\022\034\n\030TERRITORY_MEXICO_MORELOS" +
      "\020>\022\034\n\030TERRITORY_MEXICO_NAYARIT\020?\022\037\n\033TERR" +
      "ITORY_MEXICO_NUEVO_LEON\020@\022\033\n\027TERRITORY_M" +
      "EXICO_OAXACA\020A\022\033\n\027TERRITORY_MEXICO_PUEBL" +
      "A\020B\022\036\n\032TERRITORY_MEXICO_QUERETARO\020C\022!\n\035T" +
      "ERRITORY_MEXICO_QUINTANA_ROO\020D\022$\n TERRIT" +
      "ORY_MEXICO_SAN_LUIS_POTOSI\020E\022\034\n\030TERRITOR" +
      "Y_MEXICO_SINALOA\020F\022\033\n\027TERRITORY_MEXICO_S" +
      "ONORA\020G\022\034\n\030TERRITORY_MEXICO_TABASCO\020H\022\037\n" +
      "\033TERRITORY_MEXICO_TAMAULIPAS\020I\022\035\n\031TERRIT" +
      "ORY_MEXICO_TLAXCALA\020J\022\035\n\031TERRITORY_MEXIC" +
      "O_VERACRUZ\020K\022\034\n\030TERRITORY_MEXICO_YUCATAN" +
      "\020L\022\036\n\032TERRITORY_MEXICO_ZACATECAS\020M\022)\n%TE" +
      "RRITORY_PAKISTAN_KHYBER_PAKHTUNKHWA\020N\022\035\n" +
      "\031TERRITORY_PAKISTAN_PUNJAB\020O\022\031\n\025TERRITOR" +
      "Y_USA_ALABAMA\020P\022\030\n\024TERRITORY_USA_ALASKA\020" +
      "Q\022\031\n\025TERRITORY_USA_ARIZONA\020R\022\032\n\026TERRITOR" +
      "Y_USA_ARKANSAS\020S\022\034\n\030TERRITORY_USA_CALIFO" +
      "RNIA\020T\022\032\n\026TERRITORY_USA_COLORADO\020U\022\035\n\031TE" +
      "RRITORY_USA_CONNECTICUT\020V\022\032\n\026TERRITORY_U" +
      "SA_DELAWARE\020W\022&\n\"TERRITORY_USA_DISTRICT_" +
      "OF_COLUMBIA\020X\022\031\n\025TERRITORY_USA_FLORIDA\020Y" +
      "\022\031\n\025TERRITORY_USA_GEORGIA\020Z\022\030\n\024TERRITORY" +
      "_USA_HAWAII\020[\022\027\n\023TERRITORY_USA_IDAHO\020\\\022\032" +
      "\n\026TERRITORY_USA_ILLINOIS\020]\022\031\n\025TERRITORY_" +
      "USA_INDIANA\020^\022\026\n\022TERRITORY_USA_IOWA\020_\022\030\n" +
      "\024TERRITORY_USA_KANSAS\020`\022\032\n\026TERRITORY_USA" +
      "_KENTUCKY\020a\022\033\n\027TERRITORY_USA_LOUISIANA\020b" +
      "\022\027\n\023TERRITORY_USA_MAINE\020c\022\032\n\026TERRITORY_U" +
      "SA_MARYLAND\020d\022\037\n\033TERRITORY_USA_MASSACHUS" +
      "ETTS\020e\022\032\n\026TERRITORY_USA_MICHIGAN\020f\022\033\n\027TE" +
      "RRITORY_USA_MINNESOTA\020g\022\035\n\031TERRITORY_USA" +
      "_MISSISSIPPI\020h\022\032\n\026TERRITORY_USA_MISSOURI" +
      "\020i\022\031\n\025TERRITORY_USA_MONTANA\020j\022\032\n\026TERRITO" +
      "RY_USA_NEBRASKA\020k\022\030\n\024TERRITORY_USA_NEVAD" +
      "A\020l\022\037\n\033TERRITORY_USA_NEW_HAMPSHIRE\020m\022\034\n\030" +
      "TERRITORY_USA_NEW_JERSEY\020n\022\034\n\030TERRITORY_" +
      "USA_NEW_MEXICO\020o\022\032\n\026TERRITORY_USA_NEW_YO" +
      "RK\020p\022\037\n\033TERRITORY_USA_NEW_YORK_CITY\020q\022 \n" +
      "\034TERRITORY_USA_NORTH_CAROLINA\020r\022\036\n\032TERRI" +
      "TORY_USA_NORTH_DAKOTA\020s\022\026\n\022TERRITORY_USA" +
      "_OHIO\020t\022\032\n\026TERRITORY_USA_OKLAHOMA\020u\022\030\n\024T" +
      "ERRITORY_USA_OREGON\020v\022\036\n\032TERRITORY_USA_P" +
      "ENNSYLVANIA\020w\022\036\n\032TERRITORY_USA_RHODE_ISL" +
      "AND\020x\022 \n\034TERRITORY_USA_SOUTH_CAROLINA\020y\022" +
      "\036\n\032TERRITORY_USA_SOUTH_DAKOTA\020z\022\033\n\027TERRI" +
      "TORY_USA_TENNESSEE\020{\022\027\n\023TERRITORY_USA_TE" +
      "XAS\020|\022\026\n\022TERRITORY_USA_UTAH\020}\022\031\n\025TERRITO" +
      "RY_USA_VERMONT\020~\022\032\n\026TERRITORY_USA_VIRGIN" +
      "IA\020\177\022\035\n\030TERRITORY_USA_WASHINGTON\020\200\001\022 \n\033T" +
      "ERRITORY_USA_WEST_VIRGINIA\020\201\001\022\034\n\027TERRITO" +
      "RY_USA_WISCONSIN\020\202\001\022\032\n\025TERRITORY_USA_WYO" +
      "MING\020\203\001B4Z2github.com/veridil/id-extract" +
      "-service/proto/ddx/v1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
